import { defaultShaderMap } from '../../../functions/getTimeOfDay';
import { OverworldMap } from '../../../interfaces/OverworldMap';
import { campCaveOccupants } from './occupants/campCave';

export const campCave: OverworldMap = {
	area: 'OPEN',
	id: 'campCave',
	tilesetUrl: '/tilesets/newMasterSheet.png',
	occupants: campCaveOccupants,
	timeOfDayShadersMap: defaultShaderMap,
	tileMap: {
		baseLayer: [
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
			[
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
				{ yOffset: -432, xOffset: -64 },
			],
		],
		encounterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		obstacleLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -448, xOffset: -16 },
				{ yOffset: -432, xOffset: -16 },
				{ yOffset: -432, xOffset: -16 },
				{ yOffset: -432, xOffset: -16 },
				{ yOffset: -448, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -416, xOffset: -32 },
				{ yOffset: -448, xOffset: -16 },
				{ yOffset: -432, xOffset: -16 },
				{ yOffset: -448, xOffset: 0 },
				{ yOffset: -416, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -416, xOffset: -32 },
				{ yOffset: -416, xOffset: -32 },
				null,
				{ yOffset: -416, xOffset: 0 },
				{ yOffset: -416, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -448, xOffset: -16 },
				{ yOffset: -432, xOffset: -16 },
				{ yOffset: -432, xOffset: -16 },
				{ yOffset: -432, xOffset: -32 },
				{ yOffset: -416, xOffset: -32 },
				null,
				{ yOffset: -416, xOffset: 0 },
				{ yOffset: -432, xOffset: 0 },
				{ yOffset: -448, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -448, xOffset: -16 },
				{ yOffset: -432, xOffset: -16 },
				{ yOffset: -432, xOffset: -16 },
				{ yOffset: -432, xOffset: -32 },
				{ yOffset: -448, xOffset: -16 },
				{ yOffset: -448, xOffset: -64 },
				{ yOffset: -448, xOffset: -64 },
				{ yOffset: -432, xOffset: -32 },
				null,
				{ yOffset: -432, xOffset: 0 },
				{ yOffset: -448, xOffset: 0 },
				{ yOffset: -432, xOffset: 0 },
				{ yOffset: -432, xOffset: -16 },
				{ yOffset: -432, xOffset: -16 },
				{ yOffset: -448, xOffset: 0 },
				null,
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -416, xOffset: -32 },
				null,
				null,
				null,
				{ yOffset: -416, xOffset: -32 },
				null,
				null,
				null,
				null,
				{ yOffset: -432, xOffset: -96 },
				{ yOffset: -432, xOffset: 0 },
				{ yOffset: -432, xOffset: -16 },
				{ yOffset: -432, xOffset: -16 },
				{ yOffset: -448, xOffset: 0 },
				{ yOffset: -416, xOffset: 0 },
				null,
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -416, xOffset: -32 },
				null,
				null,
				null,
				{ yOffset: -416, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -416, xOffset: 0 },
				{ yOffset: -416, xOffset: 0 },
				null,
				null,
				null,
			],
			[
				null,
				{ yOffset: -448, xOffset: -16 },
				{ yOffset: -432, xOffset: -32 },
				{ yOffset: -432, xOffset: -96 },
				null,
				{ yOffset: -448, xOffset: -16 },
				{ yOffset: -432, xOffset: -32 },
				null,
				null,
				null,
				null,
				{ yOffset: -400, xOffset: 0 },
				null,
				{ yOffset: -464, xOffset: 0 },
				null,
				{ yOffset: -464, xOffset: -32 },
				{ yOffset: -416, xOffset: 0 },
				null,
				null,
				null,
			],
			[
				null,
				{ yOffset: -416, xOffset: -32 },
				{ yOffset: -448, xOffset: -16 },
				{ yOffset: -432, xOffset: -16 },
				null,
				{ yOffset: -432, xOffset: -32 },
				null,
				null,
				{ yOffset: -416, xOffset: -96 },
				{ yOffset: -400, xOffset: 0 },
				{ yOffset: -400, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				{ yOffset: -416, xOffset: -32 },
				{ yOffset: -416, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -416, xOffset: 0 },
				{ yOffset: -416, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				{ yOffset: -400, xOffset: -32 },
				null,
				null,
				{ yOffset: -400, xOffset: -32 },
				null,
				{ yOffset: -416, xOffset: 0 },
				{ yOffset: -416, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		decorationLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -400, xOffset: -16 },
				null,
				{ yOffset: -464, xOffset: -16 },
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				{ yOffset: -448, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				{ yOffset: -400, xOffset: -16 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		foregroundLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		waterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
	},
};
