import { defaultShaderMap } from '../../../functions/getTimeOfDay';
import { OverworldMap } from '../../../interfaces/OverworldMap';
import { rocketCampOccupants } from './occupants/rocketCampOccupants';

export const rocketCamp: OverworldMap = {
	area: 'OPEN',
	id: 'rocketCamp',
	occupants: rocketCampOccupants,
	timeOfDayShadersMap: defaultShaderMap,
	tilesetUrl: '/tilesets/market.png',
	tileMap: {
		baseLayer: [
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
			[
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
				{ yOffset: -16, xOffset: -128 },
			],
		],
		encounterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		obstacleLayer: [
			[
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -208, xOffset: -48 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -224, xOffset: -128 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -208, xOffset: -48 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -224, xOffset: -128 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -208, xOffset: -48 },
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -240, xOffset: -176 },
			],
			[
				{ yOffset: -64, xOffset: -48 },
				null,
				null,
				{ yOffset: -64, xOffset: -48 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -64, xOffset: -48 },
				null,
				null,
				null,
				{ yOffset: -64, xOffset: -48 },
				null,
				{ yOffset: -224, xOffset: -128 },
				{ yOffset: -224, xOffset: -128 },
			],
			[
				{ yOffset: -208, xOffset: -48 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -240, xOffset: -208 },
				{ yOffset: -64, xOffset: -48 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -224, xOffset: -128 },
				null,
				null,
				null,
				null,
				{ yOffset: -240, xOffset: -176 },
			],
			[
				{ yOffset: -224, xOffset: -160 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -208, xOffset: -48 },
				{ yOffset: -240, xOffset: -208 },
				{ yOffset: -240, xOffset: -208 },
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -224, xOffset: -128 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -224, xOffset: -160 },
			],
			[
				{ yOffset: -240, xOffset: -176 },
				null,
				null,
				null,
				null,
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -224, xOffset: -128 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -240, xOffset: -208 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -208, xOffset: -48 },
			],
			[
				{ yOffset: -208, xOffset: -48 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -224, xOffset: -160 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -240, xOffset: -176 },
			],
			[
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -224, xOffset: -128 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -224, xOffset: -160 },
			],
			[
				{ yOffset: -224, xOffset: -160 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -208, xOffset: -48 },
			],
			[
				{ yOffset: -240, xOffset: -176 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -64, xOffset: -48 },
				null,
				{ yOffset: -240, xOffset: -176 },
			],
			[
				{ yOffset: -208, xOffset: -48 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -64, xOffset: -48 },
			],
			[
				{ yOffset: -240, xOffset: -176 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -224, xOffset: -128 },
				null,
				null,
				{ yOffset: -224, xOffset: -128 },
			],
			[
				{ yOffset: -224, xOffset: -160 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -64, xOffset: -48 },
				null,
				{ yOffset: -240, xOffset: -176 },
			],
			[
				{ yOffset: -208, xOffset: -48 },
				{ yOffset: -224, xOffset: -128 },
				null,
				null,
				null,
				{ yOffset: -224, xOffset: -128 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -240, xOffset: -208 },
				{ yOffset: -224, xOffset: -160 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -224, xOffset: -128 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -224, xOffset: -160 },
			],
			[
				{ yOffset: -240, xOffset: -176 },
				null,
				null,
				null,
				null,
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -208, xOffset: -48 },
				{ yOffset: -240, xOffset: -208 },
				{ yOffset: -224, xOffset: -160 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -224, xOffset: -128 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -208, xOffset: -48 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -240, xOffset: -176 },
			],
			[
				{ yOffset: -240, xOffset: -176 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -240, xOffset: -208 },
				{ yOffset: -240, xOffset: -208 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -224, xOffset: -128 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -240, xOffset: -208 },
				{ yOffset: -208, xOffset: -48 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -224, xOffset: -160 },
			],
			[
				{ yOffset: -64, xOffset: -48 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -224, xOffset: -160 },
				null,
				{ yOffset: -240, xOffset: -208 },
				{ yOffset: -64, xOffset: -48 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -240, xOffset: -176 },
			],
			[
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -64, xOffset: -48 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -224, xOffset: -128 },
			],
			[
				{ yOffset: -208, xOffset: -48 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -224, xOffset: -160 },
			],
			[
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -224, xOffset: -160 },
				null,
				null,
				null,
				null,
				{ yOffset: -224, xOffset: -160 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -208, xOffset: -48 },
				{ yOffset: -64, xOffset: -48 },
			],
			[
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -64, xOffset: -48 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -64, xOffset: -48 },
				null,
				null,
				{ yOffset: -224, xOffset: -160 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -240, xOffset: -176 },
			],
			[
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -224, xOffset: -128 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -208, xOffset: -48 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -208, xOffset: -48 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -64, xOffset: -48 },
				{ yOffset: -224, xOffset: -128 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -224, xOffset: -160 },
				{ yOffset: -240, xOffset: -176 },
				{ yOffset: -240, xOffset: -176 },
			],
		],
		decorationLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		foregroundLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		waterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
	},
};
