import { defaultShaderMap } from '../../../functions/getTimeOfDay';
import { OverworldMap } from '../../../interfaces/OverworldMap';
import { victoryRoadExitOccupants } from './occupants/victoryRoadExit';

export const victoryRoadExit: OverworldMap = {
	area: 'OPEN',
	id: 'victoryRoadExit',
	tilesetUrl: '/tilesets/newMasterSheet.png',
	occupants: victoryRoadExitOccupants,
	timeOfDayShadersMap: defaultShaderMap,
	tileMap: {
		baseLayer: [
			[
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
			],
			[
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
			],
			[
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
			],
			[
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
			],
			[
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -208, xOffset: -320 },
				{ yOffset: -208, xOffset: -336 },
				{ yOffset: -208, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
			],
			[
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
			],
			[
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
			],
			[
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
			],
			[
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
			],
			[
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
			],
			[
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
			],
			[
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -224, xOffset: -320 },
				{ yOffset: -224, xOffset: -336 },
				{ yOffset: -224, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -240, xOffset: -320 },
				{ yOffset: -240, xOffset: -336 },
				{ yOffset: -240, xOffset: -352 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -416, xOffset: -224 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
			[
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
				{ yOffset: -736, xOffset: -16 },
			],
		],
		encounterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		obstacleLayer: [
			[
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -656, xOffset: -208 },
				{ yOffset: -656, xOffset: -224 },
				{ yOffset: -656, xOffset: -240 },
				{ yOffset: -656, xOffset: -256 },
				{ yOffset: -656, xOffset: -272 },
				{ yOffset: -656, xOffset: -288 },
				{ yOffset: -656, xOffset: -304 },
				{ yOffset: -656, xOffset: -320 },
				{ yOffset: -656, xOffset: -240 },
				{ yOffset: -656, xOffset: -336 },
				{ yOffset: -656, xOffset: -352 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
			],
			[
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -672, xOffset: -208 },
				{ yOffset: -672, xOffset: -224 },
				{ yOffset: -672, xOffset: -240 },
				{ yOffset: -672, xOffset: -256 },
				{ yOffset: -672, xOffset: -272 },
				{ yOffset: -672, xOffset: -288 },
				{ yOffset: -672, xOffset: -304 },
				{ yOffset: -672, xOffset: -320 },
				{ yOffset: -672, xOffset: -240 },
				{ yOffset: -672, xOffset: -336 },
				{ yOffset: -672, xOffset: -352 },
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
			],
			[
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				null,
				null,
				null,
				{ yOffset: -688, xOffset: -224 },
				{ yOffset: -688, xOffset: -240 },
				{ yOffset: -688, xOffset: -256 },
				{ yOffset: -688, xOffset: -272 },
				null,
				{ yOffset: -688, xOffset: -304 },
				{ yOffset: -688, xOffset: -320 },
				{ yOffset: -688, xOffset: -240 },
				{ yOffset: -688, xOffset: -336 },
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
			],
			[
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -704, xOffset: -272 },
				null,
				{ yOffset: -704, xOffset: -304 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
			],
			[
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
			],
			[
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -144 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
			],
			[
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
			],
			[
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				null,
				{ yOffset: -32, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
			],
			[
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -32, xOffset: -112 },
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
			],
			[
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
			],
			[
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -32, xOffset: -112 },
			],
			[
				{ yOffset: -720, xOffset: -32 },
				{ yOffset: -720, xOffset: -32 },
				{ yOffset: -32, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -720, xOffset: 0 },
			],
			[
				null,
				{ yOffset: -720, xOffset: -32 },
				{ yOffset: -720, xOffset: -32 },
				null,
				null,
				null,
				null,
				{ yOffset: -32, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -720, xOffset: 0 },
				{ yOffset: -720, xOffset: 0 },
			],
			[
				null,
				null,
				{ yOffset: -720, xOffset: -32 },
				{ yOffset: -720, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -720, xOffset: 0 },
				{ yOffset: -720, xOffset: 0 },
				null,
			],
			[
				null,
				null,
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -32, xOffset: -112 },
				null,
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -736, xOffset: 0 },
				null,
			],
			[
				null,
				null,
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -736, xOffset: 0 },
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -720, xOffset: -32 },
				{ yOffset: -720, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -720, xOffset: 0 },
				{ yOffset: -720, xOffset: 0 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -736, xOffset: 0 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				null,
				{ yOffset: -16, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -736, xOffset: 0 },
				null,
				null,
			],
			[
				{ yOffset: -720, xOffset: -32 },
				null,
				null,
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -112 },
				null,
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -736, xOffset: 0 },
				null,
				null,
			],
			[
				{ yOffset: -736, xOffset: -32 },
				null,
				null,
				null,
				{ yOffset: -720, xOffset: -32 },
				{ yOffset: -720, xOffset: -32 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -16, xOffset: -112 },
				{ yOffset: -720, xOffset: 0 },
				{ yOffset: -720, xOffset: 0 },
				null,
				null,
				null,
			],
			[
				null,
				{ yOffset: -720, xOffset: -32 },
				null,
				null,
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -32, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -736, xOffset: 0 },
				null,
				null,
				{ yOffset: -720, xOffset: 0 },
			],
			[
				null,
				{ yOffset: -736, xOffset: -32 },
				null,
				null,
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -736, xOffset: 0 },
				null,
				null,
				{ yOffset: -736, xOffset: 0 },
			],
			[
				null,
				null,
				{ yOffset: -720, xOffset: -32 },
				null,
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -736, xOffset: 0 },
				null,
				{ yOffset: -720, xOffset: 0 },
				null,
			],
			[
				null,
				null,
				{ yOffset: -736, xOffset: -32 },
				null,
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -736, xOffset: 0 },
				null,
				{ yOffset: -736, xOffset: 0 },
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -720, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				null,
				{ yOffset: -32, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -720, xOffset: 0 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				null,
				{ yOffset: -720, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -720, xOffset: 0 },
				null,
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -736, xOffset: 0 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				{ yOffset: -720, xOffset: -32 },
				{ yOffset: -720, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -32, xOffset: -112 },
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -720, xOffset: 0 },
				{ yOffset: -720, xOffset: 0 },
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				{ yOffset: -736, xOffset: -32 },
				{ yOffset: -736, xOffset: -32 },
				null,
				null,
				null,
				{ yOffset: -688, xOffset: -16 },
				null,
				{ yOffset: -688, xOffset: -48 },
				null,
				null,
				null,
				{ yOffset: -736, xOffset: 0 },
				{ yOffset: -736, xOffset: 0 },
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -720, xOffset: -32 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -720, xOffset: 0 },
				null,
				null,
				null,
				null,
			],
		],
		decorationLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -688, xOffset: -208 },
				null,
				null,
				null,
				null,
				{ yOffset: -688, xOffset: -288 },
				null,
				null,
				null,
				null,
				{ yOffset: -688, xOffset: -352 },
				null,
				{ yOffset: -672, xOffset: -160 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -704, xOffset: -208 },
				{ yOffset: -704, xOffset: -224 },
				{ yOffset: -704, xOffset: -240 },
				{ yOffset: -704, xOffset: -256 },
				null,
				{ yOffset: -704, xOffset: -288 },
				null,
				{ yOffset: -704, xOffset: -320 },
				{ yOffset: -704, xOffset: -240 },
				{ yOffset: -704, xOffset: -336 },
				{ yOffset: -704, xOffset: -352 },
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				{ yOffset: -656, xOffset: -144 },
				null,
				null,
				null,
				{ yOffset: -720, xOffset: -256 },
				{ yOffset: -720, xOffset: -272 },
				{ yOffset: -720, xOffset: -288 },
				{ yOffset: -720, xOffset: -304 },
				{ yOffset: -720, xOffset: -320 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -672, xOffset: -160 },
				null,
				{ yOffset: -656, xOffset: -144 },
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -672, xOffset: -160 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -656, xOffset: -144 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -656, xOffset: -144 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -672, xOffset: -160 },
				null,
				null,
				null,
			],
			[
				{ yOffset: -720, xOffset: -16 },
				null,
				null,
				null,
				{ yOffset: -672, xOffset: -160 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				{ yOffset: -848, xOffset: -128 },
				{ yOffset: -848, xOffset: -128 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -848, xOffset: -144 },
			],
			[
				null,
				{ yOffset: -848, xOffset: -128 },
				{ yOffset: -848, xOffset: -128 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -656, xOffset: -144 },
				null,
				null,
				null,
				null,
				{ yOffset: -848, xOffset: -144 },
				{ yOffset: -848, xOffset: -144 },
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -656, xOffset: -144 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -848, xOffset: -128 },
				{ yOffset: -848, xOffset: -128 },
				null,
				null,
				null,
				{ yOffset: -656, xOffset: -144 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -848, xOffset: -144 },
				{ yOffset: -848, xOffset: -144 },
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -656, xOffset: -144 },
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -848, xOffset: -128 },
				{ yOffset: -848, xOffset: -128 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -848, xOffset: -144 },
				{ yOffset: -848, xOffset: -144 },
				null,
				null,
			],
			[
				{ yOffset: -848, xOffset: -128 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -672, xOffset: -160 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				{ yOffset: -848, xOffset: -128 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -656, xOffset: -144 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -672, xOffset: -160 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -848, xOffset: -144 },
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -656, xOffset: -144 },
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -848, xOffset: -128 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -848, xOffset: -144 },
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -848, xOffset: -128 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -672, xOffset: -160 },
				null,
				null,
				{ yOffset: -848, xOffset: -144 },
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -848, xOffset: -128 },
				{ yOffset: -848, xOffset: -128 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -848, xOffset: -144 },
				{ yOffset: -848, xOffset: -144 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -848, xOffset: -128 },
				{ yOffset: -848, xOffset: -128 },
				{ yOffset: -720, xOffset: -16 },
				null,
				{ yOffset: -688, xOffset: -32 },
				null,
				{ yOffset: -720, xOffset: -16 },
				{ yOffset: -720, xOffset: -16 },
				{ yOffset: -848, xOffset: -144 },
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				{ yOffset: -848, xOffset: -128 },
				{ yOffset: -848, xOffset: -128 },
				{ yOffset: -720, xOffset: -16 },
				{ yOffset: -720, xOffset: -16 },
				{ yOffset: -720, xOffset: -16 },
				{ yOffset: -720, xOffset: -16 },
				{ yOffset: -720, xOffset: -16 },
				{ yOffset: -720, xOffset: -16 },
				{ yOffset: -720, xOffset: -16 },
				{ yOffset: -720, xOffset: -16 },
				{ yOffset: -720, xOffset: -16 },
				{ yOffset: -848, xOffset: -144 },
				{ yOffset: -848, xOffset: -144 },
				null,
				null,
				null,
			],
		],
		foregroundLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -112 },
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -112 },
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -112 },
				null,
				{ yOffset: 0, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -112 },
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		waterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
	},
};
