import { defaultShaderMap } from '../../../functions/getTimeOfDay';
import { OverworldMap } from '../../../interfaces/OverworldMap';
import { campLaboratoryOccupants } from './occupants/campLaboratory';

export const campLaboratory: OverworldMap = {
	area: 'BUILDING',
	id: 'campLaboratory',
	tilesetUrl: '/tilesets/newMasterSheet.png',
	occupants: campLaboratoryOccupants,
	questMenuAvailable: true,
	timeOfDayShadersMap: defaultShaderMap,
	tileMap: {
		baseLayer: [
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
			[
				{ yOffset: -416, xOffset: -176 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
				{ yOffset: -416, xOffset: -144 },
			],
		],
		encounterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		obstacleLayer: [
			[
				{ yOffset: -448, xOffset: -128 },
				{ yOffset: -448, xOffset: -144 },
				{ yOffset: -448, xOffset: -160 },
				{ yOffset: -448, xOffset: -176 },
				{ yOffset: -448, xOffset: -192 },
				{ yOffset: -448, xOffset: -208 },
				{ yOffset: -448, xOffset: -208 },
				{ yOffset: -448, xOffset: -208 },
				{ yOffset: -448, xOffset: -224 },
				{ yOffset: -448, xOffset: -256 },
				{ yOffset: -448, xOffset: -256 },
				{ yOffset: -448, xOffset: -304 },
				{ yOffset: -448, xOffset: -320 },
				{ yOffset: -448, xOffset: -336 },
				{ yOffset: -448, xOffset: -320 },
				{ yOffset: -448, xOffset: -336 },
				{ yOffset: -448, xOffset: -320 },
				{ yOffset: -448, xOffset: -336 },
				{ yOffset: -448, xOffset: -352 },
				{ yOffset: -448, xOffset: -368 },
			],
			[
				{ yOffset: -464, xOffset: -128 },
				{ yOffset: -464, xOffset: -144 },
				{ yOffset: -464, xOffset: -160 },
				{ yOffset: -464, xOffset: -176 },
				{ yOffset: -464, xOffset: -192 },
				{ yOffset: -464, xOffset: -208 },
				{ yOffset: -464, xOffset: -192 },
				{ yOffset: -464, xOffset: -208 },
				null,
				null,
				null,
				{ yOffset: -464, xOffset: -304 },
				{ yOffset: -464, xOffset: -320 },
				{ yOffset: -464, xOffset: -336 },
				{ yOffset: -464, xOffset: -320 },
				{ yOffset: -464, xOffset: -336 },
				{ yOffset: -464, xOffset: -320 },
				{ yOffset: -464, xOffset: -336 },
				{ yOffset: -464, xOffset: -352 },
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -528, xOffset: -272 },
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -576, xOffset: -176 },
			],
			[
				{ yOffset: -576, xOffset: -176 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -528, xOffset: -176 },
				{ yOffset: -528, xOffset: -192 },
				{ yOffset: -528, xOffset: -176 },
				{ yOffset: -528, xOffset: -192 },
				null,
				null,
				null,
			],
			[
				{ yOffset: -528, xOffset: -176 },
				{ yOffset: -528, xOffset: -192 },
				{ yOffset: -528, xOffset: -176 },
				{ yOffset: -528, xOffset: -192 },
				{ yOffset: -528, xOffset: -176 },
				{ yOffset: -528, xOffset: -192 },
				{ yOffset: -528, xOffset: -176 },
				{ yOffset: -528, xOffset: -192 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -576, xOffset: -176 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -544, xOffset: -224 },
				{ yOffset: -544, xOffset: -240 },
				null,
				{ yOffset: -528, xOffset: -176 },
				{ yOffset: -528, xOffset: -192 },
			],
			[
				{ yOffset: -576, xOffset: -176 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -576, xOffset: -176 },
				{ yOffset: -560, xOffset: -224 },
				{ yOffset: -560, xOffset: -240 },
				null,
				null,
				null,
			],
			[
				{ yOffset: -576, xOffset: -176 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -528, xOffset: -176 },
				{ yOffset: -528, xOffset: -192 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -528, xOffset: -176 },
				{ yOffset: -528, xOffset: -192 },
				{ yOffset: -528, xOffset: -176 },
				{ yOffset: -528, xOffset: -192 },
				{ yOffset: -576, xOffset: -176 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -528, xOffset: -176 },
				{ yOffset: -528, xOffset: -192 },
				{ yOffset: -528, xOffset: -176 },
				{ yOffset: -528, xOffset: -192 },
				{ yOffset: -528, xOffset: -176 },
				{ yOffset: -528, xOffset: -192 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				{ yOffset: -528, xOffset: -272 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -528, xOffset: -272 },
				null,
				null,
				null,
				{ yOffset: -528, xOffset: -272 },
				null,
				null,
				null,
				{ yOffset: -576, xOffset: -176 },
				{ yOffset: -576, xOffset: -176 },
				null,
				{ yOffset: -528, xOffset: -272 },
			],
			[
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -208 },
				{ yOffset: -608, xOffset: -224 },
				{ yOffset: -608, xOffset: -240 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
				{ yOffset: -608, xOffset: -192 },
			],
		],
		decorationLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -464, xOffset: -224 },
				{ yOffset: -464, xOffset: -256 },
				{ yOffset: -464, xOffset: -256 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -464, xOffset: -368 },
			],
			[
				{ yOffset: -480, xOffset: -128 },
				{ yOffset: -480, xOffset: -144 },
				{ yOffset: -480, xOffset: -160 },
				{ yOffset: -480, xOffset: -176 },
				{ yOffset: -480, xOffset: -192 },
				{ yOffset: -480, xOffset: -208 },
				{ yOffset: -480, xOffset: -192 },
				{ yOffset: -480, xOffset: -208 },
				{ yOffset: -480, xOffset: -256 },
				{ yOffset: -480, xOffset: -256 },
				{ yOffset: -480, xOffset: -256 },
				{ yOffset: -480, xOffset: -304 },
				{ yOffset: -480, xOffset: -320 },
				{ yOffset: -480, xOffset: -336 },
				{ yOffset: -480, xOffset: -320 },
				{ yOffset: -480, xOffset: -336 },
				{ yOffset: -480, xOffset: -320 },
				{ yOffset: -480, xOffset: -336 },
				{ yOffset: -480, xOffset: -352 },
				{ yOffset: -480, xOffset: -368 },
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -544, xOffset: -176 },
				{ yOffset: -544, xOffset: -192 },
				{ yOffset: -544, xOffset: -176 },
				{ yOffset: -544, xOffset: -192 },
				null,
				null,
				null,
			],
			[
				{ yOffset: -544, xOffset: -176 },
				{ yOffset: -544, xOffset: -192 },
				{ yOffset: -544, xOffset: -176 },
				{ yOffset: -544, xOffset: -192 },
				{ yOffset: -544, xOffset: -176 },
				{ yOffset: -544, xOffset: -192 },
				{ yOffset: -544, xOffset: -176 },
				{ yOffset: -544, xOffset: -192 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -544, xOffset: -176 },
				{ yOffset: -544, xOffset: -192 },
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -544, xOffset: -176 },
				{ yOffset: -544, xOffset: -192 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -544, xOffset: -176 },
				{ yOffset: -544, xOffset: -192 },
				{ yOffset: -544, xOffset: -176 },
				{ yOffset: -544, xOffset: -192 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -544, xOffset: -176 },
				{ yOffset: -544, xOffset: -192 },
				{ yOffset: -544, xOffset: -176 },
				{ yOffset: -544, xOffset: -192 },
				{ yOffset: -544, xOffset: -176 },
				{ yOffset: -544, xOffset: -192 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -592, xOffset: -208 },
				{ yOffset: -592, xOffset: -224 },
				{ yOffset: -592, xOffset: -240 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		foregroundLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -512, xOffset: -272 },
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -512, xOffset: -176 },
				{ yOffset: -512, xOffset: -192 },
				{ yOffset: -512, xOffset: -176 },
				{ yOffset: -512, xOffset: -192 },
				null,
				null,
				null,
			],
			[
				{ yOffset: -512, xOffset: -176 },
				{ yOffset: -512, xOffset: -192 },
				{ yOffset: -512, xOffset: -176 },
				{ yOffset: -512, xOffset: -192 },
				{ yOffset: -512, xOffset: -176 },
				{ yOffset: -512, xOffset: -192 },
				{ yOffset: -512, xOffset: -176 },
				{ yOffset: -512, xOffset: -192 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -528, xOffset: -224 },
				{ yOffset: -528, xOffset: -240 },
				null,
				{ yOffset: -512, xOffset: -176 },
				{ yOffset: -512, xOffset: -192 },
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -512, xOffset: -176 },
				{ yOffset: -512, xOffset: -192 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -512, xOffset: -176 },
				{ yOffset: -512, xOffset: -192 },
				{ yOffset: -512, xOffset: -176 },
				{ yOffset: -512, xOffset: -192 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -512, xOffset: -176 },
				{ yOffset: -512, xOffset: -192 },
				{ yOffset: -512, xOffset: -176 },
				{ yOffset: -512, xOffset: -192 },
				{ yOffset: -512, xOffset: -176 },
				{ yOffset: -512, xOffset: -192 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				{ yOffset: -512, xOffset: -272 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -512, xOffset: -272 },
				null,
				null,
				null,
				{ yOffset: -512, xOffset: -272 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -512, xOffset: -272 },
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		waterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
	},
};
