import { defaultShaderMap } from "../../../functions/getTimeOfDay";
import { OverworldMap } from "../../../interfaces/OverworldMap";
import { rocketCampOccupants } from "./occupants/rocketCampOccupants";

export const rocketCamp: OverworldMap = {
  resetOccupantsOnLeave: () => true,
  area: "OPEN",
  id: "rocketCamp",
  occupants: rocketCampOccupants,
  timeOfDayShadersMap: defaultShaderMap,
  tilesetUrl: "/tilesets/newMasterSheet.png",
  questMenuAvailable: true,
  tileMap: {
    baseLayer: [
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
      [
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
        { yOffset: -320, xOffset: -272 },
      ],
    ],
    encounterLayer: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    obstacleLayer: [
      [
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        { yOffset: -896, xOffset: -368 },
        null,
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        { yOffset: -288, xOffset: -208 },
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -288, xOffset: -208 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        null,
        { yOffset: -912, xOffset: -368 },
        { yOffset: -880, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -896, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        null,
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        { yOffset: -896, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        null,
        { yOffset: -304, xOffset: -304 },
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        { yOffset: -912, xOffset: -368 },
        null,
        { yOffset: -896, xOffset: -368 },
        null,
        null,
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -896, xOffset: -368 },
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        { yOffset: -912, xOffset: -368 },
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -896, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        { yOffset: -896, xOffset: -368 },
        null,
        null,
        null,
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        { yOffset: -896, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -896, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -896, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -896, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        null,
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        null,
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -896, xOffset: -368 },
        { yOffset: -304, xOffset: -304 },
        { yOffset: -896, xOffset: -368 },
        null,
        null,
        { yOffset: -304, xOffset: -304 },
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
        { yOffset: -304, xOffset: -304 },
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
        null,
        { yOffset: -304, xOffset: -304 },
        { yOffset: -896, xOffset: -368 },
        null,
        null,
        null,
        null,
        { yOffset: -304, xOffset: -304 },
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        null,
        { yOffset: -896, xOffset: -368 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        { yOffset: -288, xOffset: -208 },
        { yOffset: -896, xOffset: -368 },
        null,
        null,
        null,
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        { yOffset: -896, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -896, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        { yOffset: -896, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
        { yOffset: -304, xOffset: -304 },
        null,
        null,
        null,
        { yOffset: -896, xOffset: -368 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -896, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -896, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -880, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        null,
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -896, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
        { yOffset: -896, xOffset: -368 },
        { yOffset: -880, xOffset: -368 },
        null,
        { yOffset: -304, xOffset: -304 },
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        null,
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -912, xOffset: -368 },
      ],
      [
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -896, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -896, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -896, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -896, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -288, xOffset: -208 },
        { yOffset: -912, xOffset: -368 },
        { yOffset: -912, xOffset: -368 },
      ],
    ],
    decorationLayer: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    foregroundLayer: [
      [
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
      ],
      [
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
      ],
      [
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { yOffset: -880, xOffset: -368 },
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        { yOffset: -880, xOffset: -368 },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    waterLayer: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
  },
};
