export const campUpgradeNames = [
	'bulletin_board',
	'berry_farm',
	'invite apricorn smith kurt',
	'create seed vault',
	'second slot for farm',
	'third slot for farm',
	'fourth slot for farm',
	'fifth slot for farm',
	'sixth slot for farm',
	'seventh slot for farm',
	'team slot 3',
	'team slot 4',
	'team slot 5',
	'team slot 6',
	'bag size upgrade 1',
	'bag size upgrade 2',
	'bag size upgrade 3',
	'invite move tutor',
	'invite flying pokemon expert falkner',
	'invite normal pokemon expert whitney',
	'invite ghost expert morty',
	'invite fighting expert chuck',
	'invite steel pokemon expert jasmine',
	'invite ice pokemon expert pryce',
	'invite dragon pokemon expert clair',
	'invite professor rowan',
	'invite professor elm',
	'invite pikachu fan',
	'training field 1',
	'training field 2',
	'training field 3',
	'training field 4',
	'training field 5',
	'invite effort value expert',
	'build combee hive',
	'build miltank farm',
	'machete certification',
	'invite zigzagoon foragers',
	'invite dugtrio explorers',
	'invite amoongus compost researcher',
	'invite vileplume scent researcher',
	'invite fossil expert',
	'invite chef grandma',
	'pokemon swarm radar',
	'upgraded swarm radar',
	'time distortion radar',
	'space distortion radar',
	'sledge hammer certification',
	'shovel certification',
	'swimming certification',
	'rock climbing certification',
	'flashlight certification',
	'invite museum curator',
	'berry lure station routeN1',
	'berry lure station routeN1E1',
	'berry lure station routeE1',
	'berry lure station routeS1E1',
	'berry lure station routeS1W1',
	'berry lure station routeW1',
	'buy skiing equipment',
	'invite historian',
	'ranger certification',
	'warden certification',
	'dragonite taxi',
	'invite nature tutor',
	'invite ability tutor',
	'pidgeot rider certification',
	'battle journalist',
] as const;

export type CampUpgrade = (typeof campUpgradeNames)[number];

export type CampUpgradeCategory =
	| 'Sustainability'
	| 'Exploration'
	| 'Research'
	| 'Training'
	| 'Quest Reward';

export const campUpgradeCategories: Record<CampUpgrade, CampUpgradeCategory> = {
	bulletin_board: 'Research',
	berry_farm: 'Sustainability',
	'create seed vault': 'Sustainability',
	'invite apricorn smith kurt': 'Sustainability',
	'build combee hive': 'Sustainability',
	'build miltank farm': 'Sustainability',
	'invite chef grandma': 'Sustainability',
	'second slot for farm': 'Sustainability',
	'third slot for farm': 'Sustainability',
	'fourth slot for farm': 'Sustainability',
	'fifth slot for farm': 'Sustainability',
	'sixth slot for farm': 'Sustainability',
	'seventh slot for farm': 'Sustainability',
	'invite zigzagoon foragers': 'Sustainability',
	'invite dugtrio explorers': 'Sustainability',
	'invite amoongus compost researcher': 'Sustainability',
	'invite vileplume scent researcher': 'Sustainability',
	'invite museum curator': 'Sustainability',
	'invite ghost expert morty': 'Research',
	'invite fighting expert chuck': 'Research',
	'invite steel pokemon expert jasmine': 'Research',
	'invite ice pokemon expert pryce': 'Research',
	'invite dragon pokemon expert clair': 'Research',
	'invite flying pokemon expert falkner': 'Research',
	'invite normal pokemon expert whitney': 'Research',
	'invite professor rowan': 'Research',
	'invite professor elm': 'Research',
	'invite pikachu fan': 'Research',
	'pokemon swarm radar': 'Research',
	'upgraded swarm radar': 'Research',
	'time distortion radar': 'Research',
	'space distortion radar': 'Research',
	'invite fossil expert': 'Research',
	'invite historian': 'Research',
	'invite move tutor': 'Training',
	'invite effort value expert': 'Training',
	'training field 1': 'Training',
	'training field 2': 'Training',
	'training field 3': 'Training',
	'training field 4': 'Training',
	'training field 5': 'Training',
	'invite nature tutor': 'Training',
	'invite ability tutor': 'Training',
	'ranger certification': 'Training',
	'battle journalist': 'Training',
	'machete certification': 'Exploration',
	'sledge hammer certification': 'Exploration',
	'shovel certification': 'Exploration',
	'rock climbing certification': 'Exploration',
	'flashlight certification': 'Exploration',
	'buy skiing equipment': 'Exploration',
	'bag size upgrade 1': 'Exploration',
	'bag size upgrade 2': 'Exploration',
	'bag size upgrade 3': 'Exploration',
	'team slot 3': 'Exploration',
	'team slot 4': 'Exploration',
	'team slot 5': 'Exploration',
	'team slot 6': 'Exploration',
	'dragonite taxi': 'Exploration',
	'swimming certification': 'Quest Reward',
	'pidgeot rider certification': 'Quest Reward',
	'warden certification': 'Quest Reward',
	'berry lure station routeN1': 'Quest Reward',
	'berry lure station routeN1E1': 'Quest Reward',
	'berry lure station routeE1': 'Quest Reward',
	'berry lure station routeS1E1': 'Quest Reward',
	'berry lure station routeS1W1': 'Quest Reward',
	'berry lure station routeW1': 'Quest Reward',
};

export const baseRequirements: CampUpgrade[] = [
	'bulletin_board',
	'berry_farm',
	'invite apricorn smith kurt',
];

export const campUpgradeConditions: Record<CampUpgrade, CampUpgrade[]> = {
	bulletin_board: [],
	berry_farm: ['bulletin_board'],
	'invite apricorn smith kurt': ['bulletin_board'],
	'create seed vault': baseRequirements,
	'invite move tutor': baseRequirements,
	'invite effort value expert': ['invite move tutor', 'training field 1'],
	'invite nature tutor': ['invite move tutor', 'training field 1'],
	'invite ability tutor': ['invite move tutor', 'training field 1'],
	'invite ghost expert morty': ['machete certification'],
	'invite fighting expert chuck': ['machete certification'],
	'invite steel pokemon expert jasmine': ['sledge hammer certification'],
	'invite dragon pokemon expert clair': ['swimming certification'],
	'invite ice pokemon expert pryce': ['machete certification'],
	'invite flying pokemon expert falkner': ['machete certification'],
	'invite normal pokemon expert whitney': ['shovel certification'],
	'invite professor rowan': baseRequirements,
	'invite professor elm': baseRequirements,
	'invite pikachu fan': baseRequirements,
	'machete certification': baseRequirements,
	'training field 1': baseRequirements,
	'training field 2': ['training field 1'],
	'training field 3': ['training field 2'],
	'training field 4': ['training field 3'],
	'training field 5': ['training field 4'],
	'build combee hive': baseRequirements,
	'build miltank farm': baseRequirements,
	'invite chef grandma': baseRequirements,
	'pokemon swarm radar': baseRequirements,
	'upgraded swarm radar': ['pokemon swarm radar', 'ranger certification'],
	'time distortion radar': ['upgraded swarm radar', 'warden certification'],
	'space distortion radar': ['time distortion radar'],
	'second slot for farm': baseRequirements,
	'third slot for farm': ['second slot for farm'],
	'fourth slot for farm': ['third slot for farm'],
	'fifth slot for farm': ['fourth slot for farm'],
	'sixth slot for farm': ['sixth slot for farm'],
	'seventh slot for farm': ['seventh slot for farm'],
	'invite zigzagoon foragers': baseRequirements,
	'invite dugtrio explorers': ['build combee hive'],
	'invite amoongus compost researcher': baseRequirements,
	'invite vileplume scent researcher': baseRequirements,
	'invite fossil expert': ['sledge hammer certification'],
	'sledge hammer certification': ['machete certification'],
	'ranger certification': ['machete certification', 'training field 1'],
	'shovel certification': ['sledge hammer certification'],
	'flashlight certification': ['shovel certification'],
	'rock climbing certification': ['swimming certification'],
	'buy skiing equipment': ['rock climbing certification'],
	'invite museum curator': ['invite dugtrio explorers'],
	'invite historian': ['buy skiing equipment'],
	'bag size upgrade 1': baseRequirements,
	'bag size upgrade 2': ['bag size upgrade 1'],
	'bag size upgrade 3': ['bag size upgrade 2'],
	'team slot 3': [...baseRequirements],
	'team slot 4': ['team slot 3'],
	'team slot 5': ['team slot 4'],
	'team slot 6': ['team slot 5'],
	'dragonite taxi': ['swimming certification'],
	'battle journalist': baseRequirements,

	//"Quest rewards"
	'swimming certification': [],
	'pidgeot rider certification': [],
	'warden certification': ['ranger certification'],
	'berry lure station routeN1': [],
	'berry lure station routeN1E1': [],
	'berry lure station routeE1': [],
	'berry lure station routeS1E1': [],
	'berry lure station routeS1W1': [],
	'berry lure station routeW1': [],
};

export const campUpgradeExplanations: Record<CampUpgrade, string> = {
	bulletin_board: 'A place for people to post quests',
	berry_farm: 'Berries, Apricorns and Herbs are our main resources',
	'invite apricorn smith kurt': 'Pokeballs can be made from apricorns',
	'invite move tutor': 'Teaches your Pokemon new moves',
	'invite nature tutor': 'Can change your Pokemons Nature',
	'invite ability tutor': 'Can change your Pokemons Ability',
	'invite effort value expert': 'Train your Pokemons Effort values with ease',
	'invite ghost expert morty':
		'The Gym Leader from Ecruteak studies ghost pokemon',
	'invite fighting expert chuck':
		'The Gym Leader from Cianwood loves to battle',
	'invite flying pokemon expert falkner':
		'The Gym Leader from Violet city studies flying pokemon',
	'invite normal pokemon expert whitney':
		'The Gym Leader from Goldenrod City studies normal pokemon',
	'invite steel pokemon expert jasmine':
		'The Gym Leader from Olivine City studies steel pokemon',
	'invite dragon pokemon expert clair':
		'The Gym Leader from Blackthorn City studies dragon pokemon',
	'invite ice pokemon expert pryce':
		'The Gym Leader from Mahogany City studies ice pokemon',
	'invite professor rowan':
		'professor rowan collects pokemon from all over the world',
	'invite professor elm': 'professor elm studies pokemon evolution',
	'invite pikachu fan': 'Tell me, are you a fan of the pikachu',
	'machete certification': 'Safety Training for bush cutting',
	'ranger certification':
		'Pokemon Rangers keep the land safe from poachers like team rocket',
	'training field 1': 'Train your Pokemon against other trainers',
	'training field 2': 'Invite Stronger Trainers (Lvl 20)',
	'training field 3': 'Invite Even Stronger Trainers (Lvl 30)',
	'training field 4': 'Invite Even Stronger Trainers (Lvl 40)',
	'training field 5': 'Invite Even Stronger Trainers (Lvl 50)',
	'build combee hive': 'Gathering our own honey would be useful',
	'build miltank farm': 'All Pokemon like to drink miltank milk',
	'invite chef grandma': 'Raw Ingredients can be improved through cooking',
	'pokemon swarm radar': 'Detects Pokemon that migrate in swarms',
	'upgraded swarm radar': 'Can detect stronger pokemon',
	'time distortion radar': 'Can detect time distortions with rare pokemon',
	'space distortion radar': 'Can detect space distortions with rare pokemon',
	'second slot for farm': 'more space at the berry farm',
	'third slot for farm': 'more space at the berry farm',
	'fourth slot for farm': 'more space at the berry farm',
	'invite zigzagoon foragers': 'zigzagoon can find berries and other items',
	'invite dugtrio explorers': 'dugtrio can find rare items underground',
	'invite amoongus compost researcher': 'amoongus can produce mulch',
	'invite vileplume scent researcher':
		'vileplume can produce repel and other scent based items',
	'invite fossil expert': 'maybe we can revive fossilized pokemon',
	'sledge hammer certification': 'Safety Training for rock smashing',
	'shovel certification': 'Safety Training for digging into ledges',
	'flashlight certification': 'Safety Training for cave exploration',
	'swimming certification':
		'The Research center is not responsible if you drown',
	'rock climbing certification':
		'The Research center is not responsible if you fall',
	'buy skiing equipment':
		'Unfortunately, all research assistants must provide their own skiing equipment',
	'invite museum curator': 'Some items we find might be valuable',
	'create seed vault': 'Safely stores seeds so we never run out',
	'bag size upgrade 1': 'More space in your field bag',
	'bag size upgrade 2': 'More space in your field bag',
	'bag size upgrade 3': 'More space in your field bag',
	'team slot 3': 'take up to 3 pokemon with you',
	'team slot 4': 'take up to 4 pokemon with you',
	'team slot 5': 'take up to 5 pokemon with you',
	'team slot 6': 'take up to 6 pokemon with you',
	'berry lure station routeN1': 'Place berries inside to attract pokemon',
	'berry lure station routeN1E1': 'Place berries inside to attract pokemon',
	'berry lure station routeE1': 'Place berries inside to attract pokemon',
	'berry lure station routeS1E1': 'Place berries inside to attract pokemon',
	'berry lure station routeS1W1': 'Place berries inside to attract pokemon',
	'berry lure station routeW1': 'Place berries inside to attract pokemon',
	'fifth slot for farm': 'more space at the berry farm',
	'sixth slot for farm': 'more space at the berry farm',
	'seventh slot for farm': 'more space at the berry farm',
	'invite historian': 'It might not all be true, but it sounds interesting',
	'dragonite taxi':
		'dragonite can fly you to remote places if you have the correct ticket',
	'pidgeot rider certification':
		'Expert flying Pokemon Trainers can ride on their pokemon',
	'warden certification':
		'Wardens are strong rangers that take on more difficult tasks',
	'battle journalist':
		'He knows everything about the strong trainers in the region',
};

export const campUpgradeCostScale = 25;
