export const customItemDescriptions: Record<string, string> = {
  "growth-mulch": "makes berries grow faster",
  "damp-mulch": "makes berries less likely to wither",
  "stable-mulch": "produces 25% more berries",
  "gooey-mulch": "berries grow 25% slower, but yield 50% more",
  "rich-mulch": "guaranteed success, but fewer berries",
  "surprise-mulch": "will grow into a different berry than planted",
  "amaze-mulch": "same as surprise, but higher yield and higher risk",
  "boost-mulch": "grow a small amount of berries 6 times faster",
  repel: "Repel Pokemon up to level 20 for one hour",
  "super-repel": "Repel Pokemon up to level 40 for one hour",
  "max-repel": "Repel Pokemon up to level 60 for one hour",
  lure: "Attracts weak pokemon for 10 minutes",
  "super-lure": "Attracts medium strong pokemon for 10 minutes",
  "max-lure": "Attracts strong pokemon for 30 minutes",
  "health-mochi": "increases health ev by 10",
  "genius-mochi": "increases special attack ev by 10",
  "clever-mochi": "increases special defense ev by 10",
  "resist-mochi": "increases defense ev by 10",
  "muscle-mochi": "increases attack ev by 10",
  "swift-mochi": "increases speed ev by 10",
  "scroll-of-waters": "used to evolve kubfu",
  "scroll-of-darkness": "used to evolve kubfu",
  "moomoo-cheese": "a tasty snack, humans seem to like it more than pokemon",
  "max-honey": "fully heals a fainted pokemon",
  "peat-block": "used to evolve ursaring",
  "chipped-pot": "Museums might find this interesting",
  "cracked-pot": "Museums might find this interesting",
  "shell-bell":
    "When holder damages an opponent, holder heals by 1/8 of damage",
  "relic-crown": "Museums might find this interesting",
  "relic-statue": "Museums might find this interesting",
  "big-mushroom": "Museums might find this interesting",
  "star-piece": "Museums might find this interesting",
};
