import { getHeldItem } from '../functions/getHeldItem';
import { BattlePokemon } from '../interfaces/BattlePokemon';
import { MoveName } from './checkLists/movesCheckList';

export const secondTurnMoves = [
	'razor-wind',
	'skull-bash',
	'solar-beam',
	'fly',
	'dig',
	'dive',
	'bounce',
	'sky-attack',
	'shadow-force',
	'freeze-shock',
	'ice-burn',
	'phantom-force',
	'geomancy',
];

export const soundBasedMoves = [
	'alluring-voice',
	'boomburst',
	'bug-buzz',
	'chatter',
	'clanging-scales',
	'clangorous-soul',
	'clangorous-soulblaze',
	'confide',
	'disarming-voice',
	'echoed-voice',
	'eerie-spell',
	'grass-whistle',
	'growl',
	'heal-bell',
	'howl',
	'hyper-voice',
	'metal-sound',
	'noble-roar',
	'overdrive',
	'parting-shot',
	'perish-song',
	'psychic-noise',
	'relic-song',
	'roar',
	'round',
	'screech',
	'shadow-panic',
	'sing',
	'snarl',
	'snore',
	'sparkling-aria',
	'supersonic',
	'torch-song',
	'uproar',
];

export const SELF_DESTRUCTING_MOVES = [
	'explosion',
	'misty-explosion',
	'self-destruct',
	'mind-blown',
];

export const recoveryMoves = [
	'hyper-beam',
	'blast-burn',
	'hydro-cannon',
	'frenzy-plant',
	'giga-impact',
	'rock-wrecker',
	'roar-of-time',
];

const contactMoves = [
	'accelerock',
	'acrobatics',
	'aerial-ace',
	'anchor-shot',
	'aqua-jet',
	'aqua-step',
	'aqua-tail',
	'arm-thrust',
	'assurance',
	'astonish',
	'avalanche',
	'axe-kick',
	'behemoth-bash',
	'behemoth-blade',
	'bide',
	'bind',
	'bite',
	'bitter-blade',
	'blaze-kick',
	'body-press',
	'body-slam',
	'bolt-beak',
	'bolt-strike',
	'bounce',
	'branch-poke',
	'brave-bird',
	'breaking-swipe',
	'brick-break',
	'brutal-swing',
	'bug-bite',
	'bullet-punch',
	'catastropika',
	'ceaseless-edge',
	'chip-away',
	'circle-throw',
	'clamp',
	'close-combat',
	'collision-course',
	'comet-punch',
	'comeuppance',
	'constrict',
	'counter',
	'covet',
	'crabhammer',
	'cross-chop',
	'cross-poison',
	'crunch',
	'crush-claw',
	'crush-grip',
	'cut',
	'darkest-lariat',
	'dig',
	'dire-claw',
	'dive',
	'dizzy-punch',
	'double-edge',
	'double-hit',
	'double-iron-bash',
	'double-kick',
	'double-shock',
	'double-slap',
	'draon-ascent',
	'dragon-claw',
	'dragon-hammer',
	'dragon-rush',
	'dragon-tail',
	'draining-kiss',
	'drain-punch',
	'drill-peck',
	'drill-run',
	'dual-chop',
	'dual-wingbeat',
	'dynamic-punch',
	'electro-drift',
	'endeavor',
	'extreme-speed',
	'facade',
	'fake-out',
	'false-surrender',
	'false-swipe',
	'feint-attack',
	'fell-stinger',
	'fire-fang',
	'fire-lash',
	'fire-punch',
	'first-impression',
	'fishious-rend',
	'flail',
	'flame-charge',
	'flame-wheel',
	'flare-blitz',
	'flip-turn',
	'floaty-fall',
	'fly',
	'flying-press',
	'focus-punch',
	'force-palm',
	'foul-play',
	'frustration',
	'fury-attack',
	'fury-cutter',
	'fury-swipes',
	'gear-grind',
	'giga-impact',
	'glaive-rush',
	'grass-knot',
	'grassy-glide',
	'guillotine',
	'gyro-ball',
	'hammer-arm',
	'hard-press',
	'headbutt',
	'head-charge',
	'headlong-rush',
	'head-smash',
	'heart-stamp',
	'heat-crash',
	'heavy-slam',
	'high-horsepower',
	'high-jump-kick',
	'hold-back',
	'horn-attack',
	'horn-drill',
	'horn-leech',
	'hyper-drill',
	'hyper-fang',
	'ice-ball',
	'ice-fang',
	'ice-hammer',
	'ice-punch',
	'ice-spinner',
	'infestation',
	'iron-head',
	'iron-tail',
	'jaw-lock',
	'jet-punch',
	'jump-kick',
	'karate-chop',
	'knock-off',
	'kowtow-cleave',
	'lash-out',
	'last-resort',
	'leaf-blade',
	'leech-life',
	'lets-snuggle-forever',
	'lick',
	'liquidation',
	'low-kick',
	'low-sweep',
	'lunge',
	'mach-punch',
	'malicious-moonsault',
	'megahorn',
	'mega-kick',
	'mega-punch',
	'metal-claw',
	'meteor-mash',
	'mighty-cleave',
	'mortal-spin',
	'multi-attack',
	'needle-arm',
	'night-slash',
	'nuzzle',
	'outrage',
	'payback',
	'peck',
	'petal-dance',
	'phantom-force',
	'plasma-fists',
	'play-rough',
	'pluck',
	'poison-fang',
	'poison-jab',
	'poison-tail',
	'population-bomb',
	'pounce',
	'pound',
	'power-trip',
	'power-up-punch',
	'power-whip',
	'psyblade',
	'psychic-fangs',
	'psyshield-bash',
	'pulverizing-pancake',
	'punishment',
	'pursuit',
	'quick-attack',
	'rage',
	'rage-fist',
	'raging-bull',
	'rapid-spin',
	'razor-shell',
	'retaliate',
	'return',
	'revenge',
	'reversal',
	'rock-climb',
	'rock-smash',
	'rolling-kick',
	'rollout',
	'sacred-sword',
	'scratch',
	'searing-sunraze-smash',
	'seismic-toss',
	'shadow-claw',
	'shadow-force',
	'shadow-punch',
	'shadow-sneak',
	'shadow-strike',
	'sizzly-slide',
	'skitter-smack',
	'skull-bash',
	'sky-drop',
	'sky-uppercut',
	'slam',
	'slash',
	'smart-strike',
	'smelling-salts',
	'snap-trap',
	'solar-blade',
	'soul-stealing-7-star-strike',
	'spark',
	'spectral-thief',
	'spin-out',
	'spirit-break',
	'steamroller',
	'steel-roller',
	'steel-wing',
	'stomp',
	'stomping-tantrum',
	'stone-axe',
	'storm-throw',
	'strength',
	'struggle',
	'submission',
	'sucker-punch',
	'sunsteel-strike',
	'supercell-slam',
	'super-fang',
	'superpower',
	'surging-strikes',
	'tackle',
	'tail-slap',
	'take-down',
	'temper-flare',
	'thief',
	'throat-chop',
	'thunder-fang',
	'thunderous-kick',
	'thunder-punch',
	'trailblaze',
	'triple-axel',
	'triple-dive',
	'triple-kick',
	'trop-kick',
	'trump-card',
	'u-turn',
	'uppper-hand',
	'v-create',
	'veevee-volley',
	'vine-whip',
	'vise-grip',
	'vital-throw',
	'volt-tackle',
	'wake-up-slap',
	'waterfall',
	'wave-crash',
	'wicked-blow',
	'wild-charge',
	'wing-attack',
	'wood-hammer',
	'wrap',
	'wring-out',
	'x-scissor',
	'zen-headbutt',
	'zing-zap',
	'zippy-zap',
];

export const isContactMove = (move: MoveName, pokemon: BattlePokemon) => {
	if (pokemon.ability === 'long-reach') {
		return false;
	}
	if (
		getHeldItem(pokemon) === 'punching-glove' &&
		punchBasedMoves.includes(move)
	) {
		return false;
	}
	return contactMoves.includes(move);
};
export const forceSwitchMoves = ['whirlwind', 'roar'];

export const thrashingMoves = ['thrash', 'petal-dance', 'outrage'];

export const crashDamageMoves = [
	'jump-kick',
	'axe-kick',
	'high-jump-kick',
	'supercell-slam',
];

export const ohkoMoves = ['guillotine', 'sheer-cold', 'fissure', 'horn-drill'];

export const flyHitMoves = [
	'gust',
	'twister',
	'thunder',
	'sky-uppercut',
	'smack-down',
	'magnet-bomb',
	'hurricane',
];
export const digHitMoves = ['earthquake', 'magnitude', 'magnet-bomb'];
export const shadowHitMoves = ['magnet-bomb'];
export const flyDoubleDamageMoves = ['gust', 'twister'];
export const diveDoubleDamageMoves = ['surf', 'whirlpool'];

export const passThroughProtectMoves = [
	'acupressure',
	'doom-desire',
	'future-sight',
	'feint',
	'imprison',
	'perish-song',
	'phantom-force',
	'play-nice',
	'psych-up',
	'shadow-force',
	'shadow-force',
	'transform',
	'mighty-cleave',
	'hyperspace-hole',
	'hyperspace-fury',
];

export const fixedDamageMoves: Record<string, number> = {
	'sonic-boom': 20,
	'dragon-rage': 40,
};

export const levelDamageMoves: string[] = ['seismic-toss', 'night-shade'];

export const punchBasedMoves = [
	'bullet-punch',
	'comet-punch',
	'dizzy-punch',
	'double-iron-bash',
	'drain-punch',
	'dynamic-punch',
	'fire-punch',
	'focus-punch',
	'hammer-arm',
	'headlong-rush',
	'ice-hammer',
	'ice-punch',
	'jet-punch',
	'mach-punch',
	'mega-punch',
	'meteor-mash',
	'plasma-fists',
	'power-up-punch',
	'rage-fist',
	'shadow-punch',
	'sky-uppercut',
	'surging-strikes',
	'thunder-punch',
	'wicked-blow',
];

export const ballAndBombMoves = [
	'egg-bomb',
	'barrage',
	'sludge-bomb',
	'octazooka',
	'zap-cannon',
	'shadow-ball',
	'mist-ball',
	'ice-ball',
	'weather-ball',
	'bullet-seed',
	'rock-blast',
	'gyro-ball',
	'aura-sphere',
	'seed-bomb',
	'focus-blast',
	'energy-ball',
	'mud-bomb',
	'rock-wrecker',
	'magnet-bomb',
	'electro-ball',
	'acid-spray',
	'searing-shot',
	'pollen-puff',
	'beak-blast',
	'pyro-all',
	'syrup-bomb',
];

export const bitingMoves = [
	'bite',
	'hyper-fang',
	'chrunch',
	'poison-fang',
	'thunder-fang',
	'ice-fang',
	'fire-fang',
	'psychic-fangs',
	'jaw-lock',
	'fishious-rend',
];
export const auraAndPulseMoves = [
	'aura-sphere',
	'dark-pulse',
	'dragon-pulse',
	'heal-pulse',
	'terrain-pulse',
	'water-pulse',
	'heal-pulse',
];

export const powderMoves = [
	'Poison Powder',
	'Stun Spore',
	'Sleep Powder',
	'Spore',
	'Cotton Spore',
	'Rage Powder',
	'Powder',
	'Magic Powder',
];
export const danceMoves = [
	'aqua-step',
	'clangorous-soul',
	'dragon-dance',
	'feather-dance',
	'fiery-dance',
	'lunar-dance',
	'petal-dance',
	'revelation-dance',
	'quiver-dance',
	'swords-dance',
	'teeter-dance',
	'victory-dance',
];

export const windMoves = [
	'aeroblast',
	'air-cutter',
	'bleakwind-storm',
	'blizzard',
	'fairy-wind',
	'gust',
	'heat-wave',
	'hurricane',
	'icy-wind',
	'petal-blizzard',
	'sandsear-storm',
	'sandstorm',
	'springtide-storm',
	'tailwind',
	'twister',
	'whirlwind',
	'wildbolt-storm',
];

export const slicingMoves = [
	'cut',
	'razor-leaf',
	'slash',
	'fury-cutter',
	'air-cutter',
	'aerial-ace',
	'leaf-blade',
	'night-slash',
	'air-slash',
	'x-scissor',
	'psycho-cut',
	'cross-poison',
	'sacred-sword',
	'razor-shell',
	'secret-sword',
	'solar-blade',
	'behemoth-blade',
	'stone-axe',
	'ceaseless-edge',
	'kowtow-cleave',
	'psyblade',
	'bitter-blade',
	'aqua-cutter',
	'mighty-cleave',
	'tachyon-cutter',
];
