export const passThroughProtectMoves = [
	'acupressure',
	'doom-desire',
	'future-sight',
	'feint',
	'imprison',
	'perish-song',
	'phantom-force',
	'play-nice',
	'psych-up',
	'shadow-force',
	'shadow-force',
	'transform',
	'mighty-cleave',
];
