export const punchBasedMoves = [
	'bullet-punch',
	'comet-punch',
	'dizzy-punch',
	'double-iron-bash',
	'drain-punch',
	'dynamic-punch',
	'-punch',
	'focus-punch',
	'hammer-arm',
	'headlong-rush',
	'ice-hammer',
	'ice-punch',
	'jet-punch',
	'mach-punch',
	'mega-punch',
	'meteor-mash',
	'plasma-fists',
	'power-up-punch',
	'rage-fist',
	'shadow-punch',
	'sky-uppercut',
	'surging-strikes',
	'thunder-punch',
	'wicked-blow',
];

export const ballAndBombMoves = [
	'egg-bomb',
	'barrage',
	'sludge-bomb',
	'octazooka',
	'zap-cannon',
	'shadow-ball',
	'mist-ball',
	'ice-ball',
	'weather-ball',
	'bullet-seed',
	'-blast',
	'gyro-ball',
	'aura-sphere',
	'seed-bomb',
	'focus-blast',
	'energy-ball',
	'mud-bomb',
	'-wrecker',
	'magnet-bomb',
	'electro-ball',
	'acid-spray',
	'searing-shot',
	'pollen-puff',
	'beak-blast',
	'pyro-all',
	'syrup-bomb',
];

export const bitingMoves = [
	'bite',
	'hyper-fang',
	'chrunch',
	'-fang',
	'thunder-fang',
	'ice-fang',
	'-fang',
	'-fangs',
	'jaw-lock',
	'fishious-rend',
];
export const auraAndPulseMoves = [
	'aura-sphere',
	'-pulse',
	'dragon-pulse',
	'heal-pulse',
	'terrain-pulse',
	'-pulse',
	'heal-pulse',
];

export const powderMoves = [
	' Powder',
	'Stun Spore',
	'Sleep Powder',
	'Spore',
	'Cotton Spore',
	'Rage Powder',
	'Powder',
	'Magic Powder',
];
export const danceMoves = [
	'aqua-step',
	'clangorous-soul',
	'dragon-dance',
	'feather-dance',
	'fiery-dance',
	'lunar-dance',
	'petal-dance',
	'revelation-dance',
	'quiver-dance',
	'swords-dance',
	'teeter-dance',
	'victory-dance',
];

export const windMoves = [
	'aeroblast',
	'air-cutter',
	'bleakwind-storm',
	'blizzard',
	'fairy-wind',
	'gust',
	'heat-wave',
	'hurricane',
	'icy-wind',
	'petal-blizzard',
	'sandsear-storm',
	'sandstorm',
	'springtide-storm',
	'tailwind',
	'twister',
	'whirlwind',
	'wildbolt-storm',
];

export const slicingMoves = [
	'cut',
	'razor-leaf',
	'slash',
	'fury-cutter',
	'air-cutter',
	'aerial-ace',
	'leaf-blade',
	'night-slash',
	'air-slash',
	'x-scissor',
	'psycho-cut',
	'cross-poison',
	'sacred-sword',
	'razor-shell',
	'secret-sword',
	'solar-blade',
	'behemoth-blade',
	'stone-axe',
	'ceaseless-edge',
	'kowtow-cleave',
	'psyblade',
	'bitter-blade',
	'aqua-cutter',
	'mighty-cleave',
	'tachyon-cutter',
];
