export const punchBasedMoves = [
	'bullet-punch',
	'comet-punch',
	'dizzy-punch',
	'double-iron-bash',
	'drain-punch',
	'dynamic-punch',
	'fire-punch',
	'focus-punch',
	'hammer-arm',
	'headlong-rush',
	'ice-hammer',
	'ice-punch',
	'jet-punch',
	'mach-punch',
	'mega-punch',
	'meteor-mash',
	'plasma-fists',
	'power-up-punch',
	'rage-fist',
	'shadow-punch',
	'sky-uppercut',
	'surging-strikes',
	'thunder-punch',
	'wicked-blow',
];

export const ballAndBombMoves = [
	'Egg Bomb',
	'Barrage',
	'Sludge Bomb',
	'Octazooka',
	'Zap Cannon',
	'Shadow Ball',
	'Mist Ball',
	'Ice Ball',
	'Weather Ball',
	'Bullet Seed',
	'Rock Blast',
	'Gyro Ball',
	'Aura Sphere',
	'Seed Bomb',
	'Focus Blast',
	'Energy Ball',
	'Mud Bomb',
	'Rock Wrecker',
	'Magnet Bomb',
	'Electro Ball',
	'Acid Spray',
	'Searing Shot',
	'Pollen Puff',
	'Beak Blast',
	'Pyro Ball',
	'Syrup Bomb',
];
