import { PokemonName } from './pokemonNames';

export const swarmMons: PokemonName[] = [
	'cyndaquil',
	'chikorita',
	'totodile',
	'mudkip',
	'treecko',
	'torchic',
	'chimchar',
	'piplup',
	'turtwig',
	'snivy',
	'tepig',
	'oshawott',
	'chespin',
	'fennekin',
	'froakie',
	'popplio',
	'rowlet',
	'litten',
	'grookey',
	'scorbunny',
	'sobble',
	'fuecoco',
	'quaxly',
	'sprigatito',
];
export const strongerSwarmMons: PokemonName[] = [
	'donphan',
	'wigglytuff',
	'amoonguss',
	'misdreavus',
	'volcarona',
	'magneton',
	'shelgon',
	'cyclizar',
	'delibird',
	'hariyama',
	'zweilous',
	'pupitar',
	'kirlia',
];
export const pastDistortionMons: PokemonName[] = [
	'great-tusk',
	'scream-tail',
	'flutter-mane',
	'brute-bonnet',
	'slither-wing',
	'sandy-shocks',
	'roaring-moon',
];
export const futureDistortionMons: PokemonName[] = [
	'iron-treads',
	'iron-bundle',
	'iron-hands',
	'iron-jugulis',
	'iron-moth',
	'iron-thorns',
	'iron-valiant',
];
export const spaceDistortionMons: PokemonName[] = [
	'nihilego',
	'buzzwole',
	'pheromosa',
	'xurkitree',
	'celesteela',
	'kartana',
	'guzzlord',
	'poipole',
	'stakataka',
	'blacephalon',
];

export const rampageOptions: PokemonName[] = [
	'dragonite',
	'ursaring',
	'crobat',
	'arcanine',
	'garchomp',
	'tyranitar',
	'machamp',
	'alakazam',
	'slaking',
	'steelix',
	'primeape',
	'pinsir',
	'heracross',
	'gengar',
	'scolipede',
	'drapion',
	'kommo-o',
	'oranguru',
	'beartic',
	'pangoro',
];
