import { isBagOverloaded } from '../../../functions/getBagLimit';
import { getHistorianMessage } from '../../../functions/getHistorianMessage';
import { getRandomOrientation } from '../../../functions/getNextClockwiseDirection';
import { makeApricornTree } from '../../../functions/makeApricornTree';
import { zigzagoonForagers } from '../../../hooks/useZigzagoonForagers';
import { Occupant, OverworldMap } from '../../../interfaces/OverworldMap';
import { SpriteEnum } from '../../../interfaces/SpriteEnum';
import { amoongussCompostResearchers } from '../../../modules/AmoongussResearcher/AmoongussResearcher';
import { battleJournalist } from '../../../modules/BattleJournalist/BattleJournalist';
import { dragoniteTaxi } from '../../../modules/DragoniteTaxi/DragoniteTaxi';
import { miltankFarm } from '../../../modules/MiltankFarm/MiltankFarm';
import { seedvaultResearcher } from '../../../modules/SeedVault/SeedVault';
import { vileplumeResearchers } from '../../../modules/VilePlumeScentResearcher/VilePlumeScentResearcher';
import { internalDex } from '../../internalDexData';
import { bugsy, bugsysScyther } from './bugsy';
import { rewardChris } from './champChris';
import { chuckLine, chucksMachamp } from './chuckLine';
import { clairLine, clairsKingdra } from './clair';
import { evExpertLine } from './evExpert';
import { falknerLine, falknersHootHoot } from './falknerLine';
import { jasmineLine, jasminesAron } from './jasmine';
import { lookerLine } from './lookerLine';
import { mortyLine, mortysGengar } from './mortyLine';
import { pikachuFanLine } from './pikachuFanLine';
import { pryceLine, prycesMamoswine } from './pryce';
import { whitneyLine, whitneysClefairy } from './whitney';

const trainingField: Occupant[] = [
	{
		type: 'ROUTER_NPC',
		to: 'TRAINING_FIELD',
		x: 29,
		y: 23,
		orientation: 'LEFT',
		sprite: SpriteEnum.aceFemale,
		id: 'training_field_master',
		dialogue: [
			'Welcome to the training field',
			'Here you can challenge different trainers',
			'and improve your skills',
		],
		conditionFunction: (s) => s.campUpgrades['training field 1'],
	},
	{
		type: 'ROUTER_NPC',
		to: 'MOVE_TUTOR',
		x: 31,
		y: 21,
		orientation: 'DOWN',
		sprite: SpriteEnum.aceMale,
		id: 'move_tutor',
		dialogue: [
			'I can teach your Pokemon new moves',
			'But I expect some snacks as payment',
		],
		conditionFunction: (s) => s.campUpgrades['invite move tutor'],
	},
	{
		type: 'ROUTER_NPC',
		to: 'NATURE_TUTOR',
		x: 38,
		y: 24,
		orientation: 'LEFT',
		sprite: SpriteEnum.ace2Male,
		id: 'nature_tutor',
		dialogue: [
			'By giving your Pokemon certain berries',
			'we can change its nature',
		],
		conditionFunction: (s) => s.campUpgrades['invite nature tutor'],
	},
	{
		type: 'ROUTER_NPC',
		to: 'ABILITY_TUTOR',
		x: 38,
		y: 27,
		orientation: 'LEFT',
		sprite: SpriteEnum.ace2Female,
		id: 'ability_tutor',
		dialogue: [
			'I can change your Pokemons ability',
			'But I expect some snacks as payment',
		],
		conditionFunction: (s) => s.campUpgrades['invite ability tutor'],
	},
	battleJournalist,
];

export const campOccupants: OverworldMap['occupants'] = [
	{
		type: 'ON_STEP_PORTAL',
		x: 11,
		y: 25,
		portal: {
			mapId: 'campCave',
			x: 14,
			y: 7,
			orientation: 'UP',
			forwardFoot: 'CENTER1',
		},
		id: 'camp_to_campCave',
		conditionFunction: () => true,
	},
	{
		type: 'ON_STEP_PORTAL',
		x: 30,
		y: 13,
		portal: {
			mapId: 'campLaboratory',
			x: 10,
			y: 12,
			orientation: 'UP',
			forwardFoot: 'CENTER1',
		},
		id: 'camp_to_campLaboratory',
		conditionFunction: () => true,
	},
	{
		type: 'ON_STEP_PORTAL',
		x: 20,
		y: 0,
		portal: {
			mapId: 'routeN1',
			x: 25,
			y: 49,
			orientation: 'UP',
			forwardFoot: 'CENTER1',
		},
		id: 'camp_to_routeN1',
		conditionFunction: (s) => !isBagOverloaded(s),
	},
	{
		type: 'NPC',
		x: 20,
		y: 0,
		unhandledMessage: [
			'You cant go out carrying this much stuff',
			'Store some items in your chest',
		],
		id: 'bag_blocker_N1',
		sprite: SpriteEnum.scientistMale,
		orientation: 'DOWN',
		conditionFunction: (s) => isBagOverloaded(s),
	},
	{
		type: 'ON_STEP_PORTAL',
		x: 0,
		y: 30,
		portal: {
			mapId: 'routeW1',
			x: 49,
			y: 39,
			orientation: 'LEFT',
			forwardFoot: 'CENTER1',
		},
		id: 'camp_to_routeW1',
		conditionFunction: (s) => !isBagOverloaded(s),
	},
	{
		type: 'NPC',
		x: 0,
		y: 30,
		unhandledMessage: [
			'You cant go out carrying this much stuff',
			'Store some items in your chest',
		],
		id: 'bag_blocker_W1',
		sprite: SpriteEnum.scientistMale,
		orientation: 'RIGHT',
		conditionFunction: (s) => isBagOverloaded(s),
	},
	{
		type: 'ON_STEP_PORTAL',
		x: 20,
		y: 39,
		portal: {
			mapId: 'routeS1',
			x: 25,
			y: 1,
			orientation: 'DOWN',
			forwardFoot: 'CENTER1',
		},
		id: 'camp_to_routeS1',
		conditionFunction: (s) => !isBagOverloaded(s),
	},
	{
		type: 'ON_STEP_PORTAL',
		x: 39,
		y: 20,
		portal: {
			mapId: 'routeE1',
			x: 1,
			y: 25,
			orientation: 'RIGHT',
			forwardFoot: 'CENTER1',
		},
		id: 'camp_to_routeE1',
		conditionFunction: (s) => !isBagOverloaded(s),
	},
	{
		type: 'NPC',
		x: 39,
		y: 20,
		unhandledMessage: [
			'You cant go out carrying this much stuff',
			'Store some items in your chest',
		],
		id: 'bag_blocker_E1',
		sprite: SpriteEnum.scientistFemale,
		orientation: 'LEFT',
		conditionFunction: (s) => isBagOverloaded(s),
	},
	{
		type: 'SIGN',
		x: 21,
		y: 1,
		dialogue: [`Akai Route, beware of wild pokemon`],
		approachDirection: 'UP',
		id: 'routeN1Sign',
		conditionFunction: () => true,
	},
	{
		type: 'PC',
		x: 19,
		y: 15,

		id: 'camp_pc',
		conditionFunction: () => true,
	},
	{
		type: 'STORAGE_CHEST',
		x: 20,
		y: 15,
		id: 'camp_storage',
		conditionFunction: () => true,
	},
	{
		type: 'BULLETIN_BOARD',
		id: 'camp_bulletin_board',
		x: 21,
		y: 15,
		approachDirection: 'UP',
		dialogue: ['Looking for new Quests ...'],
		conditionFunction: (s) => s.campUpgrades.bulletin_board,
	},
	{
		type: 'NURSE',
		id: 'camp_nurse',
		x: 17,
		y: 18,
		orientation: 'DOWN',
		sprite: SpriteEnum.nurse,
		dialogue: ['Lets heal your Pokemon'],
		conditionFunction: () => true,
	},
	{
		type: 'POKEMON',
		id: 'camp_nurse_blissey',
		x: 18,
		y: 18,
		orientation: 'DOWN',
		dexId: 242,
		dialogue: ['Blissey is assisting Nurse Joy'],
		conditionFunction: () => true,
	},
	{
		type: 'ROUTER_NPC',
		to: 'CAMP_UPGRADES',
		id: 'camp_manager',
		x: 22,
		y: 18,
		orientation: 'DOWN',
		dialogue: ['How should we expand our camp?'],
		sprite: SpriteEnum.butler,
		conditionFunction: () => true,
	},
	{
		type: 'SWARM_RADAR',
		y: 16,
		x: 17,
		conditionFunction: (s) => s.campUpgrades['pokemon swarm radar'],
		id: 'swarm radar',
	},
	{
		type: 'ROCKET_RADIO',
		y: 15,
		x: 17,
		conditionFunction: (s) => s.campUpgrades['ranger certification'],
		id: 'rocket radio',
	},
	{
		type: 'ROUTER_NPC',
		to: 'FARM',
		id: 'berry_farmer',
		x: 7,
		y: 18,
		orientation: 'RIGHT',
		dialogue: ['We can grow all types of berries and apricorns'],
		sprite: SpriteEnum.farmer,
		conditionFunction: (s) => s.campUpgrades.berry_farm,
	},
	{
		type: 'COMBEE_HIVE',
		x: 8,
		y: 2,
		id: 'combee_hive',
		conditionFunction: (s) => s.campUpgrades['build combee hive'],
	},
	{
		type: 'POKEMON',
		x: 9,
		y: 3,
		id: 'combee-1',
		orientation: getRandomOrientation(),
		conditionFunction: (s) => s.campUpgrades['build combee hive'],
		dexId: internalDex.combee.dexId,
		dialogue: ['bzzz'],
	},
	{
		type: 'POKEMON',
		x: 7,
		y: 2,
		id: 'combee-2',
		orientation: getRandomOrientation(),
		conditionFunction: (s) => s.campUpgrades['build combee hive'],
		dexId: internalDex.combee.dexId,
		dialogue: ['bzzzzz'],
	},
	{
		type: 'ROUTER_NPC',
		to: 'APRICORN_SMITHY',
		sprite: SpriteEnum.kurt,
		x: 37,
		y: 5,
		orientation: 'LEFT',
		id: 'campUpgrade_kurt',
		dialogue: [
			'My name is kurt',
			'I practice the ancient art',
			'of turning apricorns into pokeballs',
			'Each type of ball has a different specialty',
		],
		conditionFunction: (s) => s.campUpgrades['invite apricorn smith kurt'],
	},
	{
		type: 'ROUTER_NPC',
		to: 'CHEF_GRANDMA',
		orientation: 'DOWN',
		y: 2,
		x: 31,
		dialogue: [
			'Some Berries are not very useful raw',
			'but they are still good ingredients',
		],
		sprite: SpriteEnum.grandma,
		conditionFunction: (s) => s.campUpgrades['invite chef grandma'],
		id: 'chef grandma',
	},
	...makeApricornTree({
		x: 38,
		y: 4,
		apricorn: 'grey-apricorn',
		id: 'farm_grey_tree_1',
	}),
	...makeApricornTree({
		x: 38,
		y: 6,
		apricorn: 'grey-apricorn',
		id: 'farm_grey_tree_2',
	}),
	...makeApricornTree({
		x: 37,
		y: 3,
		apricorn: 'grey-apricorn',
		id: 'farm_grey_tree_3',
	}),
	...makeApricornTree({
		x: 37,
		y: 7,
		apricorn: 'grey-apricorn',
		id: 'farm_grey_tree_4',
	}),
	...makeApricornTree({
		x: 1,
		y: 15,
		apricorn: 'green-apricorn',
		id: 'farm_green_tree_1',
	}),
	...makeApricornTree({
		x: 1,
		y: 16,
		apricorn: 'green-apricorn',
		id: 'farm_green_tree_2',
	}),
	...makeApricornTree({
		x: 1,
		y: 17,
		apricorn: 'green-apricorn',
		id: 'farm_green_tree_3',
	}),
	...makeApricornTree({
		x: 1,
		y: 19,
		apricorn: 'black-apricorn',
		id: 'farm_black_tree_1',
	}),
	...makeApricornTree({
		x: 1,
		y: 20,
		apricorn: 'black-apricorn',
		id: 'farm_black_tree_2',
	}),
	...makeApricornTree({
		x: 1,
		y: 21,
		apricorn: 'black-apricorn',
		id: 'farm_black_tree_3',
	}),
	...makeApricornTree({
		x: 16,
		y: 34,
		apricorn: 'blue-apricorn',
		id: 'farm_blue_tree_1',
	}),
	...makeApricornTree({
		x: 14,
		y: 35,
		apricorn: 'blue-apricorn',
		id: 'farm_blue_tree_2',
	}),
	...makeApricornTree({
		x: 2,
		y: 0,
		apricorn: 'yellow-apricorn',
		id: 'farm_yellow_tree_1',
	}),
	...makeApricornTree({
		x: 0,
		y: 1,
		apricorn: 'yellow-apricorn',
		id: 'farm_yellow_tree_2',
	}),
	{
		type: 'CLIMBING_STEPS',
		x: 2,
		y: 2,
		conditionFunction: () => true,
		id: 'climbing-steps-camp',
	},
	{
		type: 'CLIMBING_STEPS',
		x: 2,
		y: 3,
		conditionFunction: () => true,
		id: 'climbing-steps-camp',
	},

	...miltankFarm,
	...zigzagoonForagers,
	...vileplumeResearchers,
	...amoongussCompostResearchers,
	...seedvaultResearcher,
	...dragoniteTaxi,
	...trainingField,
	...falknerLine,
	falknersHootHoot,
	...chuckLine,
	chucksMachamp,
	...mortyLine,
	mortysGengar,
	...evExpertLine,
	bugsy,
	bugsysScyther,
	rewardChris,
	...lookerLine,
	...jasmineLine,
	jasminesAron,
	...whitneyLine,
	whitneysClefairy,
	...pikachuFanLine,
	...clairLine,
	clairsKingdra,
	...pryceLine,
	prycesMamoswine,
	{
		type: 'ROUTER_NPC',
		to: 'CURATOR',
		orientation: 'UP',
		x: 18,
		y: 21,
		dialogue: [
			'I am from the pewter city museum',
			'i heard you discovered some items',
			'that might be worth displaying',
		],
		sprite: SpriteEnum.gentleman,
		conditionFunction: (s) => s.campUpgrades['invite museum curator'],
		id: 'curator',
	},
	{
		type: 'NPC',
		orientation: 'UP',
		x: 19,
		y: 21,
		handledMessage: getHistorianMessage(),
		unhandledMessage: getHistorianMessage(),
		sprite: SpriteEnum.grandFather3,
		conditionFunction: (s) => s.campUpgrades['invite historian'],
		id: 'historian',
	},
];
