import { occupantHandled } from '../../../functions/occupantHandled';
import { OverworldMap } from '../../../interfaces/OverworldMap';
import { SpriteEnum } from '../../../interfaces/SpriteEnum';
import { bruno } from './bruno';
import { karen } from './karen';
import { koga } from './koga';
import { lance } from './lance';
import { will } from './will';

export const pokemonLeagueOccupants: OverworldMap['occupants'] = [
	{
		id: 'pokemonLeague_to_victoryRoad',
		type: 'ON_STEP_PORTAL',
		x: 5,
		y: 56,
		portal: {
			mapId: 'victoryRoad',
			x: 4,
			y: 5,
			orientation: 'DOWN',
			forwardFoot: 'CENTER1',
		},
		sprite: '/mapObjects/ladderDown.png',
		conditionFunction: () => true,
	},
	{
		type: 'NURSE',
		id: 'camp_nurse',
		x: 2,
		y: 52,
		orientation: 'DOWN',
		sprite: SpriteEnum.nurse,
		dialogue: ['Lets heal your Pokemon'],
		conditionFunction: () => true,
	},
	{
		type: 'POKEMON',
		id: 'camp_nurse_blissey',
		x: 1,
		y: 52,
		orientation: 'DOWN',
		dexId: 242,
		dialogue: ['Blissey is assisting Nurse Joy'],
		conditionFunction: () => true,
	},
	{
		type: 'PC',
		x: 8,
		y: 52,

		id: 'camp_pc',
		conditionFunction: () => true,
	},
	{
		type: 'STORAGE_CHEST',
		x: 7,
		y: 52,
		id: 'camp_storage',
		conditionFunction: () => true,
	},
	{
		type: 'NPC',
		x: 5,
		y: 51,
		orientation: 'UP',
		sprite: SpriteEnum.doormanGreen,
		id: 'elite-four-doorman-active',
		unhandledMessage: ['You have to defeat all 5 trainers in one go'],
		conditionFunction: (s) => occupantHandled(s, 'elite-four-will'),
	},
	{
		type: 'NPC',
		x: 4,
		y: 52,
		orientation: 'DOWN',
		sprite: SpriteEnum.doormanGreen,
		id: 'elite-four-doorman-inactive',
		unhandledMessage: [
			'You have to defeat all 5 trainers in one go',
			'So choose your team and items wisely',
		],
		conditionFunction: (s) => !occupantHandled(s, 'elite-four-will'),
	},
	will,
	{
		type: 'POKEMON',
		dexId: 178,
		x: 6,
		y: 42,
		orientation: 'DOWN',
		id: 'wills-xatu',
		dialogue: ['xat', 'xatu'],
		conditionFunction: (s) => !occupantHandled(s, 'elite4-will'),
	},
	koga,
	{
		type: 'POKEMON',
		dexId: 169,
		x: 4,
		y: 32,
		orientation: 'DOWN',
		id: 'kogas-crobat',
		dialogue: ['hssss'],
		conditionFunction: (s) => !occupantHandled(s, 'elite4-koga'),
	},
	bruno,
	{
		type: 'POKEMON',
		dexId: 68,
		x: 6,
		y: 22,
		orientation: 'DOWN',
		id: 'brunos-machamp',
		dialogue: ['champ champ'],
		conditionFunction: (s) => !occupantHandled(s, 'elite4-bruno'),
	},
	karen,
	{
		type: 'POKEMON',
		dexId: 359,
		x: 4,
		y: 12,
		orientation: 'DOWN',
		id: 'karens-absol',
		dialogue: ['grrrr'],
		conditionFunction: (s) => !occupantHandled(s, 'elite4-karen'),
	},
	lance,
	{
		type: 'POKEMON',
		dexId: 149,
		x: 6,
		y: 3,
		orientation: 'DOWN',
		id: 'lances-dragonite',
		dialogue: ['dragoooo'],
		conditionFunction: (s) => !occupantHandled(s, 'elite4-champ-lance'),
	},
	{
		type: 'TELEPORTER_NPC',
		sprite: SpriteEnum.oak,
		dialogue: [
			'Congratulations, Champ',
			'You have progressed so much',
			'since we started exploring the kuma region',
			'But there is still more to do',
			'lets head back to the lab',
		],
		to: {
			mapId: 'campLaboratory',
			x: 10,
			y: 4,
			orientation: 'UP',
			forwardFoot: 'CENTER1',
		},
		x: 7,
		y: 4,
		id: 'congrats-oak',
		orientation: 'LEFT',
		conditionFunction: (s) => occupantHandled(s, 'elite4-champ-lance'),
	},
];
