import { OverworldMap } from '../../../interfaces/OverworldMap';
import { SpriteEnum } from '../../../interfaces/SpriteEnum';
import { gary } from './gary';

export const routeW1Occupants: OverworldMap['occupants'] = [
	{
		type: 'ON_STEP_PORTAL',
		x: 25,
		y: 0,
		portal: {
			mapId: 'routeN1W1',
			x: 25,
			y: 49,
			orientation: 'UP',
			forwardFoot: 'CENTER1',
		},
		conditionFunction: () => true,
		id: 'routeW1_to_routeN1W1',
	},
	{
		type: 'NPC',
		x: 25,
		y: 1,
		orientation: 'DOWN',
		unhandledMessage: [
			'Not so fast, big dog',
			'Cant let anyone through without proper equipment',
			"Shit's gnarly up there, brother",
		],
		sprite: SpriteEnum.snowboarder,
		conditionFunction: (s) => !s.campUpgrades['buy skiing equipment'],
		id: 'ski-blocker',
	},
	{
		type: 'ON_STEP_PORTAL',
		x: 25,
		y: 50,
		portal: {
			mapId: 'routeS1W1',
			y: 1,
			x: 25,
			orientation: 'DOWN',
			forwardFoot: 'CENTER1',
		},
		conditionFunction: () => true,
		id: 'routeN1W1_to_routeS1W1',
	},
	{
		type: 'ON_STEP_PORTAL',
		x: 50,
		y: 25,
		portal: {
			mapId: 'camp',
			y: 10,
			x: 1,
			orientation: 'RIGHT',
			forwardFoot: 'CENTER1',
		},
		conditionFunction: () => true,
		id: 'routeW1_camp',
	},
	{
		type: 'STRANGE_TREE',
		x: 48,
		y: 25,
		conditionFunction: () => true,
		id: 'sudowoodo',
		orientation: 'UP',
	},
	{
		type: 'ON_STEP_PORTAL',
		id: 'cave entry bottom',
		conditionFunction: () => true,
		x: 28,
		y: 47,
		portal: {
			mapId: 'caveW1',
			x: 29,
			y: 47,
			orientation: 'DOWN',
			forwardFoot: 'CENTER1',
		},
		sprite: '/mapObjects/ladderDown.png',
	},
	{
		type: 'ON_STEP_PORTAL',
		id: 'cave entry middle',
		conditionFunction: () => true,
		x: 6,
		y: 17,
		portal: {
			mapId: 'caveW1',
			x: 7,
			y: 17,
			orientation: 'DOWN',
			forwardFoot: 'CENTER1',
		},
		sprite: '/mapObjects/ladderDown.png',
	},
	{
		type: 'ON_STEP_PORTAL',
		id: 'cave entry top',
		conditionFunction: () => true,
		x: 23,
		y: 2,
		portal: {
			mapId: 'caveW1',
			x: 24,
			y: 2,
			orientation: 'DOWN',
			forwardFoot: 'CENTER1',
		},
		sprite: '/mapObjects/ladderDown.png',
	},
	{
		type: 'ITEM',
		x: 12,
		y: 19,
		item: 'plume-fossil',
		amount: 1,
		conditionFunction: (s) =>
			!s.handledOccupants.some((h) => h.id === 'routeW1-plume-fossil'),
		id: 'routeW1-plume-fossil',
	},
	{
		type: 'ITEM',
		x: 23,
		y: 47,
		item: 'escape-rope',
		amount: 5,
		conditionFunction: (s) =>
			!s.handledOccupants.some((h) => h.id === 'routeW1-escape-ropes'),
		id: 'routeW1-escape-ropes',
	},
	...gary,
];
