import { makeOverworldItem } from '../../../functions/makeOverworldItem';
import { occupantHandled } from '../../../functions/occupantHandled';
import { OverworldMap } from '../../../interfaces/OverworldMap';

export const victoryRoadOccupants: OverworldMap['occupants'] = [
	{
		id: 'victory_road_to_routeN1',
		type: 'ON_STEP_PORTAL',
		x: 15,
		y: 50,
		portal: {
			mapId: 'routeN1',
			x: 15,
			y: 1,
			orientation: 'DOWN',
			forwardFoot: 'CENTER1',
		},
		conditionFunction: () => true,
	},
	{
		type: 'CLIMBING_STEPS',
		x: 7,
		y: 9,
		conditionFunction: () => true,
		id: 'climbing-steps-victoryRoad-1',
	},
	{
		type: 'CLIMBING_STEPS',
		x: 7,
		y: 10,
		conditionFunction: () => true,
		id: 'climbing-steps-victoryRoad-2',
	},
	{
		type: 'CLIMBING_STEPS',
		x: 7,
		y: 11,
		conditionFunction: () => true,
		id: 'climbing-steps-victoryRoad-3',
	},
	{
		type: 'LEDGE',
		x: 1,
		y: 29,
		conditionFunction: (s) =>
			!s.handledOccupants.some((occ) => occ.id === 'ledge-victoryRoad-1'),
		id: 'ledge-victoryRoad-1',
		sprite: '/ledges/ledgeDown.png',
		passableFrom: 'UP',
	},
	{
		type: 'LEDGE',
		x: 2,
		y: 29,
		conditionFunction: (s) =>
			!s.handledOccupants.some((occ) => occ.id === 'ledge-victoryRoad-2'),
		id: 'ledge-victoryRoad-2',
		sprite: '/ledges/ledgeDown.png',
		passableFrom: 'UP',
	},
	{
		type: 'LEDGE',
		x: 3,
		y: 29,
		conditionFunction: (s) =>
			!s.handledOccupants.some((occ) => occ.id === 'ledge-victoryRoad-3'),
		id: 'ledge-victoryRoad-3',
		sprite: '/ledges/ledgeDown.png',
		passableFrom: 'UP',
	},
	{
		type: 'ROCK',
		x: 20,
		y: 45,
		conditionFunction: (s) =>
			!s.handledOccupants.some((occ) => occ.id === 'rock_victory_road_1'),
		id: 'rock_victory_road_1',
	},
	{
		type: 'ROCK',
		x: 21,
		y: 44,
		conditionFunction: (s) =>
			!s.handledOccupants.some((occ) => occ.id === 'rock_victory_road_2'),
		id: 'rock_victory_road_2',
	},
	{
		type: 'ROCK',
		x: 19,
		y: 46,
		conditionFunction: (s) =>
			!s.handledOccupants.some((occ) => occ.id === 'rock_victory_road_3'),
		id: 'rock_victory_road_3',
	},
	{
		type: 'POKEMON',
		x: 4,
		y: 49,
		orientation: 'UP',
		dexId: 248,
		encounter: {
			name: 'tyranitar',
			maxXp: 343000,
			minXp: 343000,
			rarity: 'common',
		},
		dialogue: ['Taaarr'],
		conditionFunction: (s) => !occupantHandled(s, 'victory-road_ttar'),
		id: 'victory-road_ttar',
	},
	{
		type: 'POKEMON',
		x: 4,
		y: 48,
		orientation: 'DOWN',
		dexId: 452,
		encounter: {
			name: 'drapion',
			maxXp: 343000,
			minXp: 343000,
			rarity: 'common',
		},
		dialogue: ['Drap Drap'],
		conditionFunction: (s) => !occupantHandled(s, 'victory-road_drapion'),
		id: 'victory-road_drapion',
	},
	makeOverworldItem({
		mapId: 'victoryRoad',
		item: 'full-restore',
		x: 20,
		y: 28,
		amount: 2,
	}),
	makeOverworldItem({
		mapId: 'victoryRoad',
		item: 'ultra-ball',
		x: 10,
		y: 41,
		amount: 5,
	}),
	makeOverworldItem({
		mapId: 'victoryRoad',
		item: 'max-ether',
		x: 43,
		y: 35,
		amount: 1,
	}),
	makeOverworldItem({
		mapId: 'victoryRoad',
		item: 'lum-berry',
		x: 25,
		y: 25,
		amount: 1,
	}),
	makeOverworldItem({
		mapId: 'victoryRoad',
		item: 'loaded-dice',
		x: 45,
		y: 9,
		amount: 1,
	}),
	makeOverworldItem({
		mapId: 'victoryRoad',
		item: 'max-potion',
		x: 17,
		y: 19,
		amount: 3,
	}),
	makeOverworldItem({
		mapId: 'victoryRoad',
		item: 'leftovers',
		x: 20,
		y: 13,
		amount: 1,
	}),
	makeOverworldItem({
		mapId: 'victoryRoad',
		item: 'choice-band',
		x: 11,
		y: 5,
		amount: 1,
	}),
];
