import { defaultShaderMap } from '../../functions/getTimeOfDay';
import { OverworldMap } from '../../interfaces/OverworldMap';
import { campOccupants } from './occupants/camp';

export const camp: OverworldMap = {
	id: 'camp',
	timeOfDayShadersMap: defaultShaderMap,
	possibleEncounters: {
		BASE: [],
		MORNING: [],
		DAY: [],
		EVENING: [],
		NIGHT: [],
	},
	tileMap: {
		baseLayer: [
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -272, xOffset: -512 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -288, xOffset: -512 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -304, xOffset: -512 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -272, xOffset: -512 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -288, xOffset: -512 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -304, xOffset: -512 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -272, xOffset: -512 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -288, xOffset: -512 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -304, xOffset: -512 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -272, xOffset: -512 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -288, xOffset: -512 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -304, xOffset: -512 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
		],
		encounterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		obstacleLayer: [
			[
				{ yOffset: -256, xOffset: -1024 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				null,
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -256, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -352, xOffset: -1040 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -368, xOffset: -1040 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -256, xOffset: -1024 },
				{ yOffset: -288, xOffset: -1040 },
				null,
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -256, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -288, xOffset: -1024 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1024 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1056 },
			],
		],
		decorationLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		foregroundLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
	},

	occupants: campOccupants,
};
