import { OverworldMap } from '../../interfaces/OverworldMap';
import { SpriteEnum } from '../../interfaces/SpriteEnum';

const occs: OverworldMap['occupants'] = [
	{
		type: 'NPC',
		id: 'oak_1',
		x: 5,
		y: 4,
		orientation: 'DOWN',
		unhandledMessage: [
			'Ah, you made it',
			'Outside of the fence, the wild Kuma Region awaits',
			'If your Pokemon are hurt, talk to nurse joy on my right',
			'For camp related issues, Camp Manager Kevin can help you',
			'I have a first request for you and some equipment to get you started',
		],
		handledMessage: ['Be careful outside the fence'],
		gifts: { 'poke-ball': 10 },
		quest: 'catch a pokemon',
		sprite: SpriteEnum.oak,
		conditionFunction: (s) => s.quests['catch a pokemon'] !== 'FULFILLED',
	},
	{
		type: 'NURSE',
		id: 'camp_nurse',
		x: 6,
		y: 4,
		orientation: 'DOWN',
		sprite: SpriteEnum.nurse,
		dialogue: ['Lets heal your Pokemon'],
		conditionFunction: () => true,
	},
	{
		type: 'CAMP_MANAGER',
		id: 'camp_manager',
		x: 4,
		y: 4,
		orientation: 'DOWN',
		dialogue: ['How should we expand our camp?'],
		sprite: SpriteEnum.butler,
		conditionFunction: () => true,
	},
	{
		type: 'ON_STEP_PORTAL',
		x: 10,
		y: 0,
		portal: {
			mapId: 'routeN1',
			x: 25,
			y: 49,
			orientation: 'UP',
			forwardFoot: 'CENTER1',
		},
		id: 'camp_to_routeN1',
		conditionFunction: () => true,
	},
];

export const camp: OverworldMap = {
	id: 'camp',
	possibleEncounters: {
		MORNING: [
			{ dexId: 25, xp: 125 },
			{ dexId: 324, xp: 44 },
		],
		DAY: [{ dexId: 25, xp: 125 }],
		EVENING: [{ dexId: 25, xp: 125 }],
		NIGHT: [
			{ dexId: 167, xp: 125 },
			{ dexId: 25, xp: 125 },
		],
	},
	tileMap: {
		baseLayer: [
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -272, xOffset: -512 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -528 },
				{ yOffset: -272, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -288, xOffset: -512 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -288, xOffset: -512 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -288, xOffset: -512 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -528 },
				{ yOffset: -288, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: -304, xOffset: -512 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -528 },
				{ yOffset: -304, xOffset: -544 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
			[
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
				{ yOffset: 0, xOffset: -720 },
			],
		],
		encounterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		obstacleLayer: [
			[
				{ yOffset: -256, xOffset: -1024 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				null,
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -256, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -272, xOffset: -1024 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -1056 },
			],
			[
				{ yOffset: -288, xOffset: -1024 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1040 },
				{ yOffset: -288, xOffset: -1056 },
			],
		],
		decorationLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		foregroundLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
	},

	occupants: occs,
};
