import { defaultShaderMap } from "../../functions/getTimeOfDay";
import { OverworldMap } from "../../interfaces/OverworldMap";
import { campOccupants } from "./occupants/campFarm";

export const campFarm: OverworldMap = {
  area: "OPEN",
  id: "campFarm",
  tilesetUrl: "/tilesets/newMasterSheet.png",
  occupants: campOccupants,
  timeOfDayShadersMap: defaultShaderMap,
  tileMap: {
    baseLayer: [
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
    ],
    encounterLayer: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    obstacleLayer: [
      [
        { yOffset: -256, xOffset: -144 },
        { yOffset: -144, xOffset: -16 },
        { yOffset: -144, xOffset: -16 },
        { yOffset: -144, xOffset: -16 },
        { yOffset: -144, xOffset: -16 },
        { yOffset: -144, xOffset: -16 },
        { yOffset: -144, xOffset: -16 },
        { yOffset: -144, xOffset: -16 },
        { yOffset: -144, xOffset: -16 },
        { yOffset: -144, xOffset: -16 },
        { yOffset: -144, xOffset: -16 },
        { yOffset: -144, xOffset: -16 },
        { yOffset: -256, xOffset: -176 },
        { yOffset: -304, xOffset: -160 },
        { yOffset: -304, xOffset: -160 },
        { yOffset: -304, xOffset: -160 },
        { yOffset: -304, xOffset: -160 },
        { yOffset: -304, xOffset: -160 },
        { yOffset: -304, xOffset: -160 },
        { yOffset: -256, xOffset: -192 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -176 },
        null,
        { yOffset: -144, xOffset: -16 },
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -192 },
      ],
      [
        { yOffset: -304, xOffset: -192 },
        null,
        null,
        null,
        { yOffset: -128, xOffset: -32 },
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: -32 },
        { yOffset: -272, xOffset: -224 },
        null,
        null,
        null,
        null,
        null,
        { yOffset: -144, xOffset: -16 },
        { yOffset: -272, xOffset: -192 },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -192 },
      ],
      [
        { yOffset: -304, xOffset: -176 },
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: -32 },
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -256, xOffset: -224 },
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -192 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        { yOffset: -128, xOffset: -32 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: -32 },
        null,
        null,
        { yOffset: -288, xOffset: -176 },
        { yOffset: -304, xOffset: -160 },
        { yOffset: -304, xOffset: -160 },
        { yOffset: -304, xOffset: -160 },
        { yOffset: -304, xOffset: -160 },
        { yOffset: -304, xOffset: -160 },
        { yOffset: -304, xOffset: -160 },
        { yOffset: -288, xOffset: -192 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -144, xOffset: -16 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -256, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -256, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -304, xOffset: -192 },
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        { yOffset: -128, xOffset: -32 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        { yOffset: -288, xOffset: -208 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -304, xOffset: -176 },
        null,
        { yOffset: -144, xOffset: -16 },
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        { yOffset: -288, xOffset: -224 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -288, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -288, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -240 },
        { yOffset: -128, xOffset: -16 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: -16 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: -16 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: -16 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: -16 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: -16 },
      ],
      [
        { yOffset: -288, xOffset: -144 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
        { yOffset: -128, xOffset: -16 },
      ],
    ],
    decorationLayer: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { yOffset: -112, xOffset: -32 },
        null,
        { yOffset: -64, xOffset: 0 },
        { yOffset: -112, xOffset: -32 },
        { yOffset: -112, xOffset: 0 },
        { yOffset: -64, xOffset: 0 },
        { yOffset: -112, xOffset: -16 },
        { yOffset: -48, xOffset: 0 },
        { yOffset: -112, xOffset: -32 },
        null,
        { yOffset: -32, xOffset: -144 },
        null,
        null,
        null,
        { yOffset: -32, xOffset: -144 },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { yOffset: -112, xOffset: -16 },
        { yOffset: -48, xOffset: 0 },
        { yOffset: -112, xOffset: -32 },
        null,
        { yOffset: -112, xOffset: -32 },
        { yOffset: -112, xOffset: 0 },
        null,
        null,
        { yOffset: -48, xOffset: 0 },
        null,
        null,
        { yOffset: -32, xOffset: -144 },
        { yOffset: -48, xOffset: 0 },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { yOffset: -112, xOffset: -16 },
        { yOffset: -112, xOffset: -48 },
        { yOffset: -112, xOffset: -48 },
        { yOffset: -112, xOffset: -16 },
        { yOffset: -112, xOffset: -48 },
        { yOffset: -64, xOffset: 0 },
        null,
        null,
        null,
        { yOffset: -32, xOffset: -144 },
        { yOffset: -48, xOffset: 0 },
        null,
        null,
        { yOffset: -32, xOffset: -144 },
        null,
      ],
      [
        null,
        null,
        { yOffset: -112, xOffset: -16 },
        null,
        null,
        null,
        { yOffset: -64, xOffset: 0 },
        { yOffset: -112, xOffset: 0 },
        { yOffset: -48, xOffset: 0 },
        { yOffset: -112, xOffset: -16 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -32, xOffset: -144 },
        { yOffset: -48, xOffset: 0 },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -112, xOffset: -16 },
        null,
        null,
        null,
        null,
        { yOffset: -112, xOffset: -32 },
        null,
        { yOffset: -112, xOffset: -16 },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { yOffset: -64, xOffset: 0 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { yOffset: -112, xOffset: -32 },
        null,
        null,
        null,
        null,
        { yOffset: -112, xOffset: -16 },
        null,
        null,
        null,
        { yOffset: -48, xOffset: 0 },
        { yOffset: -32, xOffset: -144 },
        null,
        null,
        { yOffset: -48, xOffset: 0 },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -48, xOffset: 0 },
        null,
        null,
        { yOffset: -32, xOffset: -144 },
        { yOffset: -48, xOffset: 0 },
        { yOffset: -32, xOffset: -144 },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -112, xOffset: -48 },
        null,
        null,
        { yOffset: -112, xOffset: 0 },
        null,
        null,
        null,
        { yOffset: -32, xOffset: -144 },
        null,
        { yOffset: -48, xOffset: 0 },
        null,
        null,
        { yOffset: -32, xOffset: -144 },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -112, xOffset: -16 },
        null,
        null,
        null,
        null,
        null,
        { yOffset: -32, xOffset: -144 },
        null,
        null,
        { yOffset: -32, xOffset: -144 },
        { yOffset: -48, xOffset: 0 },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { yOffset: -112, xOffset: -32 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { yOffset: -112, xOffset: -16 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -112, xOffset: -48 },
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { yOffset: -256, xOffset: -96 },
        { yOffset: -256, xOffset: -128 },
        null,
        { yOffset: -256, xOffset: -96 },
        { yOffset: -256, xOffset: -128 },
        null,
        { yOffset: -256, xOffset: -96 },
        { yOffset: -256, xOffset: -128 },
        { yOffset: -112, xOffset: 0 },
        null,
        { yOffset: -256, xOffset: -96 },
        { yOffset: -256, xOffset: -128 },
        null,
        { yOffset: -256, xOffset: -96 },
        { yOffset: -256, xOffset: -128 },
        null,
        { yOffset: -256, xOffset: -96 },
        { yOffset: -256, xOffset: -128 },
        null,
      ],
      [
        null,
        { yOffset: -272, xOffset: -96 },
        { yOffset: -272, xOffset: -128 },
        null,
        { yOffset: -272, xOffset: -96 },
        { yOffset: -272, xOffset: -128 },
        null,
        { yOffset: -272, xOffset: -96 },
        { yOffset: -272, xOffset: -128 },
        null,
        null,
        { yOffset: -272, xOffset: -96 },
        { yOffset: -272, xOffset: -128 },
        null,
        { yOffset: -272, xOffset: -96 },
        { yOffset: -272, xOffset: -128 },
        null,
        { yOffset: -272, xOffset: -96 },
        { yOffset: -272, xOffset: -128 },
        null,
      ],
      [
        null,
        { yOffset: -272, xOffset: -96 },
        { yOffset: -272, xOffset: -128 },
        null,
        { yOffset: -272, xOffset: -96 },
        { yOffset: -272, xOffset: -128 },
        { yOffset: -112, xOffset: -32 },
        { yOffset: -272, xOffset: -96 },
        { yOffset: -272, xOffset: -128 },
        null,
        null,
        { yOffset: -272, xOffset: -96 },
        { yOffset: -272, xOffset: -128 },
        null,
        { yOffset: -272, xOffset: -96 },
        { yOffset: -272, xOffset: -128 },
        null,
        { yOffset: -272, xOffset: -96 },
        { yOffset: -272, xOffset: -128 },
        null,
      ],
      [
        null,
        { yOffset: -288, xOffset: -96 },
        { yOffset: -288, xOffset: -128 },
        null,
        { yOffset: -288, xOffset: -96 },
        { yOffset: -288, xOffset: -128 },
        null,
        { yOffset: -288, xOffset: -96 },
        { yOffset: -288, xOffset: -128 },
        null,
        null,
        { yOffset: -288, xOffset: -96 },
        { yOffset: -288, xOffset: -128 },
        null,
        { yOffset: -288, xOffset: -96 },
        { yOffset: -288, xOffset: -128 },
        null,
        { yOffset: -288, xOffset: -96 },
        { yOffset: -288, xOffset: -128 },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    foregroundLayer: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: 0 },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: 0 },
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: 0 },
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: 0 },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: 0 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { yOffset: -128, xOffset: 0 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: 0 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: 0 },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { yOffset: -128, xOffset: 0 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -128, xOffset: 0 },
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -256, xOffset: -240 },
        { yOffset: -128, xOffset: 0 },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        { yOffset: -128, xOffset: 0 },
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    waterLayer: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
  },
};
