import { defaultShaderMap } from '../../functions/getTimeOfDay';
import { OverworldMap } from '../../interfaces/OverworldMap';
import { campOccupants } from './occupants/camp';

export const camp: OverworldMap = {
	id: 'camp',
	tilesetUrl: '/tilesets/palletTown.png',
	occupants: campOccupants,
	timeOfDayShadersMap: defaultShaderMap,
	tileMap: {
		baseLayer: [
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
			[
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
				{ yOffset: -208, xOffset: -144 },
			],
		],
		encounterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		obstacleLayer: [
			[
				{ yOffset: 0, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				null,
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: 0, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -16, xOffset: 0 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -16 },
			],
			[
				{ yOffset: -32, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				null,
				null,
				null,
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -48, xOffset: 0 },
				{ yOffset: -32, xOffset: -16 },
			],
		],
		decorationLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -32, xOffset: -32 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -336 },
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -144, xOffset: -32 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -144, xOffset: -336 },
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -272, xOffset: -32 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -336 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -32, xOffset: -32 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -336 },
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -144, xOffset: -32 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -144, xOffset: -336 },
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -272, xOffset: -32 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -336 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -32, xOffset: -32 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -336 },
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -144, xOffset: -32 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -144, xOffset: -336 },
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -144, xOffset: -32 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -144, xOffset: -336 },
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -272, xOffset: -32 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -336 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -32, xOffset: -32 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -320 },
				{ yOffset: -32, xOffset: -336 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -32, xOffset: -32 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -48 },
				{ yOffset: -32, xOffset: -336 },
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -144, xOffset: -32 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -272, xOffset: -320 },
				{ yOffset: -272, xOffset: -336 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -144, xOffset: -32 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -80, xOffset: -176 },
				{ yOffset: -144, xOffset: -336 },
				null,
				null,
			],
			[
				null,
				null,
				{ yOffset: -272, xOffset: -32 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -320 },
				{ yOffset: -288, xOffset: -336 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -32 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -256 },
				{ yOffset: -288, xOffset: -336 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		foregroundLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		waterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -272, xOffset: -112 },
				{ yOffset: -272, xOffset: -144 },
				{ yOffset: -272, xOffset: -160 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
	},
};
