import { defaultShaderMap } from "../../functions/getTimeOfDay";
import { OverworldMap } from "../../interfaces/OverworldMap";
import { campOccupants } from "./occupants/campFarm";

export const campFarm: OverworldMap = {
  area: "OPEN",
  id: "campFarm",
  tilesetUrl: "/tilesets/newMasterSheet.png",
  occupants: campOccupants,
  timeOfDayShadersMap: defaultShaderMap,
  tileMap: {
    baseLayer: [
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
      [
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
        { yOffset: -144, xOffset: -64 },
      ],
    ],
    encounterLayer: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    obstacleLayer: [
      [
        { yOffset: -256, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -256, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -272, xOffset: -144 },
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        { yOffset: -272, xOffset: -160 },
      ],
      [
        { yOffset: -288, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -304, xOffset: -144 },
        { yOffset: -288, xOffset: -160 },
      ],
    ],
    decorationLayer: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    foregroundLayer: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
    waterLayer: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
  },
};
