import { TimeOfDay } from '../../functions/getTimeOfDay';
import { OverworldEncounter } from '../../interfaces/OverworldMap';

export type EncounterMap = Record<TimeOfDay | 'BASE', OverworldEncounter[]>;
export const routeN1Encounters: EncounterMap = {
	BASE: [{ name: 'pikachu', xp: 125, rarity: 'rare' }],
	MORNING: [
		{ name: 'starly', xp: 50, rarity: 'common' },
		{ name: 'starly', xp: 100, rarity: 'common' },
		{ name: 'starly', xp: 125, rarity: 'medium' },
		{ name: 'bidoof', xp: 50, rarity: 'common' },
		{ name: 'bidoof', xp: 100, rarity: 'common' },
		{ name: 'bidoof', xp: 125, rarity: 'medium' },
		{ name: 'kricketot', xp: 50, rarity: 'common' },
		{ name: 'kricketot', xp: 100, rarity: 'common' },
		{ name: 'kricketot', xp: 125, rarity: 'medium' },
		{ name: 'shinx', xp: 125, rarity: 'rare' },
		{ name: 'riolu', xp: 125, rarity: 'ultra-rare' },
	],
	DAY: [
		{ name: 'poochyena', xp: 50, rarity: 'common' },
		{ name: 'poochyena', xp: 100, rarity: 'common' },
		{ name: 'poochyena', xp: 125, rarity: 'medium' },
		{ name: 'zigzagoon', xp: 50, rarity: 'common' },
		{ name: 'zigzagoon', xp: 100, rarity: 'common' },
		{ name: 'zigzagoon', xp: 125, rarity: 'medium' },
		{ name: 'taillow', xp: 50, rarity: 'common' },
		{ name: 'taillow', xp: 100, rarity: 'common' },
		{ name: 'taillow', xp: 125, rarity: 'medium' },
		{ name: 'lotad', xp: 125, rarity: 'rare' },

		{ name: 'zangoose', xp: 125, rarity: 'ultra-rare' },
	],
	EVENING: [
		{ name: 'rattata', xp: 50, rarity: 'common' },
		{ name: 'rattata', xp: 100, rarity: 'common' },
		{ name: 'rattata', xp: 125, rarity: 'medium' },
		{ name: 'pidgey', xp: 50, rarity: 'common' },
		{ name: 'pidgey', xp: 100, rarity: 'common' },
		{ name: 'pidgey', xp: 125, rarity: 'medium' },
		{ name: 'caterpie', xp: 50, rarity: 'common' },
		{ name: 'caterpie', xp: 100, rarity: 'common' },
		{ name: 'caterpie', xp: 125, rarity: 'medium' },
		{ name: 'gastly', xp: 125, rarity: 'rare' },
		{ name: 'eevee', xp: 125, rarity: 'ultra-rare' },
	],
	NIGHT: [
		{ name: 'hoothoot', xp: 100, rarity: 'common' },
		{ name: 'hoothoot', xp: 50, rarity: 'common' },
		{ name: 'hoothoot', xp: 125, rarity: 'medium' },
		{ name: 'spinarak', xp: 100, rarity: 'common' },
		{ name: 'spinarak', xp: 50, rarity: 'common' },
		{ name: 'spinarak', xp: 125, rarity: 'medium' },
		{ name: 'teddiursa', xp: 100, rarity: 'common' },
		{ name: 'teddiursa', xp: 50, rarity: 'common' },
		{ name: 'teddiursa', xp: 125, rarity: 'medium' },
		{ name: 'misdreavus', xp: 125, rarity: 'rare' },
		{ name: 'houndour', xp: 125, rarity: 'ultra-rare' },
	],
};
export const routeN1E1Encounters: EncounterMap = {
	BASE: [],
	MORNING: [
		{ name: 'patrat', xp: 1000, rarity: 'common' },
		{ name: 'patrat', xp: 800, rarity: 'common' },
		{ name: 'patrat', xp: 1500, rarity: 'medium' },
		{ name: 'lillipup', xp: 1000, rarity: 'common' },
		{ name: 'lillipup', xp: 800, rarity: 'common' },
		{ name: 'lillipup', xp: 1500, rarity: 'medium' },
		{ name: 'timburr', xp: 1000, rarity: 'common' },
		{ name: 'timburr', xp: 800, rarity: 'common' },
		{ name: 'timburr', xp: 1500, rarity: 'medium' },
		{ name: 'scraggy', xp: 1500, rarity: 'rare' },
		{ name: 'emolga', xp: 1000, rarity: 'ultra-rare' },
	],
	DAY: [
		{ name: 'bunnelby', xp: 1000, rarity: 'common' },
		{ name: 'bunnelby', xp: 800, rarity: 'common' },
		{ name: 'bunnelby', xp: 1500, rarity: 'medium' },
		{ name: 'fletchling', xp: 1000, rarity: 'common' },
		{ name: 'fletchling', xp: 800, rarity: 'common' },
		{ name: 'fletchling', xp: 1500, rarity: 'medium' },
		{ name: 'skiddo', xp: 1000, rarity: 'common' },
		{ name: 'skiddo', xp: 800, rarity: 'common' },
		{ name: 'skiddo', xp: 1500, rarity: 'medium' },
		{ name: 'pancham', xp: 1500, rarity: 'rare' },
		{ name: 'noibat', xp: 1000, rarity: 'ultra-rare' },
	],
	EVENING: [
		{ name: 'pikipek', xp: 1000, rarity: 'common' },
		{ name: 'pikipek', xp: 800, rarity: 'common' },
		{ name: 'pikipek', xp: 1500, rarity: 'medium' },
		{ name: 'bounsweet', xp: 1000, rarity: 'common' },
		{ name: 'bounsweet', xp: 800, rarity: 'common' },
		{ name: 'bounsweet', xp: 1500, rarity: 'medium' },
		{ name: 'grubbin', xp: 1000, rarity: 'common' },
		{ name: 'grubbin', xp: 800, rarity: 'common' },
		{ name: 'grubbin', xp: 1500, rarity: 'medium' },
		{ name: 'rockruff', xp: 1500, rarity: 'rare' },
		{ name: 'oranguru', xp: 1500, rarity: 'ultra-rare' },
	],
	NIGHT: [
		{ name: 'rookidee', xp: 800, rarity: 'common' },
		{ name: 'rookidee', xp: 1000, rarity: 'common' },
		{ name: 'rookidee', xp: 1500, rarity: 'medium' },
		{ name: 'wooloo', xp: 800, rarity: 'common' },
		{ name: 'wooloo', xp: 1000, rarity: 'common' },
		{ name: 'wooloo', xp: 1500, rarity: 'medium' },
		{ name: 'yamper', xp: 800, rarity: 'common' },
		{ name: 'yamper', xp: 8000, rarity: 'common' },
		{ name: 'yamper', xp: 1500, rarity: 'medium' },
		{ name: 'silicobra', xp: 1500, rarity: 'rare' },
		{ name: 'toxel', xp: 1500, rarity: 'ultra-rare' },
	],
};
