import { TimeOfDay } from '../../functions/getTimeOfDay';
import { OverworldEncounter } from '../../interfaces/OverworldMap';

export const routeN1Encounters: Record<TimeOfDay, OverworldEncounter[]> = {
	MORNING: [
		{ name: 'pikachu', xp: 125, rarity: 'rare' },
		{ name: 'starly', xp: 50, rarity: 'common' },
		{ name: 'starly', xp: 100, rarity: 'common' },
		{ name: 'starly', xp: 125, rarity: 'medium' },
		{ name: 'bidoof', xp: 50, rarity: 'common' },
		{ name: 'bidoof', xp: 100, rarity: 'common' },
		{ name: 'bidoof', xp: 125, rarity: 'medium' },
		{ name: 'kricketot', xp: 50, rarity: 'common' },
		{ name: 'kricketot', xp: 100, rarity: 'common' },
		{ name: 'kricketot', xp: 125, rarity: 'medium' },
		{ name: 'shinx', xp: 125, rarity: 'rare' },
		{ name: 'riolu', xp: 125, rarity: 'ultra-rare' },
	],
	DAY: [
		{ name: 'poochyena', xp: 50, rarity: 'common' },
		{ name: 'poochyena', xp: 100, rarity: 'common' },
		{ name: 'poochyena', xp: 125, rarity: 'medium' },
		{ name: 'zigzagoon', xp: 50, rarity: 'common' },
		{ name: 'zigzagoon', xp: 100, rarity: 'common' },
		{ name: 'zigzagoon', xp: 125, rarity: 'medium' },
		{ name: 'taillow', xp: 50, rarity: 'common' },
		{ name: 'taillow', xp: 100, rarity: 'common' },
		{ name: 'taillow', xp: 125, rarity: 'medium' },
		{ name: 'lotad', xp: 125, rarity: 'rare' },
		{ name: 'pikachu', xp: 125, rarity: 'rare' },
		{ name: 'zangoose', xp: 125, rarity: 'ultra-rare' },
	],
	EVENING: [
		{ name: 'pikachu', xp: 125, rarity: 'rare' },
		{ name: 'rattata', xp: 50, rarity: 'common' },
		{ name: 'rattata', xp: 100, rarity: 'common' },
		{ name: 'rattata', xp: 125, rarity: 'medium' },
		{ name: 'pidgey', xp: 50, rarity: 'common' },
		{ name: 'pidgey', xp: 100, rarity: 'common' },
		{ name: 'pidgey', xp: 125, rarity: 'medium' },
		{ name: 'caterpie', xp: 50, rarity: 'common' },
		{ name: 'caterpie', xp: 100, rarity: 'common' },
		{ name: 'caterpie', xp: 125, rarity: 'medium' },
		{ name: 'gastly', xp: 125, rarity: 'rare' },
		{ name: 'eevee', xp: 125, rarity: 'ultra-rare' },
	],
	NIGHT: [
		{ name: 'pikachu', xp: 125, rarity: 'rare' },
		{ name: 'hoothoot', xp: 100, rarity: 'common' },
		{ name: 'hoothoot', xp: 50, rarity: 'common' },
		{ name: 'hoothoot', xp: 125, rarity: 'medium' },
		{ name: 'spinarak', xp: 100, rarity: 'common' },
		{ name: 'spinarak', xp: 50, rarity: 'common' },
		{ name: 'spinarak', xp: 125, rarity: 'medium' },
		{ name: 'teddiursa', xp: 100, rarity: 'common' },
		{ name: 'teddiursa', xp: 50, rarity: 'common' },
		{ name: 'teddiursa', xp: 125, rarity: 'medium' },
		{ name: 'misdreavus', xp: 125, rarity: 'rare' },
		{ name: 'houndour', xp: 125, rarity: 'ultra-rare' },
	],
};
