import { OverworldMap } from '../../interfaces/OverworldMap';
import { SpriteEnum } from '../../interfaces/SpriteEnum';

const occs: OverworldMap['occupants'] = [
	{
		id: 'bubu',
		type: 'ITEM',
		item: 'poke-ball',
		amount: 5,
		x: 20,
		y: 3,
		conditionFunction: (s) => s.handledOccupants.every((h) => h.id !== 'bubu'),
	},
	{
		id: 'HIdden_IT',
		type: 'HIDDEN_ITEM',
		item: 'ultra-ball',
		amount: 3,
		x: 3,
		y: 3,
		conditionFunction: (s) =>
			s.handledOccupants.every((h) => h.id !== 'HIdden_IT'),
	},
	{
		id: 'Honey Tree',
		type: 'HONEY_TREE',
		x: 10,
		y: 2,
		conditionFunction: () => true,
	},
	{
		id: 'pikachu-fan',
		type: 'NPC',
		x: 12,
		y: 2,
		quest: 'catch a pikachu',
		handledMessage: ['Did you find a pikachu?'],
		unhandledMessage: [
			'My favorite pokemon is pikachu',
			'Do you have one yet?',
		],
		orientation: 'DOWN',
		sprite: SpriteEnum.nerd,
		conditionFunction: () => true,
	},
	{
		id: 'pc',
		type: 'PC',
		x: 11,
		y: 2,
		approachDirection: 'UP',
		conditionFunction: () => true,
	},
	{
		id: 'honey-guy',
		type: 'NPC',
		x: 9,
		y: 2,
		gifts: { honey: 10 },
		quest: 'lure a pokemon with honey',
		handledMessage: ['Did the pokemon like the honey?'],
		unhandledMessage: [
			'I have seen some pokemon slurp the sap from these golden trees',
			'Maybe we can attract them by putting honey on the tree',
		],
		orientation: 'DOWN',
		sprite: SpriteEnum.artist,
		conditionFunction: () => true,
	},
	{
		id: 'evolution-researcher',
		type: 'NPC',
		x: 13,
		y: 2,
		quest: 'evolve a pokemon',
		handledMessage: ['Evolution is so cool'],
		unhandledMessage: [
			'Some Pokemon change their form',
			',when they reach a higher level',
			'Others need special items',
			'Can you please evolve a pokemon for me?',
		],
		orientation: 'DOWN',
		sprite: SpriteEnum.scientistFemale,
		conditionFunction: () => true,
	},
];

export const routeN1: OverworldMap = {
	id: 'routeN1',
	possibleEncounters: {
		MORNING: [
			{ dexId: 25, xp: 125 },
			{ dexId: 324, xp: 44 },
		],
		DAY: [{ dexId: 25, xp: 125 }],
		EVENING: [{ dexId: 25, xp: 125 }],
		NIGHT: [
			{ dexId: 167, xp: 125 },
			{ dexId: 25, xp: 125 },
		],
	},
	tileMap: {
		baseLayer: [
			[
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
			],
			[
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
			],
			[
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
			],
			[
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
			],
			[
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
			],
			[
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
			],
			[
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
			],
			[
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
			],
			[
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
				{ yOffset: 0, xOffset: -16 },
			],
		],
		encounterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
			],
			[
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -80 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		obstacleLayer: [
			[
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
			],
			[
				{ yOffset: -48, xOffset: -928 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -48, xOffset: -928 },
			],
			[
				{ yOffset: -48, xOffset: -928 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -48, xOffset: -928 },
			],
			[
				{ yOffset: -48, xOffset: -928 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -48, xOffset: -928 },
			],
			[
				{ yOffset: -48, xOffset: -928 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				null,
				null,
				null,
				null,
				{ yOffset: -48, xOffset: -928 },
			],
			[
				{ yOffset: -48, xOffset: -928 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -48, xOffset: -928 },
			],
			[
				{ yOffset: -48, xOffset: -928 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -48, xOffset: -928 },
			],
			[
				{ yOffset: -48, xOffset: -928 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -48, xOffset: -928 },
			],
			[
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
				{ yOffset: -32, xOffset: -96 },
			],
		],
		decorationLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -64 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -64 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -64 },
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -64 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: 0, xOffset: -64 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		foregroundLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				{ yOffset: -16, xOffset: -96 },
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
	},

	occupants: occs,
};
