import { OverworldMap } from '../../../interfaces/OverworldMap';

export const testMap: OverworldMap = {
	id: 'testMap',
	possibleEncounters: {
		MORNING: [
			{ dexId: 25, xp: 125 },
			{ dexId: 324, xp: 44 },
		],
		DAY: [],
		EVENING: [],
		NIGHT: [{ dexId: 167, xp: 125 }],
	},
	tileMap: {
		baseLayer: [
			[
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
			],
			[
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
			],
			[
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
			],
			[
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
			],
			[
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
			],
			[
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
			],
			[
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
			],
			[
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -18, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
			],
			[
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
				{ yOffset: -1, xOffset: -103 },
			],
		],
		encounterLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				{ yOffset: -1, xOffset: -120 },
				null,
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -1, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
		obstacleLayer: [
			[
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
			],
			[
				{ yOffset: -205, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -205, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -205, xOffset: -120 },
			],
			[
				{ yOffset: -205, xOffset: -120 },
				null,
				null,
				null,
				{ yOffset: -273, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -273, xOffset: -120 },
				null,
				null,
				null,
				{ yOffset: -273, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -222, xOffset: -239 },
				{ yOffset: -222, xOffset: -256 },
				{ yOffset: -222, xOffset: -273 },
				{ yOffset: -205, xOffset: -120 },
			],
			[
				{ yOffset: -205, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -273, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -273, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -239, xOffset: -239 },
				{ yOffset: -239, xOffset: -256 },
				{ yOffset: -239, xOffset: -273 },
				{ yOffset: -205, xOffset: -120 },
			],
			[
				{ yOffset: -205, xOffset: -120 },
				null,
				{ yOffset: -273, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -256, xOffset: -239 },
				{ yOffset: -256, xOffset: -256 },
				{ yOffset: -256, xOffset: -273 },
				{ yOffset: -205, xOffset: -120 },
			],
			[
				{ yOffset: -205, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -69, xOffset: -324 },
				null,
				null,
				null,
				null,
				{ yOffset: -205, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -205, xOffset: -120 },
			],
			[
				{ yOffset: -205, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -273, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -205, xOffset: -120 },
			],
			[
				{ yOffset: -205, xOffset: -120 },
				null,
				{ yOffset: -69, xOffset: -324 },
				null,
				null,
				{ yOffset: -205, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -273, xOffset: -120 },
				null,
				null,
				null,
				null,
				{ yOffset: -205, xOffset: -120 },
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -205, xOffset: -120 },
			],
			[
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
				{ yOffset: -205, xOffset: -120 },
			],
		],
		decorationLayer: [
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				{ yOffset: -205, xOffset: -239 },
				{ yOffset: -205, xOffset: -256 },
				{ yOffset: -205, xOffset: -273 },
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
			[
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
				null,
			],
		],
	},
	occupants: [],
};
