import { OverworldMap } from '../../../shared/OverworldMap';
import { GameMap } from '../../../shared/interfaces';

export const tiles: GameMap = {
	baseLayer: [
		[
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
		],
		[
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
		],
		[
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
		],
		[
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
		],
		[
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
		],
		[
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
		],
		[
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
		],
		[
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
		],
		[
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
			{ yOffset: -18, xOffset: -103 },
		],
	],
	obstacleLayer: [
		[
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -205, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
		],
		[
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -205, xOffset: -120 },
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
		],
		[
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
		],
		[
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
		],
		[
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
		],
		[
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -69, xOffset: -324 },
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -205, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
		],
		[
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
		],
		[
			undefined,
			undefined,
			{ yOffset: -69, xOffset: -324 },
			undefined,
			undefined,
			{ yOffset: -205, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -205, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
		],
		[
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -273, xOffset: -120 },
		],
	],
	decorationLayer: [
		[
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
		],
		[
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
		],
		[
			undefined,
			undefined,
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
		],
		[
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
		],
		[
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
		],
		[
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
		],
		[
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
		],
		[
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			{ yOffset: -1, xOffset: -120 },
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
		],
		[
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
			undefined,
		],
	],
};

export const testMap: OverworldMap = {
	id: 'testMap',
	possibleEncounters: { MORNING: [], DAY: [], EVENING: [], NIGHT: [] },
	tileMap: tiles,
	occupants: [],
};
