import { Quest } from '../../interfaces/Quest';
import {
	EmptyStatObject,
	generateRandomStatObject,
} from '../../interfaces/StatObject';
import { QuestName } from '../checkLists/questsRecord';

export const travellingTrainerQuests: Partial<Record<QuestName, Quest>> = {
	'defeat research assistant barry': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => !!s.mileStones.barryDefeatedAt,
		researchPoints: 10,
		rewardItems: { 'exp-candy-xs': 10 },
	},
	'defeat barry at lvl 20 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.barryDefeatedAt ?? 0) >= 8000,
		researchPoints: 20,
		availableAfter: 'defeat research assistant barry',
		rewardItems: { 'exp-candy-s': 10 },
	},
	'defeat barry at lvl 40 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.barryDefeatedAt ?? 0) >= 64000,
		researchPoints: 40,
		availableAfter: 'defeat barry at lvl 20 or higher',
		rewardItems: { 'exp-candy-m': 10 },
	},
	'defeat barry at lvl 60 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.barryDefeatedAt ?? 0) >= 216000,
		researchPoints: 60,
		availableAfter: 'defeat barry at lvl 40 or higher',
		rewardItems: { 'exp-candy-l': 10 },
	},
	'defeat barry at lvl 80 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.barryDefeatedAt ?? 0) >= 512000,
		researchPoints: 80,
		availableAfter: 'defeat barry at lvl 60 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
	},
	'defeat barry at lvl 100': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.barryDefeatedAt ?? 0) >= 1000000,
		researchPoints: 80,
		availableAfter: 'defeat barry at lvl 80 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
		rewardPokemon: {
			caughtAtDate: new Date().getTime(),
			growthRate: 'medium',
			unlockedMoves: ['swords-dance'],
			fixedAbility: true,
			shiny: true,
			maxHp: 30,
			effortValues: EmptyStatObject,
			ppBoostedMoves: [],
			caughtOnMap: 'camp',
			gender: 'MALE',
			stepsWalked: 0,
			ownerId: '',
			damage: 0,
			id: '',
			ball: 'poke-ball',
			ability: 'sniper',
			name: 'drapion',
			xp: 125,
			nature: 'adamant',
			intrinsicValues: generateRandomStatObject(31),
			happiness: 70,
			firstMove: { name: 'swords-dance', usedPP: 0 },
		},
	},
	'defeat trainer silver': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => !!s.mileStones.silverDefeatedAt,
		researchPoints: 10,
		rewardItems: { 'exp-candy-xs': 10 },
	},
	'defeat silver at lvl 20 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.silverDefeatedAt ?? 0) >= 8000,
		researchPoints: 20,
		availableAfter: 'defeat trainer silver',
		rewardItems: { 'exp-candy-s': 10 },
	},
	'defeat silver at lvl 40 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.silverDefeatedAt ?? 0) >= 64000,
		researchPoints: 40,
		availableAfter: 'defeat silver at lvl 20 or higher',
		rewardItems: { 'exp-candy-m': 10 },
	},
	'defeat silver at lvl 60 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.silverDefeatedAt ?? 0) >= 216000,
		researchPoints: 60,
		availableAfter: 'defeat silver at lvl 40 or higher',
		rewardItems: { 'exp-candy-l': 10 },
	},
	'defeat silver at lvl 80 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.silverDefeatedAt ?? 0) >= 512000,
		researchPoints: 80,
		availableAfter: 'defeat silver at lvl 60 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
	},
	'defeat silver at lvl 100': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.silverDefeatedAt ?? 0) >= 1000000,
		researchPoints: 80,
		availableAfter: 'defeat silver at lvl 80 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
		rewardPokemon: {
			caughtAtDate: new Date().getTime(),
			growthRate: 'medium',
			unlockedMoves: ['tail-glow'],
			fixedAbility: true,
			shiny: true,
			maxHp: 30,
			effortValues: EmptyStatObject,
			ppBoostedMoves: [],
			caughtOnMap: 'camp',
			gender: 'MALE',
			stepsWalked: 0,
			ownerId: '',
			damage: 0,
			id: '',
			ball: 'poke-ball',
			ability: 'drought',
			name: 'kingdra',
			xp: 125,
			nature: 'adamant',
			intrinsicValues: generateRandomStatObject(31),
			happiness: 70,
			firstMove: { name: 'tail-glow', usedPP: 0 },
		},
	},
	'defeat trainer cynthia': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => !!s.mileStones.cynthiaDefeatedAt,
		researchPoints: 10,
		rewardItems: { 'exp-candy-xs': 10 },
	},
	'defeat cynthia at lvl 20 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.cynthiaDefeatedAt ?? 0) >= 8000,
		researchPoints: 20,
		availableAfter: 'defeat trainer cynthia',
		rewardItems: { 'exp-candy-s': 10 },
	},
	'defeat cynthia at lvl 40 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.cynthiaDefeatedAt ?? 0) >= 64000,
		researchPoints: 40,
		availableAfter: 'defeat cynthia at lvl 20 or higher',
		rewardItems: { 'exp-candy-m': 10 },
	},
	'defeat cynthia at lvl 60 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.cynthiaDefeatedAt ?? 0) >= 216000,
		researchPoints: 60,
		availableAfter: 'defeat cynthia at lvl 40 or higher',
		rewardItems: { 'exp-candy-l': 10 },
	},
	'defeat cynthia at lvl 80 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.cynthiaDefeatedAt ?? 0) >= 512000,
		researchPoints: 80,
		availableAfter: 'defeat cynthia at lvl 60 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
	},
	'defeat cynthia at lvl 100': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.cynthiaDefeatedAt ?? 0) >= 1000000,
		researchPoints: 80,
		availableAfter: 'defeat cynthia at lvl 80 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
		rewardPokemon: {
			caughtAtDate: new Date().getTime(),
			growthRate: 'medium',
			unlockedMoves: ['tail-glow', 'aura-sphere'],
			fixedAbility: true,
			shiny: true,
			maxHp: 30,
			effortValues: EmptyStatObject,
			ppBoostedMoves: [],
			caughtOnMap: 'camp',
			gender: 'MALE',
			stepsWalked: 0,
			ownerId: '',
			damage: 0,
			id: '',
			ball: 'poke-ball',
			ability: 'mega-launcher',
			name: 'riolu',
			xp: 125,
			nature: 'modest',
			intrinsicValues: generateRandomStatObject(31),
			happiness: 70,
			firstMove: { name: 'tail-glow', usedPP: 0 },
			secondMove: { name: 'aura-sphere', usedPP: 0 },
		},
	},
	'defeat trainer n': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => !!s.mileStones.nDefeatedAt,
		researchPoints: 10,
		rewardItems: { 'exp-candy-xs': 10 },
	},
	'defeat trainer n at lvl 20 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.nDefeatedAt ?? 0) >= 8000,
		researchPoints: 20,
		availableAfter: 'defeat trainer n',
		rewardItems: { 'exp-candy-s': 10 },
	},
	'defeat trainer n at lvl 40 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.nDefeatedAt ?? 0) >= 64000,
		researchPoints: 40,
		availableAfter: 'defeat trainer n at lvl 20 or higher',
		rewardItems: { 'exp-candy-m': 10 },
	},
	'defeat trainer n at lvl 60 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.nDefeatedAt ?? 0) >= 216000,
		researchPoints: 60,
		availableAfter: 'defeat trainer n at lvl 40 or higher',
		rewardItems: { 'exp-candy-l': 10 },
	},
	'defeat trainer n at lvl 80 or higher': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.nDefeatedAt ?? 0) >= 512000,
		researchPoints: 80,
		availableAfter: 'defeat trainer n at lvl 60 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
	},
	'defeat trainer n at lvl 100': {
		category: 'BATTLE',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.nDefeatedAt ?? 0) >= 1000000,
		researchPoints: 80,
		availableAfter: 'defeat trainer n at lvl 80 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
		rewardPokemon: {
			caughtAtDate: new Date().getTime(),
			growthRate: 'medium',
			unlockedMoves: ['swords-dance', 'night-slash'],
			fixedAbility: true,
			shiny: true,
			maxHp: 30,
			effortValues: EmptyStatObject,
			ppBoostedMoves: [],
			caughtOnMap: 'camp',
			gender: 'MALE',
			stepsWalked: 0,
			ownerId: '',
			damage: 0,
			id: '',
			ball: 'poke-ball',
			ability: 'sharpness',
			name: 'zorua',
			xp: 125,
			nature: 'modest',
			intrinsicValues: generateRandomStatObject(31),
			happiness: 70,
			firstMove: { name: 'swords-dance', usedPP: 0 },
			secondMove: { name: 'night-slash', usedPP: 0 },
		},
	},
};
