import { v4 } from 'uuid';
import { Quest } from '../../interfaces/Quest';
import {
	EmptyStatObject,
	generateRandomStatObject,
} from '../../interfaces/StatObject';
import { QuestName } from '../questsRecord';
import { OwnedPokemon } from '../../interfaces/OwnedPokemon';

const testPokemon: OwnedPokemon = {
	name: 'teddiursa',
	gender: 'MALE',
	ownerId: 'test',
	id: 'bingo',
	ball: 'poke-ball',
	onTeam: true,
	firstMove: { name: 'tackle', usedPP: 0 },
	damage: 0,
	nature: 'adamant',
	xp: 125,
	ability: 'shadow-tag',
	happiness: 70,
	stepsWalked: 0,
	heldItemName: 'berry-juice',
	maxHp: 20,
	effortValues: EmptyStatObject,
	intrinsicValues: EmptyStatObject,
	ppBoostedMoves: [],
	caughtOnMap: 'camp',
	weightModifier: Math.random(),
	unlockedMoves: [],
	growthRate: 'medium',
	caughtAtDate: new Date().getTime(),
};

export const travellingTrainerQuests: Partial<Record<QuestName, Quest>> = {
	'defeat research assistant barry': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => !!s.mileStones.barryDefeatedAt,
		researchPoints: 10,
		rewardItems: { 'exp-candy-xs': 10 },
	},
	'defeat barry at lvl 20 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.barryDefeatedAt ?? 0) >= 8000,
		researchPoints: 20,
		availableAfter: 'defeat research assistant barry',
		rewardItems: { 'exp-candy-s': 10 },
	},
	'defeat barry at lvl 40 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.barryDefeatedAt ?? 0) >= 64000,
		researchPoints: 40,
		availableAfter: 'defeat barry at lvl 20 or higher',
		rewardItems: { 'exp-candy-m': 10 },
	},
	'defeat barry at lvl 60 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.barryDefeatedAt ?? 0) >= 216000,
		researchPoints: 60,
		availableAfter: 'defeat barry at lvl 40 or higher',
		rewardItems: { 'exp-candy-l': 10 },
	},
	'defeat barry at lvl 80 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.barryDefeatedAt ?? 0) >= 512000,
		researchPoints: 80,
		availableAfter: 'defeat barry at lvl 60 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
	},
	'defeat barry at lvl 100': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.barryDefeatedAt ?? 0) >= 1000000,
		researchPoints: 100,
		availableAfter: 'defeat barry at lvl 80 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
		rewardPokemon: {
			...testPokemon,
			id: v4(),
			name: 'skorupi',
			shiny: true,
			caughtAtDate: new Date().getTime(),
			xp: 125,
			intrinsicValues: generateRandomStatObject(31, 25),
			caughtOnMap: 'camp',
		},
	},
	'defeat trainer silver': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => !!s.mileStones.silverDefeatedAt,
		researchPoints: 10,
		rewardItems: { 'exp-candy-xs': 10 },
	},
	'defeat silver at lvl 20 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.silverDefeatedAt ?? 0) >= 8000,
		researchPoints: 20,
		availableAfter: 'defeat trainer silver',
		rewardItems: { 'exp-candy-s': 10 },
	},
	'defeat silver at lvl 40 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.silverDefeatedAt ?? 0) >= 64000,
		researchPoints: 40,
		availableAfter: 'defeat silver at lvl 20 or higher',
		rewardItems: { 'exp-candy-m': 10 },
	},
	'defeat silver at lvl 60 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.silverDefeatedAt ?? 0) >= 216000,
		researchPoints: 60,
		availableAfter: 'defeat silver at lvl 40 or higher',
		rewardItems: { 'exp-candy-l': 10 },
	},
	'defeat silver at lvl 80 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.silverDefeatedAt ?? 0) >= 512000,
		researchPoints: 80,
		availableAfter: 'defeat silver at lvl 60 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
	},
	'defeat silver at lvl 100': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.silverDefeatedAt ?? 0) >= 1000000,
		researchPoints: 100,
		availableAfter: 'defeat silver at lvl 80 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
		rewardPokemon: {
			...testPokemon,
			id: v4(),
			name: 'mareep',
			shiny: true,
			caughtAtDate: new Date().getTime(),
			xp: 125,
			intrinsicValues: generateRandomStatObject(31, 25),
			caughtOnMap: 'camp',
		},
	},
	'defeat trainer cynthia': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => !!s.mileStones.cynthiaDefeatedAt,
		researchPoints: 10,
		rewardItems: { 'exp-candy-xs': 10 },
	},
	'defeat cynthia at lvl 20 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.cynthiaDefeatedAt ?? 0) >= 8000,
		researchPoints: 20,
		availableAfter: 'defeat trainer cynthia',
		rewardItems: { 'exp-candy-s': 10 },
	},
	'defeat cynthia at lvl 40 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.cynthiaDefeatedAt ?? 0) >= 64000,
		researchPoints: 40,
		availableAfter: 'defeat cynthia at lvl 20 or higher',
		rewardItems: { 'exp-candy-m': 10 },
	},
	'defeat cynthia at lvl 60 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.cynthiaDefeatedAt ?? 0) >= 216000,
		researchPoints: 60,
		availableAfter: 'defeat cynthia at lvl 40 or higher',
		rewardItems: { 'exp-candy-l': 10 },
	},
	'defeat cynthia at lvl 80 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.cynthiaDefeatedAt ?? 0) >= 512000,
		researchPoints: 80,
		availableAfter: 'defeat cynthia at lvl 60 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
	},
	'defeat cynthia at lvl 100': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.cynthiaDefeatedAt ?? 0) >= 1000000,
		researchPoints: 100,
		availableAfter: 'defeat cynthia at lvl 80 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
		rewardPokemon: {
			...testPokemon,
			id: v4(),
			name: 'riolu',
			shiny: true,
			caughtAtDate: new Date().getTime(),
			xp: 125,
			intrinsicValues: generateRandomStatObject(31, 25),
			caughtOnMap: 'camp',
		},
	},
	'defeat trainer n': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => !!s.mileStones.nDefeatedAt,
		researchPoints: 10,
		rewardItems: { 'exp-candy-xs': 10 },
	},
	'defeat trainer n at lvl 20 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.nDefeatedAt ?? 0) >= 8000,
		researchPoints: 20,
		availableAfter: 'defeat trainer n',
		rewardItems: { 'exp-candy-s': 10 },
	},
	'defeat trainer n at lvl 40 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.nDefeatedAt ?? 0) >= 64000,
		researchPoints: 40,
		availableAfter: 'defeat trainer n at lvl 20 or higher',
		rewardItems: { 'exp-candy-m': 10 },
	},
	'defeat trainer n at lvl 60 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.nDefeatedAt ?? 0) >= 216000,
		researchPoints: 60,
		availableAfter: 'defeat trainer n at lvl 40 or higher',
		rewardItems: { 'exp-candy-l': 10 },
	},
	'defeat trainer n at lvl 80 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.nDefeatedAt ?? 0) >= 512000,
		researchPoints: 80,
		availableAfter: 'defeat trainer n at lvl 60 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
	},
	'defeat trainer n at lvl 100': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.nDefeatedAt ?? 0) >= 1000000,
		researchPoints: 100,
		availableAfter: 'defeat trainer n at lvl 80 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
		rewardPokemon: {
			...testPokemon,
			id: v4(),
			name: 'zorua',
			shiny: true,
			caughtAtDate: new Date().getTime(),
			xp: 125,
			intrinsicValues: generateRandomStatObject(31, 25),
			caughtOnMap: 'camp',
		},
	},
	'defeat trainer red': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => !!s.mileStones.redDefeatedAt,
		researchPoints: 10,
		rewardItems: { 'exp-candy-xs': 10 },
	},
	'defeat trainer red at lvl 20 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.redDefeatedAt ?? 0) >= 8000,
		researchPoints: 20,
		availableAfter: 'defeat trainer red',
		rewardItems: { 'exp-candy-s': 10 },
	},
	'defeat trainer red at lvl 40 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.redDefeatedAt ?? 0) >= 64000,
		researchPoints: 40,
		availableAfter: 'defeat trainer red at lvl 20 or higher',
		rewardItems: { 'exp-candy-m': 10 },
	},
	'defeat trainer red at lvl 60 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.redDefeatedAt ?? 0) >= 216000,
		researchPoints: 60,
		availableAfter: 'defeat trainer red at lvl 40 or higher',
		rewardItems: { 'exp-candy-l': 10 },
	},
	'defeat trainer red at lvl 80 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.redDefeatedAt ?? 0) >= 512000,
		researchPoints: 80,
		availableAfter: 'defeat trainer red at lvl 60 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
	},
	'defeat trainer red at lvl 100': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.redDefeatedAt ?? 0) >= 1000000,
		researchPoints: 100,
		availableAfter: 'defeat trainer red at lvl 80 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
		rewardPokemon: {
			...testPokemon,
			id: v4(),
			name: 'dratini',
			shiny: true,
			caughtAtDate: new Date().getTime(),
			xp: 125,
			intrinsicValues: generateRandomStatObject(31, 25),
			caughtOnMap: 'camp',
		},
	},
	'defeat trainer hugh': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => !!s.mileStones.hughDefeatedAt,
		researchPoints: 10,
		rewardItems: { 'exp-candy-xs': 10 },
	},
	'defeat trainer hugh at lvl 20 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.hughDefeatedAt ?? 0) >= 8000,
		researchPoints: 20,
		availableAfter: 'defeat trainer hugh',
		rewardItems: { 'exp-candy-s': 10 },
	},
	'defeat trainer hugh at lvl 40 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.hughDefeatedAt ?? 0) >= 64000,
		researchPoints: 40,
		availableAfter: 'defeat trainer hugh at lvl 20 or higher',
		rewardItems: { 'exp-candy-m': 10 },
	},
	'defeat trainer hugh at lvl 60 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.hughDefeatedAt ?? 0) >= 216000,
		researchPoints: 60,
		availableAfter: 'defeat trainer hugh at lvl 40 or higher',
		rewardItems: { 'exp-candy-l': 10 },
	},
	'defeat trainer hugh at lvl 80 or higher': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.hughDefeatedAt ?? 0) >= 512000,
		researchPoints: 80,
		availableAfter: 'defeat trainer hugh at lvl 60 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
	},
	'defeat trainer hugh at lvl 100': {
		category: 'TRAVELLING TRAINER',
		kind: 'BULLETIN',
		conditionFunction: (s) => (s.mileStones.hughDefeatedAt ?? 0) >= 1000000,
		researchPoints: 100,
		availableAfter: 'defeat trainer hugh at lvl 80 or higher',
		rewardItems: { 'exp-candy-xl': 10 },
		rewardPokemon: {
			...testPokemon,
			id: v4(),
			name: 'axew',
			shiny: true,
			caughtAtDate: new Date().getTime(),
			xp: 125,
			intrinsicValues: generateRandomStatObject(31, 25),
			caughtOnMap: 'camp',
		},
	},
};
