import { EncounterMap } from '../encounters';

export const routeE1Encounters: EncounterMap = {
	BASE: [
		{ name: 'growlithe', xp: 3000, rarity: 'medium' },
		{ name: 'growlithe-hisui', xp: 3000, rarity: 'medium' },
	],
	MORNING: [
		{ name: 'aron', xp: 1500, rarity: 'common' },
		{ name: 'aron', xp: 2000, rarity: 'common' },
		{ name: 'aron', xp: 3000, rarity: 'medium' },
		{ name: 'sandshrew', xp: 1500, rarity: 'common' },
		{ name: 'sandshrew', xp: 2000, rarity: 'common' },
		{ name: 'sandshrew', xp: 3000, rarity: 'medium' },
		{ name: 'rolycoly', xp: 1500, rarity: 'common' },
		{ name: 'rolycoly', xp: 2000, rarity: 'common' },
		{ name: 'rolycoly', xp: 3000, rarity: 'medium' },
		{ name: 'sandslash', xp: 3000, rarity: 'rare' },
		{ name: 'riolu', xp: 3000, rarity: 'ultra-rare' },
	],
	DAY: [
		{ name: 'bidoof', xp: 1500, rarity: 'common' },
		{ name: 'bidoof', xp: 2000, rarity: 'common' },
		{ name: 'bidoof', xp: 3000, rarity: 'medium' },
		{ name: 'tauros', xp: 1500, rarity: 'common' },
		{ name: 'tauros', xp: 2000, rarity: 'common' },
		{ name: 'tauros', xp: 3000, rarity: 'medium' },
		{ name: 'toedscool', xp: 1500, rarity: 'common' },
		{ name: 'toedscool', xp: 2000, rarity: 'common' },
		{ name: 'toedscool', xp: 3000, rarity: 'medium' },
		{ name: 'gligar', xp: 3000, rarity: 'rare' },
		{ name: 'sandslash', xp: 3000, rarity: 'ultra-rare' },
	],
	EVENING: [
		{ name: 'wooper', xp: 1500, rarity: 'common' },
		{ name: 'wooper', xp: 2000, rarity: 'common' },
		{ name: 'wooper', xp: 3000, rarity: 'medium' },
		{ name: 'pidgey', xp: 1500, rarity: 'common' },
		{ name: 'pidgey', xp: 2000, rarity: 'common' },
		{ name: 'pidgey', xp: 3000, rarity: 'medium' },
		{ name: 'machop', xp: 1500, rarity: 'common' },
		{ name: 'machop', xp: 2000, rarity: 'common' },
		{ name: 'machop', xp: 3000, rarity: 'medium' },
		{ name: 'diglett', xp: 1500, rarity: 'common' },
		{ name: 'diglett', xp: 2000, rarity: 'common' },
		{ name: 'diglett', xp: 3000, rarity: 'medium' },
		{ name: 'baltoy', xp: 3000, rarity: 'rare' },
		{ name: 'rockruff', xp: 3000, rarity: 'ultra-rare' },
	],
	NIGHT: [
		{ name: 'wooper-paldea', xp: 2000, rarity: 'common' },
		{ name: 'wooper-paldea', xp: 1500, rarity: 'common' },
		{ name: 'wooper-paldea', xp: 3000, rarity: 'medium' },
		{ name: 'woobat', xp: 2000, rarity: 'common' },
		{ name: 'woobat', xp: 1500, rarity: 'common' },
		{ name: 'woobat', xp: 3000, rarity: 'medium' },
		{ name: 'rattata-alola', xp: 2000, rarity: 'common' },
		{ name: 'rattata-alola', xp: 1500, rarity: 'common' },
		{ name: 'rattata-alola', xp: 3000, rarity: 'medium' },
		{ name: 'golett', xp: 3000, rarity: 'rare' },
		{ name: 'abra', xp: 3000, rarity: 'ultra-rare' },
	],
};
