import { EncounterMap } from '../encounters';

export const routeN1Encounters: EncounterMap = {
	BASE: [
		{ name: 'pikachu', xp: 125, rarity: 'rare' },
		{ name: 'eevee', xp: 125, rarity: 'rare' },
	],
	MORNING: [
		{ name: 'rattata', xp: 50, rarity: 'common' },
		{ name: 'rattata', xp: 100, rarity: 'common' },
		{ name: 'rattata', xp: 125, rarity: 'medium' },
		{ name: 'spearow', xp: 50, rarity: 'common' },
		{ name: 'spearow', xp: 100, rarity: 'common' },
		{ name: 'spearow', xp: 125, rarity: 'medium' },
		{ name: 'stunky', xp: 50, rarity: 'common' },
		{ name: 'stunky', xp: 100, rarity: 'common' },
		{ name: 'stunky', xp: 125, rarity: 'medium' },
		{ name: 'shinx', xp: 125, rarity: 'rare' },
		{ name: 'riolu', xp: 125, rarity: 'ultra-rare' },
	],
	DAY: [
		{ name: 'starly', xp: 50, rarity: 'common' },
		{ name: 'starly', xp: 100, rarity: 'common' },
		{ name: 'starly', xp: 125, rarity: 'medium' },
		{ name: 'zigzagoon', xp: 50, rarity: 'common' },
		{ name: 'zigzagoon', xp: 100, rarity: 'common' },
		{ name: 'zigzagoon', xp: 125, rarity: 'medium' },
		{ name: 'taillow', xp: 50, rarity: 'common' },
		{ name: 'taillow', xp: 100, rarity: 'common' },
		{ name: 'taillow', xp: 125, rarity: 'medium' },
		{ name: 'lotad', xp: 125, rarity: 'rare' },
		{ name: 'zangoose', xp: 125, rarity: 'ultra-rare' },
	],
	EVENING: [
		{ name: 'poochyena', xp: 50, rarity: 'common' },
		{ name: 'poochyena', xp: 100, rarity: 'common' },
		{ name: 'poochyena', xp: 125, rarity: 'medium' },
		{ name: 'pidgey', xp: 50, rarity: 'common' },
		{ name: 'pidgey', xp: 100, rarity: 'common' },
		{ name: 'pidgey', xp: 125, rarity: 'medium' },
		{ name: 'teddiursa', xp: 50, rarity: 'common' },
		{ name: 'teddiursa', xp: 100, rarity: 'common' },
		{ name: 'teddiursa', xp: 125, rarity: 'medium' },
		{ name: 'oddish', xp: 50, rarity: 'common' },
		{ name: 'oddish', xp: 100, rarity: 'common' },
		{ name: 'oddish', xp: 125, rarity: 'medium' },
		{ name: 'swablu', xp: 125, rarity: 'rare' },
		{ name: 'rockruff', xp: 125, rarity: 'ultra-rare' },
	],
	NIGHT: [
		{ name: 'hoothoot', xp: 100, rarity: 'common' },
		{ name: 'hoothoot', xp: 50, rarity: 'common' },
		{ name: 'hoothoot', xp: 125, rarity: 'medium' },
		{ name: 'houndour', xp: 100, rarity: 'common' },
		{ name: 'houndour', xp: 50, rarity: 'common' },
		{ name: 'houndour', xp: 125, rarity: 'medium' },
		{ name: 'rattata-alola', xp: 100, rarity: 'common' },
		{ name: 'rattata-alola', xp: 50, rarity: 'common' },
		{ name: 'rattata-alola', xp: 125, rarity: 'medium' },
		{ name: 'gastly', xp: 125, rarity: 'rare' },
		{ name: 'misdreavus', xp: 125, rarity: 'ultra-rare' },
	],
};
