import { EncounterMap } from '../encounters';

export const routeN1E1Encounters: EncounterMap = {
	BASE: [
		{ name: 'scyther', xp: 1500, rarity: 'rare' },
		{ name: 'meowth', xp: 1000, rarity: 'common' },
		{ name: 'nidoran-f', xp: 1000, rarity: 'medium' },
		{ name: 'nidoran-m', xp: 1000, rarity: 'medium' },
	],
	MORNING: [
		{ name: 'stunky', xp: 1000, rarity: 'common' },
		{ name: 'stunky', xp: 800, rarity: 'common' },
		{ name: 'stunky', xp: 1500, rarity: 'medium' },
		{ name: 'lillipup', xp: 1000, rarity: 'common' },
		{ name: 'lillipup', xp: 800, rarity: 'common' },
		{ name: 'lillipup', xp: 1500, rarity: 'medium' },
		{ name: 'smoliv', xp: 1000, rarity: 'common' },
		{ name: 'smoliv', xp: 800, rarity: 'common' },
		{ name: 'smoliv', xp: 1500, rarity: 'medium' },
		{ name: 'pinsir', xp: 1500, rarity: 'rare' },
		{ name: 'shroomish', xp: 1000, rarity: 'rare' },
		{ name: 'emolga', xp: 1000, rarity: 'ultra-rare' },
	],
	DAY: [
		{ name: 'kricketot', xp: 1000, rarity: 'common' },
		{ name: 'kricketot', xp: 800, rarity: 'common' },
		{ name: 'kricketot', xp: 1500, rarity: 'medium' },
		{ name: 'fletchling', xp: 1000, rarity: 'common' },
		{ name: 'fletchling', xp: 800, rarity: 'common' },
		{ name: 'fletchling', xp: 1500, rarity: 'medium' },
		{ name: 'skiddo', xp: 1000, rarity: 'common' },
		{ name: 'skiddo', xp: 800, rarity: 'common' },
		{ name: 'skiddo', xp: 1500, rarity: 'medium' },
		{ name: 'pancham', xp: 1500, rarity: 'rare' },
		{ name: 'riolu', xp: 1500, rarity: 'ultra-rare' },
	],
	EVENING: [
		{ name: 'pikipek', xp: 1000, rarity: 'common' },
		{ name: 'pikipek', xp: 800, rarity: 'common' },
		{ name: 'pikipek', xp: 1500, rarity: 'medium' },
		{ name: 'bounsweet', xp: 1000, rarity: 'common' },
		{ name: 'bounsweet', xp: 800, rarity: 'common' },
		{ name: 'bounsweet', xp: 1500, rarity: 'medium' },
		{ name: 'grubbin', xp: 1000, rarity: 'common' },
		{ name: 'grubbin', xp: 800, rarity: 'common' },
		{ name: 'grubbin', xp: 1500, rarity: 'medium' },
		{ name: 'pansage', xp: 1500, rarity: 'rare' },
		{ name: 'venomoth', xp: 1000, rarity: 'rare' },
		{ name: 'oranguru', xp: 1500, rarity: 'ultra-rare' },
	],
	NIGHT: [
		{ name: 'drifloon', xp: 800, rarity: 'common' },
		{ name: 'drifloon', xp: 1000, rarity: 'common' },
		{ name: 'drifloon', xp: 1500, rarity: 'medium' },
		{ name: 'shelmet', xp: 800, rarity: 'common' },
		{ name: 'shelmet', xp: 1000, rarity: 'common' },
		{ name: 'shelmet', xp: 1500, rarity: 'medium' },
		{ name: 'zubat', xp: 800, rarity: 'common' },
		{ name: 'zubat', xp: 1000, rarity: 'common' },
		{ name: 'zubat', xp: 1500, rarity: 'medium' },
		{ name: 'ekans', xp: 1500, rarity: 'rare' },
		{ name: 'golbat', xp: 1000, rarity: 'rare' },
		{ name: 'noibat', xp: 1000, rarity: 'ultra-rare' },
	],
};
