export const abilityCheckList: {
	name: string;
	url: string;
	todos?: string[];
	handled?: boolean;
}[] = [
	{
		name: 'stench',
		url: 'https://pokeapi.co/api/v2/ability/1/',
		handled: true,
	},
	{
		name: 'drizzle',
		url: 'https://pokeapi.co/api/v2/ability/2/',
		handled: true,
	},
	{
		name: 'speed-boost',
		url: 'https://pokeapi.co/api/v2/ability/3/',
		handled: true,
	},
	{
		name: 'battle-armor',
		url: 'https://pokeapi.co/api/v2/ability/4/',
		handled: true,
	},
	{
		name: 'sturdy',
		url: 'https://pokeapi.co/api/v2/ability/5/',
		handled: true,
	},
	{
		name: 'damp',
		url: 'https://pokeapi.co/api/v2/ability/6/',
		handled: true,
	},
	{
		name: 'limber',
		url: 'https://pokeapi.co/api/v2/ability/7/',
		handled: true,
	},
	{
		name: 'sand-veil',
		url: 'https://pokeapi.co/api/v2/ability/8/',
		handled: true,
	},
	{
		name: 'static',
		url: 'https://pokeapi.co/api/v2/ability/9/',
		handled: true,
	},
	{
		name: 'volt-absorb',
		url: 'https://pokeapi.co/api/v2/ability/10/',
		handled: true,
	},

	{
		name: 'water-absorb',
		url: 'https://pokeapi.co/api/v2/ability/11/',
		handled: true,
	},
	{
		name: 'oblivious',
		url: 'https://pokeapi.co/api/v2/ability/12/',
		handled: true,
	},
	{
		name: 'cloud-nine',
		url: 'https://pokeapi.co/api/v2/ability/13/',
		handled: true,
	},
	{
		name: 'compound-eyes',
		url: 'https://pokeapi.co/api/v2/ability/14/',
		handled: true,
	},
	{
		name: 'insomnia',
		url: 'https://pokeapi.co/api/v2/ability/15/',
		handled: true,
	},
	{
		name: 'color-change',
		url: 'https://pokeapi.co/api/v2/ability/16/',
		handled: true,
	},
	{
		name: 'immunity',
		url: 'https://pokeapi.co/api/v2/ability/17/',
		handled: true,
	},
	{
		name: 'flash-fire',
		url: 'https://pokeapi.co/api/v2/ability/18/',
		handled: true,
	},
	{
		name: 'shield-dust',
		url: 'https://pokeapi.co/api/v2/ability/19/',
		handled: true,
	},
	{
		name: 'own-tempo',
		url: 'https://pokeapi.co/api/v2/ability/20/',
		handled: true,
	},

	{
		name: 'suction-cups',
		url: 'https://pokeapi.co/api/v2/ability/21/',
		handled: true,
	},
	{
		name: 'intimidate',
		url: 'https://pokeapi.co/api/v2/ability/22/',
		handled: true,
	},
	{
		name: 'shadow-tag',
		url: 'https://pokeapi.co/api/v2/ability/23/',
		handled: true,
	},
	{
		name: 'rough-skin',
		url: 'https://pokeapi.co/api/v2/ability/24/',
		handled: true,
	},
	{
		name: 'wonder-guard',
		url: 'https://pokeapi.co/api/v2/ability/25/',
		handled: true,
	},
	{
		name: 'levitate',
		url: 'https://pokeapi.co/api/v2/ability/26/',
		handled: true,
	},
	{
		name: 'effect-spore',
		url: 'https://pokeapi.co/api/v2/ability/27/',
		handled: true,
	},
	{
		name: 'synchronize',
		url: 'https://pokeapi.co/api/v2/ability/28/',
		handled: true,
	},
	{
		name: 'clear-body',
		url: 'https://pokeapi.co/api/v2/ability/29/',
		handled: true,
	},
	{
		name: 'natural-cure',
		url: 'https://pokeapi.co/api/v2/ability/30/',
		handled: true,
	},
	{
		name: 'lightning-rod',
		url: 'https://pokeapi.co/api/v2/ability/31/',
		handled: true,
	},
	{
		name: 'serene-grace',
		url: 'https://pokeapi.co/api/v2/ability/32/',
		handled: true,
	},
	{
		name: 'swift-swim',
		url: 'https://pokeapi.co/api/v2/ability/33/',
		handled: true,
	},
	{
		name: 'chlorophyll',
		url: 'https://pokeapi.co/api/v2/ability/34/',
		handled: true,
	},
	{
		name: 'illuminate',
		url: 'https://pokeapi.co/api/v2/ability/35/',
		handled: true,
	},
	{
		name: 'trace',
		url: 'https://pokeapi.co/api/v2/ability/36/',
		handled: true,
	},
	{
		name: 'huge-power',
		url: 'https://pokeapi.co/api/v2/ability/37/',
		handled: true,
	},
	{
		name: 'poison-point',
		url: 'https://pokeapi.co/api/v2/ability/38/',
		handled: true,
	},
	{
		name: 'inner-focus',
		url: 'https://pokeapi.co/api/v2/ability/39/',
		handled: true,
	},
	{
		name: 'magma-armor',
		url: 'https://pokeapi.co/api/v2/ability/40/',
		handled: true,
	},
	{
		name: 'water-veil',
		url: 'https://pokeapi.co/api/v2/ability/41/',
		handled: true,
	},
	{
		name: 'magnet-pull',
		url: 'https://pokeapi.co/api/v2/ability/42/',
		handled: true,
	},
	{
		name: 'soundproof',
		url: 'https://pokeapi.co/api/v2/ability/43/',
		handled: true,
	},
	{
		name: 'rain-dish',
		url: 'https://pokeapi.co/api/v2/ability/44/',
		handled: true,
	},
	{
		name: 'sand-stream',
		url: 'https://pokeapi.co/api/v2/ability/45/',
		handled: true,
	},
	{
		name: 'pressure',
		url: 'https://pokeapi.co/api/v2/ability/46/',
		handled: true,
	},
	{
		name: 'thick-fat',
		url: 'https://pokeapi.co/api/v2/ability/47/',
		handled: true,
	},
	{
		name: 'early-bird',
		url: 'https://pokeapi.co/api/v2/ability/48/',
		handled: true,
	},
	{
		name: 'flame-body',
		url: 'https://pokeapi.co/api/v2/ability/49/',
		handled: true,
	},
	{
		name: 'run-away',
		url: 'https://pokeapi.co/api/v2/ability/50/',
		handled: true,
	},
	{
		name: 'vital-spirit',
		url: 'https://pokeapi.co/api/v2/ability/72/',
		handled: true,
	},
	{
		name: 'white-smoke',
		url: 'https://pokeapi.co/api/v2/ability/73/',
		handled: true,
	},
	{
		name: 'pure-power',
		url: 'https://pokeapi.co/api/v2/ability/74/',
		handled: true,
	},
	{
		name: 'shell-armor',
		url: 'https://pokeapi.co/api/v2/ability/75/',
		handled: true,
	},
	{
		name: 'air-lock',
		url: 'https://pokeapi.co/api/v2/ability/76/',
		handled: true,
	},
	{
		name: 'tangled-feet',
		url: 'https://pokeapi.co/api/v2/ability/77/',
		handled: true,
	},
	{
		name: 'motor-drive',
		url: 'https://pokeapi.co/api/v2/ability/78/',
		handled: true,
	},
	{
		name: 'rivalry',
		url: 'https://pokeapi.co/api/v2/ability/79/',
		handled: true,
	},
	{
		name: 'keen-eye',
		url: 'https://pokeapi.co/api/v2/ability/51/',
		handled: true,
	},
	{
		name: 'hyper-cutter',
		url: 'https://pokeapi.co/api/v2/ability/52/',
		handled: true,
	},
	{
		name: 'pickup',
		url: 'https://pokeapi.co/api/v2/ability/53/',
		handled: true,
	},
	{
		name: 'truant',
		url: 'https://pokeapi.co/api/v2/ability/54/',
		handled: true,
	},
	{
		name: 'hustle',
		url: 'https://pokeapi.co/api/v2/ability/55/',
		handled: true,
	},
	{
		name: 'cute-charm',
		url: 'https://pokeapi.co/api/v2/ability/56/',
		handled: true,
	},
	{ name: 'plus', url: 'https://pokeapi.co/api/v2/ability/57/', handled: true },
	{
		name: 'minus',
		url: 'https://pokeapi.co/api/v2/ability/58/',
		handled: true,
	},

	{
		name: 'shed-skin',
		url: 'https://pokeapi.co/api/v2/ability/61/',
		handled: true,
	},
	{ name: 'guts', url: 'https://pokeapi.co/api/v2/ability/62/', handled: true },
	{
		name: 'marvel-scale',
		url: 'https://pokeapi.co/api/v2/ability/63/',
		handled: true,
	},
	{
		name: 'liquid-ooze',
		url: 'https://pokeapi.co/api/v2/ability/64/',
		handled: true,
	},
	{
		name: 'overgrow',
		url: 'https://pokeapi.co/api/v2/ability/65/',
		handled: true,
	},
	{
		name: 'blaze',
		url: 'https://pokeapi.co/api/v2/ability/66/',
		handled: true,
	},
	{
		name: 'torrent',
		url: 'https://pokeapi.co/api/v2/ability/67/',
		handled: true,
	},
	{
		name: 'swarm',
		url: 'https://pokeapi.co/api/v2/ability/68/',
		handled: true,
	},
	{
		name: 'rock-head',
		url: 'https://pokeapi.co/api/v2/ability/69/',
		handled: true,
	},
	{
		name: 'drought',
		url: 'https://pokeapi.co/api/v2/ability/70/',
		handled: true,
	},
	{
		name: 'arena-trap',
		url: 'https://pokeapi.co/api/v2/ability/71/',
		handled: true,
	},
	{
		name: 'steadfast',
		url: 'https://pokeapi.co/api/v2/ability/80/',
		handled: true,
	},
	{
		name: 'snow-cloak',
		url: 'https://pokeapi.co/api/v2/ability/81/',
		handled: true,
	},
	{
		name: 'gluttony',
		url: 'https://pokeapi.co/api/v2/ability/82/',
		handled: true,
	},
	{
		name: 'anger-point',
		url: 'https://pokeapi.co/api/v2/ability/83/',
		handled: true,
	},
	{
		name: 'unburden',
		url: 'https://pokeapi.co/api/v2/ability/84/',
		handled: true,
	},
	{
		name: 'heatproof',
		url: 'https://pokeapi.co/api/v2/ability/85/',
		handled: true,
	},
	{
		name: 'simple',
		url: 'https://pokeapi.co/api/v2/ability/86/',
		handled: true,
	},
	{
		name: 'dry-skin',
		url: 'https://pokeapi.co/api/v2/ability/87/',
		handled: true,
	},
	{
		name: 'download',
		url: 'https://pokeapi.co/api/v2/ability/88/',
		handled: true,
	},
	{
		name: 'iron-fist',
		url: 'https://pokeapi.co/api/v2/ability/89/',
		handled: true,
	},
	{
		name: 'poison-heal',
		url: 'https://pokeapi.co/api/v2/ability/90/',
		handled: true,
	},
	{
		name: 'adaptability',
		url: 'https://pokeapi.co/api/v2/ability/91/',
		handled: true,
	},
	{
		name: 'skill-link',
		url: 'https://pokeapi.co/api/v2/ability/92/',
		handled: true,
	},
	{
		name: 'hydration',
		url: 'https://pokeapi.co/api/v2/ability/93/',
		handled: true,
	},
	{
		name: 'solar-power',
		url: 'https://pokeapi.co/api/v2/ability/94/',
		handled: true,
	},
	{
		name: 'quick-feet',
		url: 'https://pokeapi.co/api/v2/ability/95/',
		handled: true,
	},
	{
		name: 'normalize',
		url: 'https://pokeapi.co/api/v2/ability/96/',
		handled: true,
	},
	{
		name: 'sniper',
		url: 'https://pokeapi.co/api/v2/ability/97/',
		handled: true,
	},
	{
		name: 'magic-guard',
		url: 'https://pokeapi.co/api/v2/ability/98/',
		handled: true,
	},
	{
		name: 'no-guard',
		url: 'https://pokeapi.co/api/v2/ability/99/',
		handled: true,
	},
	{
		name: 'stall',
		url: 'https://pokeapi.co/api/v2/ability/100/',
		handled: true,
	},
	{
		name: 'technician',
		url: 'https://pokeapi.co/api/v2/ability/101/',
		handled: true,
	},
	{
		name: 'leaf-guard',
		url: 'https://pokeapi.co/api/v2/ability/102/',
		handled: true,
	},
	{
		name: 'klutz',
		url: 'https://pokeapi.co/api/v2/ability/103/',
		handled: true,
	},
	{
		name: 'sticky-hold',
		url: 'https://pokeapi.co/api/v2/ability/60/',
		handled: true,
	},
	{
		name: 'super-luck',
		url: 'https://pokeapi.co/api/v2/ability/105/',
		handled: true,
	},
	{
		name: 'aftermath',
		url: 'https://pokeapi.co/api/v2/ability/106/',
		handled: true,
	},

	{
		name: 'unaware',
		url: 'https://pokeapi.co/api/v2/ability/109/',
		handled: true,
	},
	{
		name: 'tinted-lens',
		url: 'https://pokeapi.co/api/v2/ability/110/',
		handled: true,
	},
	{
		name: 'filter',
		url: 'https://pokeapi.co/api/v2/ability/111/',
		handled: true,
	},
	{
		name: 'solid-rock',
		url: 'https://pokeapi.co/api/v2/ability/116/',
		handled: true,
	},
	{
		name: 'snow-warning',
		url: 'https://pokeapi.co/api/v2/ability/117/',
		handled: true,
	},
	{
		name: 'honey-gather',
		url: 'https://pokeapi.co/api/v2/ability/118/',
		handled: true,
	},
	{
		name: 'frisk',
		url: 'https://pokeapi.co/api/v2/ability/119/',
		handled: true,
	},
	{
		name: 'reckless',
		url: 'https://pokeapi.co/api/v2/ability/120/',
		handled: true,
	},
	{
		name: 'flower-gift',
		url: 'https://pokeapi.co/api/v2/ability/122/',
		handled: true,
	},
	{
		name: 'bad-dreams',
		url: 'https://pokeapi.co/api/v2/ability/123/',
		handled: true,
	},
	{
		name: 'pickpocket',
		url: 'https://pokeapi.co/api/v2/ability/124/',
		handled: true,
	},
	{
		name: 'sheer-force',
		url: 'https://pokeapi.co/api/v2/ability/125/',
		handled: true,
	},
	{
		name: 'contrary',
		url: 'https://pokeapi.co/api/v2/ability/126/',
		handled: true,
	},
	{
		name: 'unnerve',
		url: 'https://pokeapi.co/api/v2/ability/127/',
		handled: true,
	},
	{
		name: 'defiant',
		url: 'https://pokeapi.co/api/v2/ability/128/',
		handled: true,
	},
	{
		name: 'slow-start',
		url: 'https://pokeapi.co/api/v2/ability/112/',
		handled: true,
	},
	{
		name: 'scrappy',
		url: 'https://pokeapi.co/api/v2/ability/113/',
		handled: true,
	},
	{
		name: 'storm-drain',
		url: 'https://pokeapi.co/api/v2/ability/114/',
		handled: true,
	},
	{
		name: 'ice-body',
		url: 'https://pokeapi.co/api/v2/ability/115/',
		handled: true,
	},
	{
		name: 'defeatist',
		url: 'https://pokeapi.co/api/v2/ability/129/',
		handled: true,
	},
	{
		name: 'cursed-body',
		url: 'https://pokeapi.co/api/v2/ability/130/',
		handled: true,
	},
	{
		name: 'healer',
		url: 'https://pokeapi.co/api/v2/ability/131/',
		handled: true,
	},
	{
		name: 'friend-guard',
		url: 'https://pokeapi.co/api/v2/ability/132/',
		handled: true,
	},
	{
		name: 'weak-armor',
		url: 'https://pokeapi.co/api/v2/ability/133/',
		handled: true,
	},
	{
		name: 'heavy-metal',
		url: 'https://pokeapi.co/api/v2/ability/134/',
		handled: true,
	},
	{
		name: 'light-metal',
		url: 'https://pokeapi.co/api/v2/ability/135/',
		handled: true,
	},
	{
		name: 'multiscale',
		url: 'https://pokeapi.co/api/v2/ability/136/',
		handled: true,
	},
	{
		name: 'toxic-boost',
		url: 'https://pokeapi.co/api/v2/ability/137/',
		handled: true,
	},
	{
		name: 'flare-boost',
		url: 'https://pokeapi.co/api/v2/ability/138/',
		handled: true,
	},
	{
		name: 'harvest',
		url: 'https://pokeapi.co/api/v2/ability/139/',
		handled: true,
	},
	{
		name: 'telepathy',
		url: 'https://pokeapi.co/api/v2/ability/140/',
		handled: true,
	},
	{
		name: 'moody',
		url: 'https://pokeapi.co/api/v2/ability/141/',
		handled: true,
	},
	{
		name: 'overcoat',
		url: 'https://pokeapi.co/api/v2/ability/142/',
		handled: true,
	},
	{
		name: 'poison-touch',
		url: 'https://pokeapi.co/api/v2/ability/143/',
		handled: true,
	},
	{
		name: 'regenerator',
		url: 'https://pokeapi.co/api/v2/ability/144/',
		handled: true,
	},
	{
		name: 'big-pecks',
		url: 'https://pokeapi.co/api/v2/ability/145/',
		handled: true,
	},
	{
		name: 'sand-rush',
		url: 'https://pokeapi.co/api/v2/ability/146/',
		handled: true,
	},
	{
		name: 'wonder-skin',
		url: 'https://pokeapi.co/api/v2/ability/147/',
		handled: true,
	},

	{
		name: 'infiltrator',
		url: 'https://pokeapi.co/api/v2/ability/151/',
		handled: true,
	},
	{
		name: 'mummy',
		url: 'https://pokeapi.co/api/v2/ability/152/',
		handled: true,
	},
	{
		name: 'moxie',
		url: 'https://pokeapi.co/api/v2/ability/153/',
		handled: true,
	},
	{
		name: 'justified',
		url: 'https://pokeapi.co/api/v2/ability/154/',
		handled: true,
	},
	{
		name: 'rattled',
		url: 'https://pokeapi.co/api/v2/ability/155/',
		handled: true,
	},

	{
		name: 'sap-sipper',
		url: 'https://pokeapi.co/api/v2/ability/157/',
		handled: true,
	},
	{
		name: 'prankster',
		url: 'https://pokeapi.co/api/v2/ability/158/',
		handled: true,
	},
	{
		name: 'sand-force',
		url: 'https://pokeapi.co/api/v2/ability/159/',
		handled: true,
	},
	{
		name: 'iron-barbs',
		url: 'https://pokeapi.co/api/v2/ability/160/',
		handled: true,
	},

	{
		name: 'victory-star',
		url: 'https://pokeapi.co/api/v2/ability/162/',
		handled: true,
	},
	{
		name: 'aroma-veil',
		url: 'https://pokeapi.co/api/v2/ability/165/',
		handled: true,
	},
	{
		name: 'flower-veil',
		url: 'https://pokeapi.co/api/v2/ability/166/',
		handled: true,
	},
	{
		name: 'protean',
		url: 'https://pokeapi.co/api/v2/ability/168/',
		handled: true,
	},
	{
		name: 'fur-coat',
		url: 'https://pokeapi.co/api/v2/ability/169/',
		handled: true,
	},
	{
		name: 'magician',
		url: 'https://pokeapi.co/api/v2/ability/170/',
		handled: true,
	},
	{
		name: 'bulletproof',
		url: 'https://pokeapi.co/api/v2/ability/171/',
		handled: true,
	},
	{
		name: 'competitive',
		url: 'https://pokeapi.co/api/v2/ability/172/',
		handled: true,
	},
	{
		name: 'strong-jaw',
		url: 'https://pokeapi.co/api/v2/ability/173/',
		handled: true,
	},
	{
		name: 'refrigerate',
		url: 'https://pokeapi.co/api/v2/ability/174/',
		handled: true,
	},
	{
		name: 'sweet-veil',
		url: 'https://pokeapi.co/api/v2/ability/175/',
		handled: true,
	},

	{
		name: 'gale-wings',
		url: 'https://pokeapi.co/api/v2/ability/177/',
		handled: true,
	},
	{
		name: 'mega-launcher',
		url: 'https://pokeapi.co/api/v2/ability/178/',
		handled: true,
	},
	{
		name: 'grass-pelt',
		url: 'https://pokeapi.co/api/v2/ability/179/',
		handled: true,
	},

	{
		name: 'tough-claws',
		url: 'https://pokeapi.co/api/v2/ability/181/',
		handled: true,
	},
	{
		name: 'pixilate',
		url: 'https://pokeapi.co/api/v2/ability/182/',
		handled: true,
	},
	{
		name: 'gooey',
		url: 'https://pokeapi.co/api/v2/ability/183/',
		handled: true,
	},
	{
		name: 'aerilate',
		url: 'https://pokeapi.co/api/v2/ability/184/',
		handled: true,
	},
	{
		name: 'parental-bond',
		url: 'https://pokeapi.co/api/v2/ability/185/',
		handled: true,
	},
	{
		name: 'dark-aura',
		url: 'https://pokeapi.co/api/v2/ability/186/',
		handled: true,
	},
	{
		name: 'fairy-aura',
		url: 'https://pokeapi.co/api/v2/ability/187/',
		handled: true,
	},
	{
		name: 'aura-break',
		url: 'https://pokeapi.co/api/v2/ability/188/',
		handled: true,
	},

	{
		name: 'stamina',
		url: 'https://pokeapi.co/api/v2/ability/192/',
		handled: true,
	},
	{
		name: 'water-compaction',
		url: 'https://pokeapi.co/api/v2/ability/195/',
		handled: true,
	},
	{
		name: 'merciless',
		url: 'https://pokeapi.co/api/v2/ability/196/',
		handled: true,
	},

	{
		name: 'water-bubble',
		url: 'https://pokeapi.co/api/v2/ability/199/',
		handled: true,
	},
	{
		name: 'steelworker',
		url: 'https://pokeapi.co/api/v2/ability/200/',
		handled: true,
	},
	{
		name: 'berserk',
		url: 'https://pokeapi.co/api/v2/ability/201/',
		handled: true,
	},
	{
		name: 'slush-rush',
		url: 'https://pokeapi.co/api/v2/ability/202/',
		handled: true,
	},
	{
		name: 'long-reach',
		url: 'https://pokeapi.co/api/v2/ability/203/',
		handled: true,
	},
	{
		name: 'liquid-voice',
		url: 'https://pokeapi.co/api/v2/ability/204/',
		handled: true,
	},
	{
		name: 'triage',
		url: 'https://pokeapi.co/api/v2/ability/205/',
		handled: true,
	},
	{
		name: 'galvanize',
		url: 'https://pokeapi.co/api/v2/ability/206/',
		handled: true,
	},
	{
		name: 'surge-surfer',
		url: 'https://pokeapi.co/api/v2/ability/207/',
		handled: true,
	},
	{
		name: 'corrosion',
		url: 'https://pokeapi.co/api/v2/ability/212/',
		handled: true,
	},
	{
		name: 'comatose',
		url: 'https://pokeapi.co/api/v2/ability/213/',
		handled: true,
	},
	{
		name: 'queenly-majesty',
		url: 'https://pokeapi.co/api/v2/ability/214/',
		handled: true,
	},
	{
		name: 'innards-out',
		url: 'https://pokeapi.co/api/v2/ability/215/',
		handled: true,
	},
	{
		name: 'dancer',
		url: 'https://pokeapi.co/api/v2/ability/216/',
		handled: true,
	},
	{
		name: 'battery',
		url: 'https://pokeapi.co/api/v2/ability/217/',
		handled: true,
	},
	{
		name: 'fluffy',
		url: 'https://pokeapi.co/api/v2/ability/218/',
		handled: true,
	},

	{
		name: 'tangling-hair',
		url: 'https://pokeapi.co/api/v2/ability/221/',
		handled: true,
	},
	{
		name: 'beast-boost',
		url: 'https://pokeapi.co/api/v2/ability/224/',
		handled: true,
	},

	{
		name: 'electric-surge',
		url: 'https://pokeapi.co/api/v2/ability/226/',
		handled: true,
	},
	{
		name: 'psychic-surge',
		url: 'https://pokeapi.co/api/v2/ability/227/',
		handled: true,
	},
	{
		name: 'grassy-surge',
		url: 'https://pokeapi.co/api/v2/ability/229/',
		handled: true,
	},
	{
		name: 'misty-surge',
		url: 'https://pokeapi.co/api/v2/ability/228/',
		handled: true,
	},
	{
		name: 'full-metal-body',
		url: 'https://pokeapi.co/api/v2/ability/230/',
		handled: true,
	},
	{
		name: 'shadow-shield',
		url: 'https://pokeapi.co/api/v2/ability/231/',
		handled: true,
	},
	{
		name: 'prism-armor',
		url: 'https://pokeapi.co/api/v2/ability/232/',
		handled: true,
	},
	{
		name: 'neuroforce',
		url: 'https://pokeapi.co/api/v2/ability/233/',
		handled: true,
	},
	{
		name: 'intrepid-sword',
		url: 'https://pokeapi.co/api/v2/ability/234/',
		handled: true,
	},
	{
		name: 'dauntless-shield',
		url: 'https://pokeapi.co/api/v2/ability/235/',
		handled: true,
	},
	{
		name: 'libero',
		url: 'https://pokeapi.co/api/v2/ability/236/',
		handled: true,
	},
	{
		name: 'ball-fetch',
		url: 'https://pokeapi.co/api/v2/ability/237/',
		handled: true,
	},
	{
		name: 'cotton-down',
		url: 'https://pokeapi.co/api/v2/ability/238/',
		handled: true,
	},

	{
		name: 'steam-engine',
		url: 'https://pokeapi.co/api/v2/ability/243/',
		handled: true,
	},
	{
		name: 'punk-rock',
		url: 'https://pokeapi.co/api/v2/ability/244/',
		handled: true,
	},

	{
		name: 'ice-scales',
		url: 'https://pokeapi.co/api/v2/ability/246/',
		handled: true,
	},
	{
		name: 'ripen',
		url: 'https://pokeapi.co/api/v2/ability/247/',
		handled: true,
	},

	{
		name: 'power-spot',
		url: 'https://pokeapi.co/api/v2/ability/249/',
		handled: true,
	},
	{
		name: 'screen-cleaner',
		url: 'https://pokeapi.co/api/v2/ability/251/',
		handled: true,
	},
	{
		name: 'steely-spirit',
		url: 'https://pokeapi.co/api/v2/ability/252/',
		handled: true,
	},
	{
		name: 'wandering-spirit',
		url: 'https://pokeapi.co/api/v2/ability/254/',
		handled: true,
	},
	{
		name: 'gorilla-tactics',
		url: 'https://pokeapi.co/api/v2/ability/255/',
		handled: true,
	},

	{
		name: 'pastel-veil',
		url: 'https://pokeapi.co/api/v2/ability/257/',
		handled: true,
	},
	{ name: 'hunger-switch', url: 'https://pokeapi.co/api/v2/ability/258/' },
	{ name: 'quick-draw', url: 'https://pokeapi.co/api/v2/ability/259/' },
	{ name: 'unseen-fist', url: 'https://pokeapi.co/api/v2/ability/260/' },
	{ name: 'curious-medicine', url: 'https://pokeapi.co/api/v2/ability/261/' },
	{ name: 'transistor', url: 'https://pokeapi.co/api/v2/ability/262/' },
	{ name: 'dragons-maw', url: 'https://pokeapi.co/api/v2/ability/263/' },
	{ name: 'chilling-neigh', url: 'https://pokeapi.co/api/v2/ability/264/' },
	{ name: 'grim-neigh', url: 'https://pokeapi.co/api/v2/ability/265/' },
	{ name: 'as-one-glastrier', url: 'https://pokeapi.co/api/v2/ability/266/' },
	{ name: 'as-one-spectrier', url: 'https://pokeapi.co/api/v2/ability/267/' },
	{ name: 'lingering-aroma', url: 'https://pokeapi.co/api/v2/ability/268/' },
	{ name: 'seed-sower', url: 'https://pokeapi.co/api/v2/ability/269/' },
	{ name: 'thermal-exchange', url: 'https://pokeapi.co/api/v2/ability/270/' },
	{ name: 'anger-shell', url: 'https://pokeapi.co/api/v2/ability/271/' },
	{ name: 'purifying-salt', url: 'https://pokeapi.co/api/v2/ability/272/' },
	{ name: 'well-baked-body', url: 'https://pokeapi.co/api/v2/ability/273/' },
	{ name: 'wind-rider', url: 'https://pokeapi.co/api/v2/ability/274/' },
	{ name: 'guard-dog', url: 'https://pokeapi.co/api/v2/ability/275/' },
	{ name: 'rocky-payload', url: 'https://pokeapi.co/api/v2/ability/276/' },
	{ name: 'wind-power', url: 'https://pokeapi.co/api/v2/ability/277/' },
	{ name: 'zero-to-hero', url: 'https://pokeapi.co/api/v2/ability/278/' },
	{ name: 'commander', url: 'https://pokeapi.co/api/v2/ability/279/' },
	{ name: 'electromorphosis', url: 'https://pokeapi.co/api/v2/ability/280/' },
	{ name: 'protosynthesis', url: 'https://pokeapi.co/api/v2/ability/281/' },
	{ name: 'quark-drive', url: 'https://pokeapi.co/api/v2/ability/282/' },
	{ name: 'good-as-gold', url: 'https://pokeapi.co/api/v2/ability/283/' },
	{ name: 'vessel-of-ruin', url: 'https://pokeapi.co/api/v2/ability/284/' },
	{ name: 'sword-of-ruin', url: 'https://pokeapi.co/api/v2/ability/285/' },
	{ name: 'tablets-of-ruin', url: 'https://pokeapi.co/api/v2/ability/286/' },
	{ name: 'beads-of-ruin', url: 'https://pokeapi.co/api/v2/ability/287/' },
	{ name: 'orichalcum-pulse', url: 'https://pokeapi.co/api/v2/ability/288/' },
	{ name: 'hadron-engine', url: 'https://pokeapi.co/api/v2/ability/289/' },
	{ name: 'opportunist', url: 'https://pokeapi.co/api/v2/ability/290/' },
	{ name: 'cud-chew', url: 'https://pokeapi.co/api/v2/ability/291/' },
	{ name: 'sharpness', url: 'https://pokeapi.co/api/v2/ability/292/' },
	{ name: 'supreme-overlord', url: 'https://pokeapi.co/api/v2/ability/293/' },
	{ name: 'costar', url: 'https://pokeapi.co/api/v2/ability/294/' },
	{ name: 'toxic-debris', url: 'https://pokeapi.co/api/v2/ability/295/' },
	{ name: 'armor-tail', url: 'https://pokeapi.co/api/v2/ability/296/' },
	{ name: 'earth-eater', url: 'https://pokeapi.co/api/v2/ability/297/' },
	{ name: 'mycelium-might', url: 'https://pokeapi.co/api/v2/ability/298/' },
	{ name: 'minds-eye', url: 'https://pokeapi.co/api/v2/ability/299/' },
	{ name: 'supersweet-syrup', url: 'https://pokeapi.co/api/v2/ability/300/' },
	{ name: 'hospitality', url: 'https://pokeapi.co/api/v2/ability/301/' },
	{ name: 'toxic-chain', url: 'https://pokeapi.co/api/v2/ability/302/' },
	{ name: 'embody-aspect', url: 'https://pokeapi.co/api/v2/ability/303/' },
	{ name: 'tera-shift', url: 'https://pokeapi.co/api/v2/ability/304/' },
	{ name: 'tera-shell', url: 'https://pokeapi.co/api/v2/ability/305/' },
	{ name: 'teraform-zero', url: 'https://pokeapi.co/api/v2/ability/306/' },
	{ name: 'poison-puppeteer', url: 'https://pokeapi.co/api/v2/ability/307/' },
	{ name: 'mountaineer', url: 'https://pokeapi.co/api/v2/ability/10001/' },
	{ name: 'wave-rider', url: 'https://pokeapi.co/api/v2/ability/10002/' },
	{ name: 'skater', url: 'https://pokeapi.co/api/v2/ability/10003/' },
	{ name: 'thrust', url: 'https://pokeapi.co/api/v2/ability/10004/' },
	{ name: 'perception', url: 'https://pokeapi.co/api/v2/ability/10005/' },
	{ name: 'parry', url: 'https://pokeapi.co/api/v2/ability/10006/' },
	{ name: 'instinct', url: 'https://pokeapi.co/api/v2/ability/10007/' },
	{ name: 'dodge', url: 'https://pokeapi.co/api/v2/ability/10008/' },
	{ name: 'jagged-edge', url: 'https://pokeapi.co/api/v2/ability/10009/' },
	{ name: 'frostbite', url: 'https://pokeapi.co/api/v2/ability/10010/' },
	{ name: 'tenacity', url: 'https://pokeapi.co/api/v2/ability/10011/' },
	{ name: 'pride', url: 'https://pokeapi.co/api/v2/ability/10012/' },
	{ name: 'deep-sleep', url: 'https://pokeapi.co/api/v2/ability/10013/' },
	{ name: 'power-nap', url: 'https://pokeapi.co/api/v2/ability/10014/' },
	{ name: 'spirit', url: 'https://pokeapi.co/api/v2/ability/10015/' },
	{ name: 'warm-blanket', url: 'https://pokeapi.co/api/v2/ability/10016/' },
	{ name: 'gulp', url: 'https://pokeapi.co/api/v2/ability/10017/' },
	{ name: 'herbivore', url: 'https://pokeapi.co/api/v2/ability/10018/' },
	{ name: 'sandpit', url: 'https://pokeapi.co/api/v2/ability/10019/' },
	{ name: 'hot-blooded', url: 'https://pokeapi.co/api/v2/ability/10020/' },
	{ name: 'medic', url: 'https://pokeapi.co/api/v2/ability/10021/' },
	{ name: 'life-force', url: 'https://pokeapi.co/api/v2/ability/10022/' },
	{ name: 'lunchbox', url: 'https://pokeapi.co/api/v2/ability/10023/' },
	{ name: 'nurse', url: 'https://pokeapi.co/api/v2/ability/10024/' },
	{ name: 'melee', url: 'https://pokeapi.co/api/v2/ability/10025/' },
	{ name: 'sponge', url: 'https://pokeapi.co/api/v2/ability/10026/' },
	{ name: 'bodyguard', url: 'https://pokeapi.co/api/v2/ability/10027/' },
	{ name: 'hero', url: 'https://pokeapi.co/api/v2/ability/10028/' },
	{ name: 'last-bastion', url: 'https://pokeapi.co/api/v2/ability/10029/' },
	{ name: 'stealth', url: 'https://pokeapi.co/api/v2/ability/10030/' },
	{ name: 'vanguard', url: 'https://pokeapi.co/api/v2/ability/10031/' },
	{ name: 'nomad', url: 'https://pokeapi.co/api/v2/ability/10032/' },
	{ name: 'sequence', url: 'https://pokeapi.co/api/v2/ability/10033/' },
	{ name: 'grass-cloak', url: 'https://pokeapi.co/api/v2/ability/10034/' },
	{ name: 'celebrate', url: 'https://pokeapi.co/api/v2/ability/10035/' },
	{ name: 'lullaby', url: 'https://pokeapi.co/api/v2/ability/10036/' },
	{ name: 'calming', url: 'https://pokeapi.co/api/v2/ability/10037/' },
	{ name: 'daze', url: 'https://pokeapi.co/api/v2/ability/10038/' },
	{ name: 'frighten', url: 'https://pokeapi.co/api/v2/ability/10039/' },
	{ name: 'interference', url: 'https://pokeapi.co/api/v2/ability/10040/' },
	{ name: 'mood-maker', url: 'https://pokeapi.co/api/v2/ability/10041/' },
	{ name: 'confidence', url: 'https://pokeapi.co/api/v2/ability/10042/' },
	{ name: 'fortune', url: 'https://pokeapi.co/api/v2/ability/10043/' },
	{ name: 'bonanza', url: 'https://pokeapi.co/api/v2/ability/10044/' },
	{ name: 'explode', url: 'https://pokeapi.co/api/v2/ability/10045/' },
	{ name: 'omnipotent', url: 'https://pokeapi.co/api/v2/ability/10046/' },
	{ name: 'share', url: 'https://pokeapi.co/api/v2/ability/10047/' },
	{ name: 'black-hole', url: 'https://pokeapi.co/api/v2/ability/10048/' },
	{ name: 'shadow-dash', url: 'https://pokeapi.co/api/v2/ability/10049/' },
	{ name: 'sprint', url: 'https://pokeapi.co/api/v2/ability/10050/' },
	{ name: 'disgust', url: 'https://pokeapi.co/api/v2/ability/10051/' },
	{ name: 'high-rise', url: 'https://pokeapi.co/api/v2/ability/10052/' },
	{ name: 'climber', url: 'https://pokeapi.co/api/v2/ability/10053/' },
	{ name: 'flame-boost', url: 'https://pokeapi.co/api/v2/ability/10054/' },
	{ name: 'aqua-boost', url: 'https://pokeapi.co/api/v2/ability/10055/' },
	{ name: 'run-up', url: 'https://pokeapi.co/api/v2/ability/10056/' },
	{ name: 'conqueror', url: 'https://pokeapi.co/api/v2/ability/10057/' },
	{ name: 'shackle', url: 'https://pokeapi.co/api/v2/ability/10058/' },
	{ name: 'decoy', url: 'https://pokeapi.co/api/v2/ability/10059/' },
	{ name: 'shield', url: 'https://pokeapi.co/api/v2/ability/10060/' },
	/**
	 * BANISHED
	 */
	{ name: 'wimp-out', url: 'https://pokeapi.co/api/v2/ability/193/' },
	{ name: 'emergency-exit', url: 'https://pokeapi.co/api/v2/ability/194/' },
	{ name: 'primordial-sea', url: 'https://pokeapi.co/api/v2/ability/189/' },
	{ name: 'desolate-land', url: 'https://pokeapi.co/api/v2/ability/190/' },
	{ name: 'delta-stream', url: 'https://pokeapi.co/api/v2/ability/191/' },
	{ name: 'forecast', url: 'https://pokeapi.co/api/v2/ability/59/' },
	{ name: 'mold-breaker', url: 'https://pokeapi.co/api/v2/ability/104/' },
	{ name: 'anticipation', url: 'https://pokeapi.co/api/v2/ability/107/' },
	{ name: 'forewarn', url: 'https://pokeapi.co/api/v2/ability/108/' },
	{ name: 'multitype', url: 'https://pokeapi.co/api/v2/ability/121/' },
	{ name: 'analytic', url: 'https://pokeapi.co/api/v2/ability/148/' },
	{ name: 'illusion', url: 'https://pokeapi.co/api/v2/ability/149/' },
	{ name: 'imposter', url: 'https://pokeapi.co/api/v2/ability/150/' },
	{ name: 'magic-bounce', url: 'https://pokeapi.co/api/v2/ability/156/' },
	{ name: 'zen-mode', url: 'https://pokeapi.co/api/v2/ability/161/' },
	{ name: 'turboblaze', url: 'https://pokeapi.co/api/v2/ability/163/' },
	{ name: 'teravolt', url: 'https://pokeapi.co/api/v2/ability/164/' },
	{ name: 'cheek-pouch', url: 'https://pokeapi.co/api/v2/ability/167/' },
	{ name: 'stance-change', url: 'https://pokeapi.co/api/v2/ability/176/' },
	{ name: 'symbiosis', url: 'https://pokeapi.co/api/v2/ability/180/' },
	{ name: 'shields-down', url: 'https://pokeapi.co/api/v2/ability/197/' },
	{ name: 'stakeout', url: 'https://pokeapi.co/api/v2/ability/198/' },
	{ name: 'schooling', url: 'https://pokeapi.co/api/v2/ability/208/' },
	{ name: 'disguise', url: 'https://pokeapi.co/api/v2/ability/209/' },
	{ name: 'battle-bond', url: 'https://pokeapi.co/api/v2/ability/210/' },
	{ name: 'power-construct', url: 'https://pokeapi.co/api/v2/ability/211/' },
	{ name: 'dazzling', url: 'https://pokeapi.co/api/v2/ability/219/' },
	{ name: 'soul-heart', url: 'https://pokeapi.co/api/v2/ability/220/' },
	{ name: 'receiver', url: 'https://pokeapi.co/api/v2/ability/222/' },
	{ name: 'power-of-alchemy', url: 'https://pokeapi.co/api/v2/ability/223/' },
	{ name: 'rks-system', url: 'https://pokeapi.co/api/v2/ability/225/' },
	{ name: 'propeller-tail', url: 'https://pokeapi.co/api/v2/ability/239/' },
	{ name: 'mirror-armor', url: 'https://pokeapi.co/api/v2/ability/240/' },
	{ name: 'gulp-missile', url: 'https://pokeapi.co/api/v2/ability/241/' },
	{ name: 'stalwart', url: 'https://pokeapi.co/api/v2/ability/242/' },
	{ name: 'sand-spit', url: 'https://pokeapi.co/api/v2/ability/245/' },
	{ name: 'ice-face', url: 'https://pokeapi.co/api/v2/ability/248/' },
	{ name: 'mimicry', url: 'https://pokeapi.co/api/v2/ability/250/' },
	{ name: 'perish-body', url: 'https://pokeapi.co/api/v2/ability/253/' },
	{ name: 'neutralizing-gas', url: 'https://pokeapi.co/api/v2/ability/256/' },
];

export const abilityNames = [
	'stench',
	'drizzle',
	'speed-boost',
	'limber',
	'battle-armor',
	'shell-armor',
	'sturdy',
	'damp',
	'sand-veil',
	'static',
	'volt-absorb',
	'water-absorb',
	'oblivious',
	'cloud-nine',
	'air-lock',
	'compound-eyes',
	'immunity',
	'flash-fire',
	'insomnia',
	'color-change',
	'shield-dust',
	'own-tempo',
	'suction-cups',
	'inner-focus',
	'magma-armor',
	'intimidate',
	'shadow-tag',
	'rough-skin',
	'wonder-guard',
	'levitate',
	'effect-spore',
	'synchronize',
	'clear-body',
	'white-smoke',
	'natural-cure',
	'lightning-rod',
	'serene-grace',
	'swift-swim',
	'chlorophyll',
	'water-veil',
	'illuminate',
	'trace',
	'huge-power',
	'pure-power',
	'poison-point',
	'magnet-pull',
	'soundproof',
	'rain-dish',
	'sand-stream',
	'pressure',
	'thick-fat',
	'early-bird',
	'flame-body',
	'tangled-feet',
	'motor-drive',
	'run-away',
	'rivalry',
	'keen-eye',
	'hyper-cutter',
	'pickup',
	'truant',
	'hustle',
	'cute-charm',
	'plus',
	'minus',
	'shed-skin',
	'guts',
	'marvel-scale',
	'liquid-ooze',
	'overgrow',
	'blaze',
	'torrent',
	'swarm',
	'rock-head',
	'drought',
	'arena-trap',
	'steadfast',
	'snow-cloak',
	'gluttony',
	'anger-point',
	'unburden',
	'heatproof',
	'simple',
	'dry-skin',
	'download',
	'iron-fist',
	'poison-heal',
	'adaptability',
	'skill-link',
	'hydration',
	'solar-power',
	'quick-feet',
	'normalize',
	'sniper',
	'magic-guard',
	'no-guard',
	'stall',
	'technician',
	'leaf-guard',
	'klutz',
	'sticky-hold',
	'super-luck',
	'aftermath',
	'unaware',
	'tinted-lens',
	'filter',
	'solid-rock',
	'snow-warning',
	'honey-gather',
	'frisk',
	'reckless',
	'flower-gift',
	'bad-dreams',
	'pickpocket',
	'sheer-force',
	'contrary',
	'unnerve',
	'defiant',
	'slow-start',
	'scrappy',
	'storm-drain',
	'ice-body',
	'defeatist',
	'cursed-body',
	'healer',
	'friend-guard',
	'weak-armor',
	'heavy-metal',
	'light-metal',
	'multiscale',
	'toxic-boost',
	'flare-boost',
	'harvest',
	'telepathy',
	'moody',
	'overcoat',
	'poison-touch',
	'regenerator',
	'big-pecks',
	'sand-rush',
	'wonder-skin',
	'infiltrator',
	'mummy',
	'moxie',
	'justified',
	'rattled',
	'sap-sipper',
	'prankster',
	'sand-force',
	'iron-barbs',
	'victory-star',
	'aroma-veil',
	'flower-veil',
	'protean',
	'fur-coat',
	'magician',
	'bulletproof',
	'competitive',
	'strong-jaw',
	'refrigerate',
	'sweet-veil',
	'gale-wings',
	'mega-launcher',
	'grass-pelt',
	'tough-claws',
	'pixilate',
	'gooey',
	'aerilate',
	'parental-bond',
	'dark-aura',
	'fairy-aura',
	'aura-break',
	'stamina',
	'water-compaction',
	'merciless',
	'water-bubble',
	'steelworker',
	'berserk',
	'slush-rush',
	'long-reach',
	'liquid-voice',
	'triage',
	'galvanize',
	'surge-surfer',
	'corrosion',
	'comatose',
	'queenly-majesty',
	'innards-out',
	'dancer',
	'battery',
	'fluffy',
	'tangling-hair',
	'beast-boost',
	'electric-surge',
	'psychic-surge',
	'grassy-surge',
	'misty-surge',
	'full-metal-body',
	'shadow-shield',
	'prism-armor',
	'neuroforce',
	'intrepid-sword',
	'dauntless-shield',
	'libero',
	'ball-fetch',
	'cotton-down',
	'steam-engine',
	'punk-rock',
	'ice-scales',
	'ripen',
	'power-spot',
	'screen-cleaner',
	'steely-spirit',
	'wandering-spirit',
	'gorilla-tactics',
	'pastel-veil',
] as const;

export type AbilityName = (typeof abilityNames)[number];
