export const mapIds = [
  //KUMA VERSION
  "camp",
  "campCave",
  "campLaboratory",
  "routeN1",
  "routeN1E1",
  "routeE1",
  "onixCave",
  "routeS1E1",
  "routeS1",
  "routeS1W1",
  "routeW1",
  "routeN1W1",
  "caveW1",
  "caveW1F1",
  "caveW1F2",
  "caveN1W1",
  "challengeField",
  "randomField",
  "rocketCamp",
  "victoryRoad",
  "victoryRoadU1",
  "victoryRoadExtra",
  "victoryRoadExit",
  "pokemonLeague",
  "apricornClearing",
  "ilex-forest",
  "murasaki-glades",
  //LABYRINTH VERSION
  "labyrinth_level_1",
  "labyrinth_level_2",
] as const;
export type MapId = (typeof mapIds)[number];
