export const routes = [
	'OVERWORLD',
	'MAIN',
	'BAG',
	'TEAM',
	'BATTLE',
	'MARKET',
	'BUY_MARKET',
	'SELL_MARKET',
	'STORAGE',
	'STARTER_SELECTION',
	'SPRITE_SELECTION',
	'SETTINGS',
	'QUESTS',
	'MAP_MAKER_CAMP',
	'MAP_MAKER_ROUTEN1',
	'MAP_MAKER_ROUTES1',
	'FARM',
	'FOSSIL_REVIVER',
	'CAMP_UPGRADES',
	'BULLETIN_BOARD',
	'APRICORN_SMITHY',
] as const;
export type RoutesType = (typeof routes)[number];
